### ISSUE TITLE
Transition effects

### ISSUE THREAD

**Issue by junardoclarit** [fancyapps/ui#103]
How do you change the transition effect on v4? Instead of slide i want to use fade. because in v3 you just need to change the `transitionEffect` property. Thanks

**Comment by fancyapps** [comment]
Hi,

Sorry, there are currently no options for that, but that is planned to implement.

**Comment by Pixelous** [comment]
fancyapps, any ETA for this?)

**Comment by fancyapps** [comment]
@Pixelous  Sorry, it is not possible to give any ETA, it can change unexpectedly at any time.

**Comment by DmitrySheklein** [comment]
@fancyapps This is very important. The current animation slows down even on iMac 27

**Comment by netbbe** [comment]
+1

**Comment by daniellelecomte** [comment]
+1

**Comment by nathanielperales** [comment]
+1

**Comment by yiiness** [comment]
+3

**Comment by yiiness** [comment]
waste the time

**Comment by fancyapps** [comment]
Hello, everyone!

After a year of full time work, v5 is finally here, and it provides transition effects - https://fancyapps.com/fancybox/#examples
