### ISSUE TITLE
PDF content not displayed in Fancybox 4.0.0 Alpha 2

### ISSUE THREAD

**Issue by toxpal** [fancyapps/ui#11]
Used v3 for years to display images and PDF files. Noticed v4 is available and upgraded today. Unfortunately, PDF content is not displayed in v4. All I see is an white placeholder. Are there any special requirements for new version to display PDF content?

In v3, it was enough to add this:

`data-type="iframe"`

**Comment by fancyapps** [comment]
Hi,

Use `data-type="pdf"` and it will work the same as in v3. `data-type="iframe"` would also work, but you would have to disable preloading by adding `data-preload="false"`. 

Sorry, I just right now added chapter to docs about PDF, but I have not yet updated homepage.

**Comment by toxpal** [comment]
Thank you, works great.

**Comment by toxpal** [comment]
Sorry for re-opening the issue, but I found this option (`data-type="pdf"`) doesn't work in FireFox. However, old option (`data-fancybox data-type="iframe" data-preload="false"`) works in FireFox and other browsers (but pop-up window looks different when compared to `data-type="pdf"`

When saying "doesn't work", I mean that FF opens popup window, but it has no data and is only several pixels height. Using the latest version of Fancybox and FF (also tested using older versions of plugin and FF - the issue still exists).

**Comment by fancyapps** [comment]
@toxpal Thanks for reporting, it should work fine after upgrading to the latest.
