### ISSUE TITLE
Trouble getting events to fire

### ISSUE THREAD

**Issue by ginagregory** [fancyapps/ui#12]
I'm having a hard time getting the 'load' or 'done' event to fire. For the code below, the init works fine, but the load event doesn't fire. My popup is just one slide (a modal), not sure if that matters.

```
var popup = new Fancybox(
{
  type: 'ajax', 
  src: '/?view=popup-email'
},
{
  on: {
    init: function(fancybox, slide) {
     console.log('fancybox init');
    },
   load: function(fancybox, slide) {
     console.log('fancybox loaded content');
   }
  }
});
```

I've also tried it this way:
```
popup.on("load", function(fancybox, slide) {
  console.log('fancybox loaded content');
});
```
But that doesn't work for me either. What am I doing wrong?

Basically what I need is to know when the HTML has been added to the page so I can set up some new events on those elements in the popup.

**Comment by ginagregory** [comment]
Upon further testing, the load event only seems to fire if I have multiple slides. Is this intentional? How can we get a load event for a single slide (modal)?

**Comment by fancyapps** [comment]
Hi,

Thanks for the report, there was a problem with callbacks, but it should be fixed in the latest release.

You should use `reveal` callback, because at that point the content will already be in the correct place and you will be able to do whatever you want with it. You can access your content using `slide.$content`:

```js
var popup = new Fancybox(
  [{
    type: 'ajax', 
    src: 'ajax_page'
  }],
  {
    on: {
      init: function(fancybox, slide) {
        console.log('Fancybox init');
      },
      reveal: function(fancybox, slide) {
        console.log('Fancybox is going to reveal this content:');
        console.log(slide.$content);
      }
    }
  });
```
