### ISSUE TITLE
Triggering Fancybox.show() on a td with a <a> link tag bug

### ISSUE THREAD

**Issue by cascading-jox** [fancyapps/ui#122]
Hi, I have a table containing a td with an event listener to trigger Fancybox.show(). The td contains a link tag and clicking on the link tag closes the fancybox immediately after opening but clicking outside the link tag but inside the td (which the click event is registered on) is behaving normally. 

Reproducible example: https://codepen.io/cascading-jox/pen/yLXPJwZ

**Comment by fancyapps** [comment]
Hi,

You simply have to stop default click action, like this:

```js
let genContent = "<div>hello fancy</div>";
document.querySelector(".fancyTbl").addEventListener("click", (e) => {
  e.preventDefault();
  
  Fancybox.show([
    {
      src: genContent,
      type: "html",
      dragToClose: false
      // Panzoom: {
      //   draggableClass: false,
      //   draggingClass: false,
      // },
    }
  ]);
});

```
