### ISSUE TITLE
Disable grab cursor

### ISSUE THREAD

**Issue by EricToTheJohansson** [fancyapps/ui#124]
This just might be being stupid, but I've read the documentation of Fancybox for and can't seem to disable the grab cursor and moving the "slide" functions and the grab to close function.

I have an inline HTML-element that I open with:
Fancybox.show([{ src: '#mediafiles' + game_id, type: 'inline', dragToClose: false }]);

**Comment by fancyapps** [comment]
Hi,

Not all options can be set individually per slide, use it like this:

```js
Fancybox.show([{ 
  src: '#mediafiles' + game_id, 
  type: 'inline'
}], {
  dragToClose: false 
});
```
