### ISSUE TITLE
Selector

### ISSUE THREAD

**Issue by Pixelous** [fancyapps/ui#127]
Hi,

I am trying to init Fancybox with variable:

```
var selector = fancyboxWrapper[i].querySelectorAll(".fancybox-item");
Fancybox.bind(selector, {
    groupAll: true
  });
```

but no luck.

Any hints?

**Comment by fancyapps** [comment]
Hi,

Sorry, only CSS selectors (`DOMString` type, [similarly to querySelector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector)) are currently accepted.
