### ISSUE TITLE
Close Button 

### ISSUE THREAD

**Issue by Pixelous** [fancyapps/ui#129]
Hi,

I am trying to get close button 

```
on: {
      initLayout: (fancybox) => {
		var fancyboxContainer = fancybox.$container;
		console.log( fancyboxContainer );
		var closeButton = fancyboxContainer.querySelector(".is-close");
		console.log( closeButton );
        //console.log( fancybox.$container );
      },
    },
```

but

`console.log( closeButton );`

returns null.

init, initLayout, initCarousel, ready do not work for close button.

Can you please fix it?

**Comment by fancyapps** [comment]
Hi,

It does not work that way for close button. In fact, there are 3 types of close button:

1) In the toolbar - it is part of the Toolbar plugin
2) For HTML content (or Toolbar is disabled), close button is created for each slide by default and is accessible like this:
`Fancybox.getInstance().getSlide().$closeButton`.
3) If `closeButton` is set to `outside` (and Toolbar is disabled or content is HTML), then one close button is created per instance:
`Fancybox.getInstance().$closeButton`.

In all cases, close button will not be available during `initLayout` event, you can access it later, but that depends.

**Comment by Pixelous** [comment]
@fancyapps you sure it works? Coz 

console.log( Fancybox.getInstance() );

returns null for me.

This:

```
const test = new Fancybox.bind(".gallery-container-wrapper a", {
    groupAll: true,
   Thumbs: false,
   Toolbar: false,
   closeButton: "top",
});

test.on("done", (fancybox, slide) => {
  console.log( fancybox );
});
```
Uncaught TypeError: test.on is not a function

**Comment by fancyapps** [comment]
I hoped you will figure out that you can replace `Fancybox.getInstance()` with `instance` variable that is available as the first argument from any callback. `Fancybox.getInstance()` returns instance from anywhere when any instance is already active.
