### ISSUE TITLE
Can you increase the image switching effect？

### ISSUE THREAD

**Issue by qinxs** [fancyapps/ui#134]
The current mode of switching（`translate3d(xxxpx, 0, 0)`）makes you dizzy

## Compare：
- [Fancybox](https://fancyapps.com/docs/ui/fancybox/plugins/image/#gallery-1)
- [Bing](https://cn.bing.com/images/search?view=detailV2&ccid=z%2FF33162&id=DAC411D5FBD46B119381789C7AD92AB3A9021D71&thid=OIP-C.z_F33162LmYNo717dTefQQHaLC&mediaurl=https%3A%2F%2Finews.gtimg.com%2Fnewsapp_match%2F0%2F8584903870%2F0&exph=928&expw=623&q=黄梦莹&simid=608042806613512841&form=IRPRST&ck=683BFB36D0029DFD2DCA84A2FE70394B&selectedindex=43&ajaxhist=0&ajaxserp=0&vt=0&sim=11)

**Comment by fancyapps** [comment]
Hi,

Sorry, but I do not understand your comment. You want to change sliding speed when clicking on navigation arrows? You can disable or change duration using `Carousel.friction` option, for example:

`Fancybox.defaults.Carousel = { friction : 0};`

**Comment by qinxs** [comment]
I see. Thank you
