### ISSUE TITLE
Thumbnail navigation is not displayed for less than 3 images

### ISSUE THREAD

**Issue by cokuna-pavelkosolapov** [fancyapps/ui#135]
Hello.
i'm creating a vue component for fancybox in my project and  have curious issue. I don't have any thumbnail navi panel if i have less then 3 pictures  in the group

// fancypic.vue
```
<template>
    <div 
        class="preview-item"
        :style="{ backgroundImage: `url(${preview})` }"        
        :data-src="source"
        :data-thumb="thumb"
        :data-fancybox="group"
    >
        <div>
            <button type="button">
                <i class="far fa-expand-alt"></i>
            </button>
        </div>
    </div>
</template>

<script>
import { Fancybox } from "@fancyapps/ui"
import "@fancyapps/ui/dist/fancybox.css"

export default {
    name: 'fancypic',
    props: {
        group: {
            type: String,
            default: 'gallery'
        },
        source: String,
        preview: String,
        thumb: String
    },
    mounted() {
        Fancybox.bind('[data-fancybox]')
    }
}
</script>
```

The Component creates picture and initializes fancybox plugin. Fancybox creates gallery with arrow and thumbnail navigation. It works fine, but only if i have more then 2 pictures. Didn't found any explanations for this in the manuel page. Grateful for any suggestions.

usage:
// fancy-gallery.vue
```
<template>
    <div class="preview-gallery">
        <fancypic v-for="(pic, ix) in pictures" 
            :key="ix"
            :preview="pic.preview"
            :source="pic.source"
            :thumb="pic.thumb"
        />
    </div>
</template>

<script>
import { fancypic } from "./fancypic"

export default {
    name: 'fancy-gallery',
    components: { fancypic },
    props: {
        pictures: Array
    },
}
</script>

**Comment by fancyapps** [comment]
Hi,

Are you using the latest version?

Default minimum slide count for thumbnails to be displayed is 2, but it was 3 in the early releases - https://fancyapps.com/docs/ui/fancybox/plugins/thumbnails#minSlideCount

**Comment by cokuna-pavelkosolapov** [comment]
I was using the 4.0.0-alpha.4, now i have the 4.0.5, but now i don't see thumbnail navigation at all. xD

**Comment by fancyapps** [comment]
Therefore you have to create demo with your custom code, you can use any Playground of your choice, for example, codesandbox.io

**Comment by cokuna-pavelkosolapov** [comment]
Thank you for support. Suddenly it works, without any changes. Maybe was kind of cache in project, don't know. Sorry for bothering you.
