### ISSUE TITLE
Initializing a specific data-fancybox="<name>" seems not work. 

### ISSUE THREAD

**Issue by amkdev** [fancyapps/ui#141]
Yesterday I noticed that it seems to be unimportant what data-fancybox property value is given to bind fancybox.

```
<a href="XYZ" data-fancybox="gallery" ...
<a href="XYZ" data-fancybox="video-gallery" ...
```

Both are initialized via one 
`Fancybox.bind('[data-fancybox="gallery"]`, ... maybe I'm wrong but it seems only the property itself plays a role - not the value.

In addition I'm a bit confused that initialization of a carousel ( `new Carousel()` ) also activates the fancybox lightbox functionality - the only need is to add the data-fancybox property to any link.

**Comment by fancyapps** [comment]
Hi,

Fancybox is automatically attached to any element having `data-fancybox` attribute. I am now thinking about removing this feature, because some users are confused by that.
