### ISSUE TITLE
Cannot expose `Fancybox` (i.e., put it in global scope) using Webpack's expose-loader

### ISSUE THREAD

**Issue by Abdull** [fancyapps/ui#142]
My build process uses Webpack.

In order to use Fancybox's API, I tried to put Fancybox in a global scope using Webpack's *expose-loader*, just as I successfully did it with jQuery (`$` / `jQuery`) in the past: 

```
// ... snippet from webpack.config.js:
      {
        test: require.resolve('jquery'),
        use: [{
          loader: 'expose-loader',
          options: {
            exposes:  ['$', 'jQuery']
          }
        }]
      },
      {
        test: require.resolve('@fancyapps/ui'),
        use: [{
          loader: 'expose-loader',
          options: {
            exposes: ['Fancybox']
          }
        }]
      },
// ...
```

Unfortunately, this approach doesn't work for *Fancybox*; `Uncaught ReferenceError: Fancybox is not defined`.

Though this approach works for `jQuery` and `$`.

Any ideas how to put `Fancybox` in a global scope when using Webpack?

**Comment by fancyapps** [comment]
Hi,

Sorry, I am not expert of Webpack/expose-loader, therefore I do not know how to answer this question. There is nothing magical/mystical about Fancybox, use it like any other ES6 module. Try asking on relative support forums or Stackoverflow.

Anyway, why don't you simply import Fancybox as ES6 module and expose it by yourself? Smt like this:

```js
import { Fancybox } from "@fancyapps/ui";
window.Fancybox = Fancybox;
```
