### ISSUE TITLE
Internet Explorer 11 - data-fancybox-trigger may not be working

### ISSUE THREAD

**Issue by nealboy** [fancyapps/ui#150]
I don't know if it's worth developing with Internet Explorer in mind these days, but a co-worker noticed on a project where we are using a link to open a Fancybox gallery with 'data-fancybox-trigger,' it doesn't seem to work in IE11.

I didn't dig too deep here to investigate what might be the problem, but I rolled back to Fancybox V3, and it works fine in IE11.

Not sure if this is a known issue, but is it time to just move on from IE, or is it worth fixing?

**Comment by fancyapps** [comment]
Hi,

Sorry, IE11 is not supported. To fix this, it would be necessary to avoid any progress of the modern web.

**Comment by fancyapps** [comment]
I believe it is already dead, even Microsoft 365 services has dropped support (on August 17, 2021).
