### ISSUE TITLE
iOS 15 Safari touch event issue

### ISSUE THREAD

**Issue by jerryc127** [fancyapps/ui#151]
when i drag content up/down to close, the layout cannot close
it cause the website broken, cannot do anything

test website: https://butterfly-backup.vercel.app/Gallery/wallpaper
browser: ios 15 safari

https://user-images.githubusercontent.com/16351105/137273319-32808847-b80d-48dd-bd57-5788e321942c.MP4

**Comment by fancyapps** [comment]
Hi,

Thanks for reporting, I have upgraded to iOS 15 and there seems to be issues with touch events. I will look for a solution.

**Comment by fancyapps** [comment]
This has been fixed in the latest release. However, I will continue to improve UX.
