### ISSUE TITLE
No baseTpl in v4?

### ISSUE THREAD

**Issue by pekka** [fancyapps/ui#152]
I'm trying to move the caption above/before the main image. 
In Fancybox v3, this used to be possible through creating a custom HTML skeleton in `baseTpl`.
There seems no mention of this anymore in v4?

**Comment by EMDM45** [comment]
How right to use template.main option?
if set
`template : {
main : '<div class="test"></div>'
}`
then:
![изображение](https://user-images.githubusercontent.com/38912510/140600085-cf1496aa-ab29-45f0-8ef3-cf74d1706134.png)

I want to use different styles and layouts for Fancybox on one page. Custom - for one html content, default - for images and other html's.
But i don't know how can i do it in Fancybox v4.

**Comment by fancyapps** [comment]
@EMDM45 If you want to customize layout based on your custom criteria, then simply use callbacks to customize the structure. See this example - https://fancyapps.com/playground/16W

If you wish to style something based on content type, then maybe it is sufficient enough to use CSS selectors like `.fancybox__slide.has-image{}`.
