### ISSUE TITLE
Thumbs don't display if they are lazy loaded inside link

### ISSUE THREAD

**Issue by ExileofAranei** [fancyapps/ui#153]
Greetings, faced a problem with lazy loaded images inside A tag.
I created a sandbox with this issue: [https://codesandbox.io/s/fancybox-swiper-lazy-lp4wk](https://codesandbox.io/s/fancybox-swiper-lazy-lp4wk)
Example uses v4.0.5 @fancyapps/ui version.

Steps to reproduce:
I use swiper with lazy load mode enabled, so if I open fancybox at first slide thumbs will be generated only for lazy loaded images inside slider slides, but the fancybox itself still can change slides through all possible slides without showing thumbs (7/10 at screenshot).
![image](https://user-images.githubusercontent.com/41694699/137300431-050cd5d9-2974-43af-90fe-bcc3aa56e234.png)

Any ideas hot to handle this case?

**Comment by fancyapps** [comment]
Hi,

Support for `data-src` and `data-lazy-src` attributes was added in the latest release.

BTW, it would be easier to combine Fancybox with Carousel that is already available for you if you are using Fancybox, see this demo - https://fancyapps.com/playground/16L
