### ISSUE TITLE
Lazyload with srcset

### ISSUE THREAD

**Issue by mmoollllee** [fancyapps/ui#157]
How can lazyloading be used with the `src-set`-Attribute instead of only `data-src`?

**Comment by fancyapps** [comment]
Sorry, forgot to close this issue, support `data-lazy-srcset` was added some time ago.

**Comment by nathanielperales** [comment]
Hi,

Is `data-lazy-srcset` not supported anymore in v5?

What do you recommend we do instead?

Thanks,

**Comment by fancyapps** [comment]
Hi, actually, it is supported, does it not work for you? Can you create a demo?

**Comment by nathanielperales** [comment]
I'll try to get a demo. Do you have a demo of it working? Essentially, the carousel is not choosing the correct srcset image, it's always using the smallest one, making it blurry. Also, is there a place in the documentation that explains how it's supported now?
