### ISSUE TITLE
Fancybox 3 Documentation

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/ui#16]
Glad to see the new Fancybox is finally released, and I'm excited to dig into it. That said, I expect to be using v3 for a while longer, and perhaps indefinitely for existing projects. Is the v3 website/documentation still available?

**Comment by addedlovely** [comment]
https://web.archive.org/web/20210325170940/https://fancyapps.com/fancybox/3/docs/

**Comment by fancyapps** [comment]
Hi,

You can either download from Github - https://github.com/fancyapps/fancybox/blob/master/docs/index.html - or use the link above for online version.
