### ISSUE TITLE
[Suggestion] please add more function to image view

### ISSUE THREAD

**Issue by steve3d** [fancyapps/ui#164]
I would like see more function in image view. for example:

- rotate image clockwise 90 degree, click for increase rotation on clockwise 90 degrees.
- counter-clockwise rotate 90,
- flip image horizontal/vertical.

all these can be easily done with css. please add these. thanks for this project.

**Comment by Eldenroot** [comment]
Rotate image +1 also I would like to see "download" button

**Comment by Eldenroot** [comment]
@fancyapps - wow, great! Just one thing, how to bind to "data-XXX" where XXX is variable? It is changed for every post/page.

I would like to cover all globally.

**Comment by fancyapps** [comment]
@Eldenroot You want to start Fancybox when user clicks on any element that has any data attribute? That is not a good idea. You have to choose some unique attribute or selector.

**Comment by steve3d** [comment]
when can we see these rotation feature?

**Comment by fancyapps** [comment]
Hi,

v5 has been released recently and it offers more functionally, see this example - https://fancyapps.com/fancybox/#transformation-controls
