### ISSUE TITLE
Video (Vimeo) displays at 1px*1,7px on mobile devices because of CSS setting

### ISSUE THREAD

**Issue by ts-mz** [fancyapps/ui#168]
Hi, I'm using fancybox 4 with galleries with mixed image and vimeo content. Everything works great on desktop, but on mobile the videos aren't reliably displayed. The size of the vimeo player is (most of the times) apparently calculated down to a 1px/1,7pixel for most mobile devices in Chrome's inspector.

This appears to be a consequence of a css "min-height:1px" command you're applying to ".fancybox__content". Changing this to something like 100px or 20vh makes the video appear using the correct ratio, although, depending on screen size, not stretched to the left and right border of the content box.

**Comment by fancyapps** [comment]
Works fine for me, iOS 15.
