### ISSUE TITLE
"Named export 'Fancybox' not found" when importing

### ISSUE THREAD

**Issue by nickelswitte** [fancyapps/ui#169]
Hello,

firstly, its a great library, thanks for coding!

I have a question regarding using Fancybox with npm. When installing Fancybox liked described [here](https://fancyapps.com/docs/ui/installation) following these steps

1. `npm install @fancyapps/ui`
2. `import { Fancybox } from "@fancyapps/ui";` in my app.js and `import "fancyapps/ui/dist/fancybox.css";` in my main css file
3. And starting my app

I will get the following error

```
import { Fancybox } from "@fancyapps/ui";
         ^^^^^^^^
SyntaxError: Named export 'Fancybox' not found. The requested module '@fancyapps/ui' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@fancyapps/ui';
const { Fancybox } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:121:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:171:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

The fix described in the error msg works, but what is the issue here? Am I installing Fancybox wrong?

Any help is appreciated, cheers!

**Comment by nickelswitte** [comment]
[Issue #1583](https://github.com/fancyapps/fancybox/issues/1583) seems to be related but it did not help.

**Comment by fancyapps** [comment]
Hi,

I have created two quick demos using popular code playgrounds. As you can see, they work perfectly fine.

- Codesandbox - https://codesandbox.io/s/fancybox-vanilla-js-4uebs?file=/src/index.js
- Stackblitz - https://stackblitz.com/edit/js-dt53bs?file=index.js

So, the question is - how do your settings differ, why doesn't it work for you. Sorry, I'm not a Node expert, I can't tell you the cause of your problem.

Anyway, there is no wrong way to install/include Fancybox. If you can get Fancybox object, then great, it will work just fine. You could also import directly from Fancybox.js file.

**Comment by anakadote** [comment]
Fancybox needs to be rendered client side, so simply wrap your [Fancybox wrapper component](https://fancyapps.com/resources/integration/#vue) with Nuxt's [`<ClientOnly>`](https://nuxt.com/docs/api/components/client-only):

```
<ClientOnly fallback-tag="span" fallback="Loading...">
  <Fancybox>
    <a href="..."><img src="..." alt=""></a>
    <a href="..."><img src="..." alt=""></a>
  </Fancybox>
</ClientOnly>
```
