### ISSUE TITLE
Option 'hideScrollbar' not working

### ISSUE THREAD

**Issue by nickelswitte** [fancyapps/ui#170]
Hello,

for my web app, the option `hideScrollbar` does not seem to work.

Somehow the scrollbar is always there, even when explicitly setting it to `true` in the options.

```javascript
document.addEventListener('DOMContentLoaded', () => {
  
  Fancybox.defaults.Hash = false;

  Fancybox.bind(".card-image a", {
    infinite: false,
    groupAll: true,
    hideScrollbar: true,
    Toolbar: {
      display: [
        "slideshow",
        "fullscreen",
        "thumbs",
        "close",
      ],
    },
  });
});
```

Please find below a screenshot of an image with the scrollbar on the right:
![grafik](https://user-images.githubusercontent.com/36443026/140829154-9cb2e7ab-bf02-4947-aea7-d33457e5effe.png)

When scrolling, the website behind the lightbox is continuing to scroll.

Also, when closing the fancybox, the whole site is moving to the right significantly. This may be to related to the scrollbar, but I am not sure. Zou can see this is this GIF, when closing the image.

![fancybox](https://user-images.githubusercontent.com/36443026/140829871-327abbab-4f2d-466b-8cbb-6f726483b9d1.gif)

Thanks for the help.

**Comment by fancyapps** [comment]
Hi,

The scrollbar is hidden using CSS and something on your page seems to be preventing this. If I could take a look at your page, I think I could quickly determine the cause and help you. 

So, how it works. Fancybox adds `compensate-for-scrollbar` class name to `body` element and then this CSS snippet hides the scrollbar:

```css
body.compensate-for-scrollbar {
    overflow: hidden !important;
}
```
Fancybox then calculates the scrollbar width (this may vary for different browsers and settings) on opening and creates new CSS rule that compensates the missing width of the scrollbar, so that the total width of the body element stays the same and content is not expanding, example:

```css
.compensate-for-scrollbar {
    padding-right: 16.7999267578125px;
}
```

**Comment by nickelswitte** [comment]
Hello,

thanks for the quick reply, it is much appreciated!

Currently I am still in localhost and not hosting anywhere public. Is there a way to easily let you check out my side?
You can find here a screenshot while inspecting the body. The described classes are there, but the overflow seems to just have no effect. You have any idea what can cause this?

![grafik](https://user-images.githubusercontent.com/36443026/140924198-84b1bbaf-bb9f-4a65-8fb2-55ee63e0991f.png)

As a workaround, I overwrote the `.compensate-for-scrollbar` to remove any padding:

```css
.compensate-for-scrollbar {
    padding-right: 0px !important;
}
```

This solution is okay, but I would prefer to have the scrollbar removed.

Thanks a lot,
Cheers!

**Comment by fancyapps** [comment]
Then which element has vertical scroll bar? Maybe `<html>` element? In such case, try smth like this -

```css
.with-fancybox {
  overflow: hidden;
}
```

**Comment by nickelswitte** [comment]
This is now working! Thanks for the help.
