### ISSUE TITLE
Slide draggable areas limited?

### ISSUE THREAD

**Issue by ts-mz** [fancyapps/ui#173]
Hi,

in a lightbox I have  some extended captions, so this issue became noticeable: While animations can be consistently triggered by clicking on navigation arrows and swiping by touching any area without text content, they will not be triggered at all by attempting to swipe from any text element, like the caption. Touching the screen just next to a paragraph within the 'fancybox__caption' will trigger the animation, touching the screen on top of any text within a paragraph will have no effect. For me, this happens in both standard and customized fancybox configurations.

Not sure if this is the intended behavior, but I find it at least unintuitive.

Occasionally one of two "violation" notices are printed in the console "[Violation] Forced reflow while executing Javascript took xx ms" and "[Violation] 'requestAnimationFrame' handler took xx ms", although the timing of the notices seems unrelated to attempting swipe by touching from the caption paragraph.

Thanks!

**Comment by fancyapps** [comment]
Hi,

As the author of Fancybox I can not predict if user will want to select and copy/paste the text or if developer will want to allow users to select the text.

But I can give you a choice, set `Panzoom.textSelection : false` and your text will be unselectable, see this demo - https://fancyapps.com/playground/1eR

```JS
Fancybox.bind('[data-fancybox="gallery"]', {
  Carousel : {
      Panzoom : {
        textSelection : false
      }
    },
});

```

**Comment by ts-mz** [comment]
Thanks! =)
