### ISSUE TITLE
Remove horitontal drag (v4)

### ISSUE THREAD

**Issue by PubliAlex** [fancyapps/ui#174]
Hello,

I'm testing fancybox v4 and you did a very good job.

But I wonder if there is an option remove horizontal dragging, I explored the documentation and it seems there is no option for this.

Thank you

Alex

**Comment by fancyapps** [comment]
Hi,

It would be like this:

```JS
Fancybox.bind('[data-fancybox="gallery"]', {
  Carousel: {
    Panzoom: {
      touch: false,
    },
  },
});
```

Demo - https://fancyapps.com/playground/1fO

**Comment by PubliAlex** [comment]
Thank you it works, I didn't tought to look to the carousel documentation
