### ISSUE TITLE
Conflict between autoFocus and trapFocus options

### ISSUE THREAD

**Issue by ExileofAranei** [fancyapps/ui#175]
Greetings, found an unexpectable behavior with Fancybox ```autoFocus``` and ```trapFocus``` options.
Here's an example: [https://fancyapps.com/playground/1gg](https://fancyapps.com/playground/1gg)
When ```Fancybox.defaults.autoFocus``` is set to ```false```, I expect that input won't be auto focused, but seems like ```trapFocus``` option itself focuses any first focusable element. I can disable this option too, but I definitely want to keep trap focus active.

**Comment by fancyapps** [comment]
Hi,

Thanks for reporting, I will look into this next week (here in Latvia, we celebrate Proclamation Day and we have a holiday).

**Comment by fancyapps** [comment]
This has been fixed in the latest release.
