### ISSUE TITLE
Bug with options

### ISSUE THREAD

**Issue by somegooser** [fancyapps/ui#179]
It looks like fancybox forgets / ignores the options i pass as a parameter the second time.

I log every key event in the console. The first time only escape and enter keys triggers and the second time i call this every keyboard function triggers.

I also get this error "Node cannot be found in the current page." if i try to get document.activeElement the SECOND time. The first time it works.

Example:

```js
Fancybox.show([{
                    src: content,
                    type: 'html'
                }], {
                    keyboard: {
                        Escape: "",
                        Enter: ""
                    },
                    autoFocus: false,
                    trapFocus: false,
                    placeFocusBack: false,
                    dragToClose: false,
                    click: false,
                    on: {
                        keydown: function(fancybox, key, event) {
                            console.log(key);
                      }
});
```

**Comment by fancyapps** [comment]
Hi,

Sorry, but I do not understand your comment. What do you mean by "i pass as a parameter the second time".

Your snippet works fine (after fixing syntax error) and I do not see any issue:

```js
Fancybox.show([{
  src: 'content',
  type: 'html'
}], {
  keyboard: {
    Escape: "",
    Enter: ""
  },
  autoFocus: false,
  trapFocus: false,
  placeFocusBack: false,
  dragToClose: false,
  click: false,
  on: {
    keydown: function(fancybox, key, event) {
      console.log(key);
    }
  }
});
```

**Comment by fancyapps** [comment]
Sorry, there seems to be some misunderstanding - "it should limit itself to escape and enter" - actually no, it is not supposed to work like that. You use `keyboard` option to specify which API method to execute when pressing a particular key (https://fancyapps.com/docs/ui/fancybox/options#keyboard), for example:

```js
keyboard: {
  Escape: "close",
  Enter: "close"
}
```
If you pass `Escape: "",` then it actually does nothing, because such API method does not exist.

**Comment by fancyapps** [comment]
FYI, it is also possible to pass a method:

```js
Escape: function() { console.log('Escape!'); },
```
