### ISSUE TITLE
Fancybox trigger on dragging

### ISSUE THREAD

**Issue by thyash11** [fancyapps/ui#18]
Hi, from your documentation(v4), I couldn't find a way to disable Fancybox while dragging.

https://codepen.io/thyash11/pen/jOmVwRP

Please let me know, Thanks.

**Comment by fancyapps** [comment]
Hi,

The logic must be the other way around. Your code should handle click event and prevent default click action (e..g, `event.preventDefault();`) when dragging is detected. That is how every carousel/slider script (should) work. Fancybox (like any other lightbox/modal script) then checks if `event.defaultPrevented` and returns if it is true.

**Comment by thyash11** [comment]
Thank You, I solved it by setting links to pointer-events: none while dragging.

**Comment by franco-onevillas** [comment]
Hi,

I am testing the fancybox Carousel and wondering if you know how to prevent the default on vue (to make some calculations if the drag is vertical or more horizontal). I tried event handlers but actually didn't work for click nor dragging.

Thanks :)

**Comment by fancyapps** [comment]
@franco-onevillas Sorry, I cold not understand your question (what is "on vue"), could you please elaborate? Basically, calculate drag distance using pointer/mouse events and then inside click event decide if default action should be prevented.

**Comment by franco-onevillas** [comment]
Hi @fancyapps , thanks for answering me.

Regarding "on vue" I was talking about the Vue framework and how to stop the dragging event there.

I have this issue https://github.com/fancyapps/ui/issues/222 and I am trying to catch the drag event to make some calculations but can't stop the dragging to happen.

Thanks again
