### ISSUE TITLE
[Request] Support multiple classnames in classNames option object

### ISSUE THREAD

**Issue by albanyacademy** [fancyapps/ui#180]
Writing space-separated CSS classes for the classNames option results in an error. e.g.
```
...
classNames:
                    {
                        main: "carousel__nav banner-slider__nav",
                        button: "carousel__button banner-slider__nav-button",
                        next: "is-next",
                        prev: "is-prev",
                    }
...
```
prompts this error in the dialogue:
```
Uncaught DOMException: String contains an invalid character
```

Being able to use the default fancybox CSS classnames with the option of adding additional classes for specific usages would allow for more DRY implementations of the Carousel - I don't want to completely change the button CSS, just have more control in tweaking it slightly in different usages.

**Comment by fancyapps** [comment]
Hi,

It should work fine after updating to the latest version.
