### ISSUE TITLE
Scroll bug with scroll-behavior: smooth; when closing fancybox

### ISSUE THREAD

**Issue by hexcross** [fancyapps/ui#183]
I found strange bug, when I had set CSS `html {scroll-behavior: smooth;}` and close the fancybox. 
When closed (or closed with esc key) the page will scroll to the top. I tried change some of focus options but bug is still there..

You can simply reproduce this bug on your website by adding CSS. 

Browsers: Chrome latest, Safari..

**Comment by fancyapps** [comment]
Hi,

This should be fixed in the latest release using this CSS rule:

```css
html.with-fancybox {
    scroll-behavior: auto;
}
```
