### ISSUE TITLE
Lazyloading large image in Fancybox

### ISSUE THREAD

**Issue by ChristopherRobinSuperStar** [fancyapps/ui#186]
Is it possible to load large image only after click on thumbnail or after opening Fancybox?

**Comment by fancyapps** [comment]
Hi,

Sorry, I do not understand your question. That is the main goal of Fancybox - to download and display large version of the image when needed (right after clicking on the thumbnail).

**Comment by ChristopherRobinSuperStar** [comment]
My question related to the carousel first slide large version of the image.

**Comment by fancyapps** [comment]
Sorry, I do not understand your comment. What large version, what image?

**Comment by ChristopherRobinSuperStar** [comment]
Sorry. I used img tag inside a picture tag. 
Need support for data-lazy-srcset

**Comment by ChristopherRobinSuperStar** [comment]
Is it possible to add support for picture tag and data-lazy-srcset?

**Comment by fancyapps** [comment]
I would like your first comment to be as follows - "I have this demo where ... but I would like ... to work ..., because ". It would have saved you and me time. At the moment, I'm still not sure if I understand you. It is still not clear what component are you talking about.

**Comment by ChristopherRobinSuperStar** [comment]
I would like something like this...
```
<div id="myCarousel" class="carousel">
  <div class="carousel__slide">
    <picture>
	<source data-lazy-srcset="https://lipsum.app/id/1/1200x675" type="image/webp">
        <img data-lazy-src="https://lipsum.app/id/1/1200x675">
    </picture>
  </div>
  <div class="carousel__slide">
    <picture>
        <source data-lazy-srcset="https://lipsum.app/id/2/1200x675" type="image/webp">
        <img data-lazy-src="https://lipsum.app/id/2/1200x675">
    </picture>   
  </div>
  <div class="carousel__slide">
    <picture>
	<source data-lazy-srcset="https://lipsum.app/id/3/1200x675" type="image/webp">
        <img data-lazy-src="https://lipsum.app/id/3/1200x675">
    </picture>
  </div>
</div>
```

**Comment by fancyapps** [comment]
Hi,

The latest update adds support for `data-lazy-srcset` attributes.
