### ISSUE TITLE
Carousel viewport auto height?

### ISSUE THREAD

**Issue by tou0125** [fancyapps/ui#189]
Hi,

is it possible to adapt the carousel viewport so that the height changes depending on the image height? This is for a case where only one image is shown at a time. When I use images with different heights now, the viewport is the size of the largest image. I would like the viewport to adapt based on the current image.

Please see here: https://codepen.io/sophmek/pen/PoJNvRV
The viewport is grey and as you can see, it is the size of the largest image. I use bootstrap in my use case so I have included it here.

Am I doing something wrong or does that require customisation? 

I have been using Swiper JS but would like to switch to your carousel if possible.

Thanks

Edit: I created my own solution: https://codepen.io/sophmek/pen/GRMqGKO
If there is a better or "official" way, please let me know

**Comment by fancyapps** [comment]
Hi,

Sorry for the late reply. Your solution is OK. Just one note - it is best to use data from the callbacks. For example,

replace 

```js
    selectSlide: (carousel) => {
      //current slide
      var slideselect = document.querySelector(".is-selected");
```

with

```js
selectSlide: (carousel, slide) => {
      //current slide
      var slideselect = slide.$el;
```
