### ISSUE TITLE
Unable to open low resolution images

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/ui#192]
Please try to open these images via FancyBox... I am unable to open them - image error is displayed... anyway when I open it on a new tab (withount fancybox) I can see them. Please can you reproduce?

[rot.zip](https://github.com/fancyapps/ui/files/7688460/rot.zip)

**Comment by fancyapps** [comment]
Hi,

I tried your samples and they worked fine. I can't imagine a reason why they wouldn't work. If possible, please, provide a link to live page/demo.
