### ISSUE TITLE
Carousel drag not work in modal if window has scroll

### ISSUE THREAD

**Issue by averines** [fancyapps/ui#193]
The carousel is placed in a modal/dialog window.
If the modal window does not fit into the browser window, then mouse drag carousel slides stops working. 
At same time switching slide with the navigation and dots buttons works.
If the browser window is enlarged enough to make scrolling disappear, then dragging immediately works again.

https://fancyapps.com/playground/1to

I read the documentation, but I didn't find a solution. Please tell me how to solve this)

**Comment by fancyapps** [comment]
Hi,

I made some tests and decided to remove check for scollable parent. Carousel is now working fine inside scrollable modal.
