### ISSUE TITLE
Carousel with variable width slides

### ISSUE THREAD

**Issue by taksu** [fancyapps/ui#198]
Hi, 
How to make the carousel work with variable width slides?

I did create a demo with virtual slides.
To see what we would like to have, follow the guide in first slide. 
In short: just set the .carousel__slide width to auto and resize the viewport.

See the [Codepen link here.](https://codepen.io/taksu/pen/XWeVyLE)

Thanks.

**Comment by fancyapps** [comment]
Hi,

The script supports variable widths for slides that already exists in the page. I do not think it is possible to support virtual slides with paging and navigation without knowing how many fill fit inside each page.

**Comment by fancyapps** [comment]
Hi,

Here is an example of a carousel with variable width slides:
https://stackblitz.com/edit/js-ssq8xh?file=index.html,index.js,style.css
