### ISSUE TITLE
Fancybox no response after clicking when set hash to false

### ISSUE THREAD

**Issue by xgrei** [fancyapps/ui#199]
browser: Chrome/96.0.4664.110

I use Fancybox with Carousel to show photos. 

I set Hahs to false for Fancybox: `Fancybox.defaults.Hash = false`

But no response after clicking photo unless the page is refreshed.

I try to set `data-lazy-src`  to `src` for img tag, but not working.

May I ask what caused this problem?

Thank you so much. 🙏

```javascript
Fancybox.defaults.Hash = false
let carousel =  new Carousel(container.querySelector('.carousel'), {
  preload: 0,
  infinite: false,
  center: false,
  slidesPerPage: 1,
  friction: 0.5,
  Dots: false,
})

carouselConfig = {
  Dots: true,
  on: {
    change: that => {
      carousel.slideTo(carousel.findPageForSlide(that.page), {
        friction: 0,
      })
    },
  },
}
Fancybox.bind('[data-fancybox="gallery"]', {
  Thumbs: true,
  Toolbar: true,
  closeButton: 'top',
  Carousel: carouselConfig
})

```

**Comment by fancyapps** [comment]
Hi,

Your code snippet works fine - https://fancyapps.com/playground/1yv - so, sorry, it is not possible to help you.
