### ISSUE TITLE
picture slideshow 'autoplay' ?

### ISSUE THREAD

**Issue by lionel-dieu** [fancyapps/ui#2]
Hello, 

Great to see the new version at work.
It was well worth the wait.
Do you intend to make it possible to enable some kind of picture 'autoplay' as was the case with v3 ?

**Comment by fancyapps** [comment]
Hi, Thanks!

Yes of course. Next on the todo list is an optional toolbar plugin that will include slideshow functionality.

**Comment by lionel-dieu** [comment]
Perfect !
Already looking forward to start using it.

**Comment by fancyapps** [comment]
The first beta was released today and it now includes Toolbar plugin by default.

**Comment by lionel-dieu** [comment]
Working great !
Many thanks.

**Comment by alexxxseo** [comment]
Hello!

What about carousel autoplay?
Like this: https://fancyapps.com/playground/Be with autoplay
