### ISSUE TITLE
Thumb images do not showing when there are two object in Programmatic

### ISSUE THREAD

**Issue by mrtyrdm** [fancyapps/ui#20]
` var $imgs = [  {
      src: "https://lipsum.app/id/2/800x600",
      thumb: "https://lipsum.app/id/2/80x80",
      caption: "First image",
  },
  {
      src: "https://lipsum.app/id/3/800x600",
      thumb: "https://lipsum.app/id/3/80x80",
      caption: "Second image",
  },`

but it shows when there are three object

How  can  I solve the problem ?

**Comment by fancyapps** [comment]
Hi,

Thumbnail plugin has `minSlideCount ` option (https://fancyapps.com/docs/ui/fancybox/plugins/thumbnails#minSlideCount) and default value is `3` and therefore thumbnail strip is not displayed for two images. This is how you can change that option -

```JS
Fancybox.show([
  {
    src: "https://lipsum.app/id/2/800x600",
    thumb: "https://lipsum.app/id/2/80x80",
    caption: "First image",
  },
  { src: "https://lipsum.app/id/3/800x600", 
  thumb: "https://lipsum.app/id/3/80x80", 
  caption: "Second image" },
 
], {
  Thumbs : {
    minSlideCount : 2
  }
});
```

**Comment by mrtyrdm** [comment]
Thank's it happened
