### ISSUE TITLE
Fancybox Slideshow autostart issue

### ISSUE THREAD

**Issue by lionel-dieu** [fancyapps/ui#200]
I have a Fancybox Slideshow triggered by an image-hyperlink : slideshow autoStart does not work.
When replacing the image-hyperlink by text-hyperlink, the autoStart is working OK.
Any possible explanation ?

[fancybox-text.txt](https://github.com/fancyapps/ui/files/7814192/fancybox-text.txt)
[fancybox-image.txt](https://github.com/fancyapps/ui/files/7814196/fancybox-image.txt)

**Comment by fancyapps** [comment]
Hi,

I have created two demos based on your code - 

https://jsfiddle.net/dj815n3m/
https://jsfiddle.net/2nkro48q/

and everything works fine. I do not know how to help you.

**Comment by lionel-dieu** [comment]
www.pino-gris.be/_autostart/fancybox-image.htm

**Comment by fancyapps** [comment]
OK, thanks, I'll take a look.

**Comment by fancyapps** [comment]
It should work fine after upgrading to the latest version. 

Since you are using CDN, you will have to wait for it to be updated or you can use the latest version directly:
`https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0.15/dist/fancybox.umd.js`

**Comment by lionel-dieu** [comment]
Looking good at primary testing.
Many many thanks.
