### ISSUE TITLE
Add thumb support to show()

### ISSUE THREAD

**Issue by chrisrowe** [fancyapps/ui#201]
I didn't see any mention of this in the docs, I've skimmed the source but can't see any way to programatically add thumbs like we can when using markup.

Ideally something like the below, is there something I'm missing or is this planned?

```
const fancybox = Fancybox.show([
  {
    src: "https://lipsum.app/id/98/800x600",
    thumb: "https://lipsum.app/id/98/80x60",
    type: "image",
  },
  {
    src: "https://lipsum.app/id/99/800x600",
    thumb: "https://lipsum.app/id/98/80x60",
    type: "image",
  },
]);
```

**Comment by fancyapps** [comment]
Hi,

Your code snippet works as you described - https://fancyapps.com/playground/1A8
