### ISSUE TITLE
Panzoom maxScale

### ISSUE THREAD

**Issue by andre-lx** [fancyapps/ui#202]
hey @fancyapps . 

Saw this issue but didn't work: https://github.com/fancyapps/ui/issues/149

Trying to zoom in a carrousel image, but the max scale looks like that is not making any change.

I'm trying to use like this:

```
    Fancybox.bind("[data-fancybox]", {
        infinite: true,
        click: "next",
        Image: {
            zoom: false,
        },
        Carousel: {
            friction: 0.4,
        },
        Panzoom: {
            zoomFriction: 0.99,
            maxScale: 10,
        },
        Toolbar: {
            display: [
                { id: "prev", position: "center" },
                { id: "counter", position: "center" },
                { id: "next", position: "center" },
                "zoom",
                "fullscreen",
                "thumbs",
                "close",
                //"slideshow",
            ],
        }
    });
```

![image](https://user-images.githubusercontent.com/44682155/148270189-11a696c9-5add-4a84-b851-054198c9a925.png)

All the other elements are working very well.

Thanks

**Comment by fancyapps** [comment]
Hi,

I am very sorry, documentation contains code that worked in the early releases, maxScale should be set like this:

```js
Image: {
  zoom: false,
  Panzoom: {
    zoomFriction: 0.99,
    maxScale: function() {
      return 10;
    },
  },
},
```


Demo - https://fancyapps.com/playground/1Ad

I will update docs with more samples.
