### ISSUE TITLE
data-type="pdf" for url that `redirect` to pdf or `download` pdf

### ISSUE THREAD

**Issue by sadeghbarati** [fancyapps/ui#204]
@fancyapps 

for example if file extension not present in url 
fancybox instead of showing pdf content 

will open black iframe and download it after iframe loaded

**Comment by sadeghbarati** [comment]
```html
<a
  data-fancybox
  data-type="pdf"
  href="/pdfjs/web/viewer.html?/another-url-that-refers-to-pdf-not-file-extionstion"
  >Click me</a
>
```

**Comment by fancyapps** [comment]
Hi,

Could you, please, check it upgrading to the latest (4.0.16) helps with this issue?

**Comment by sadeghbarati** [comment]
I upgrade scripts and add version for remove cache just in case still downloading pdf

```html
<a href="url-of-pdf" data-fancybox="images" data-type="pdf">Show pdf</a>
```

![Screenshot (443)](https://user-images.githubusercontent.com/17789047/148751716-714d16bc-5b8b-47f1-8e7f-2617c33479be.png)

**Comment by sadeghbarati** [comment]
1. please add simple pdf example in [showcase](https://fancyapps.com/showcase)
2. add [pdf.js](https://mozilla.github.io/pdf.js/) example too

**Comment by fancyapps** [comment]
Please create a demo where your issue could be inspected. Sorry, my todo list is so long, that I am not able to complete it...

**Comment by sadeghbarati** [comment]
https://codepen.io/sadeghbarati/pen/abLargK

**Comment by fancyapps** [comment]
But can you open https://github.com/sadeghbarati/staticassets/raw/main/Vue-3-Cheat-Sheet.pdf in the browser? Can you embed it in the iframe tag? I think it is not possible, see https://jsfiddle.net/g6e3p0fL/

**Comment by sadeghbarati** [comment]
`content-disposition inline` solved this issue

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
