### ISSUE TITLE
How to disable zoom animation when Toolbar option is set?

### ISSUE THREAD

**Issue by syshut** [fancyapps/ui#205]
> zoom {Boolean}​
> Do zoom animation from thumbnail image when starting or closing fancybox. Default: true

To disable zoom animation:
https://fancyapps.com/playground/1BK

But it looks like when the Toolbar option is set, the animation activated again:
https://fancyapps.com/playground/1BJ

Is there something wrong?

**Comment by fancyapps** [comment]
Hi,

You have a syntax error in your code, it should be like this:

```js
Fancybox.bind('[data-fancybox="gallery"]', {
  Toolbar: {
    display: [
      "zoom",
      "slideshow",
      "fullscreen",
      "thumbs",
      "close",
    ],
  },
  Image: {
    zoom: false,
    wheel: 'slide',
  },
});

```

https://fancyapps.com/playground/1BQ
