### ISSUE TITLE
Is the code right?

### ISSUE THREAD

**Issue by syshut** [fancyapps/ui#206]
Hi dear Skarnelis，

My fancybox v3 code is like this.

```
	$('[data-fancybox]').fancybox({
		animationEffect: 'fade',
	});
```

And I want to make it the same style and animation in v4, where the code is like this:

```
	Fancybox.bind("[data-fancybox]", {
		showClass: 'fancybox-fadeIn',
		hideClass: 'fancybox-fadeOut',
		animated: true,
		Image : {
			zoom: false
		}
	});
```
https://fancyapps.com/playground/1Cg

Is that right? Because it seems a little different with v3. The animation is not so smooth, and the fade effect (especially fade-out )seems not working.

**Comment by fancyapps** [comment]
Hi,

Unfortunately, there was a problem with Playground and the animations didn't work properly there, but now they're working fine.

Transition effects, including cross-fade, are currently being developed, see #103
