### ISSUE TITLE
Question Regarding Default Zoom Size For Images In Carousel Mode

### ISSUE THREAD

**Issue by SamuelBanya** [fancyapps/ui#209]
Hey there,

So I created an Art Gallery page using your JS library, and think its amazing!

My main question is the default zoom size.

I'm not sure if this is an issue with my thumbnail size, or if this is something that this library can adjust while an image is being viewed in Carousel Mode.

However, the one thing I wanted to ask if how to enlarge the default zoom size by maybe like 1.5x?

I ask because I only see the 'zoom' object key value in the docs to either toggle it on or off. but I kind of just want to display the image a a bit larger by default, as if someone scrolled with their middle mouse scroll wheel a few rotations downward.

For an example, I created my Art Gallery page, so you can see this effect on any image:
https://www.sambanya.com/artgallery.html

The JS can be found for the related GitHub repo for that portion of the site:
https://github.com/SamuelBanya/ArtGalleryCreator2/blob/main/artgallery.js 

Related CSS stylesheet used:
https://github.com/SamuelBanya/ArtGalleryCreator2/blob/main/artgallery.css 

Specific portion of the actual project in which I create image tags using FancyBox on Line 220:
https://github.com/SamuelBanya/ArtGalleryCreator2/blob/main/main.py

Not sure if this is a CSS issue though, so sorry if this isn't FancyBox related! :)

Thanks!

**Comment by fancyapps** [comment]
Hi,

Please, avoid using generic CSS rules, for example, you have this:

```CSS
img {
    padding: 5px;
    background: white;
    border: 2px solid #BBB;
    margin: 7px 14px 7px 0;
    width: 160px;
}
```

if you would replace it with

```CSS
#right_art_gallery img { ...}
```

then everything will work just fine.

**Comment by SamuelBanya** [comment]
Thanks a ton! That fixed the issue :)
