### ISSUE TITLE
Add support for Next/image (React)

### ISSUE THREAD

**Issue by 7iomka** [fancyapps/ui#217]
Hi.
I want to buy your plugin for my gallery, but I see that it not recognize thumbs images if that was <Image/> component from 'next/image'.

`<Image/>` component is a wrapper around native image, but, anyway, fancybox seems not found it.

Code example
```tsx
<a href={item.im} data-fancybox={`gallery_${activeSlug}`}>
                <Image
                  src={item.th}
                  alt=""
                  width={240}
                  height={240}
                  quality={100} // if already optimized
                />
              </a>
```
This is output layout
```html
<a href="/static/images/content/gallery/mirrors/02.jpg" data-fancybox="gallery_all">
   <span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;">
      <span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;">
         <img alt="" aria-hidden="true" src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQwIiBoZWlnaHQ9IjI0MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2ZXJzaW9uPSIxLjEiLz4=" style="display: block; max-width: 100%; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px;">
       </span>
      <img alt="" src="/_next/image?url=%2Fstatic%2Fimages%2Fcontent%2Fgallery%2Fmirrors%2F02-thumb.jpg&amp;w=640&amp;q=100" decoding="async" data-nimg="intrinsic" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%;" srcset="/_next/image?url=%2Fstatic%2Fimages%2Fcontent%2Fgallery%2Fmirrors%2F02-thumb.jpg&amp;w=256&amp;q=100 1x, /_next/image?url=%2Fstatic%2Fimages%2Fcontent%2Fgallery%2Fmirrors%2F02-thumb.jpg&amp;w=640&amp;q=100 2x">
      <noscript></noscript>
   </span>
</a>

```

I have list with that type of links inside gallery.
When I click, inside modal only thumb for clicked item was recognized, rest - none.
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/18473137/151225698-65500f39-6524-4e67-a089-786f5f7d0250.png">

Second click on a next item 
<img width="729" alt="image" src="https://user-images.githubusercontent.com/18473137/151225812-3e0425cb-07e6-4486-8595-b82f530ea4b9.png">

**Comment by 7iomka** [comment]
Repro: https://codesandbox.io/s/busy-cherry-lynso?file=/pages/index.js

**Comment by fancyapps** [comment]
Hello,

Thanks for reporting. The script uses the first image inside the link as a thumbnail, but in your case it is a dummy image, so the result is what it is. I'll change the selector to ignore images with a `aria-hidden` attribute, and then it should work fine.

In the meantime, you can use the `data-thumb` attribute for links to specify a thumbnail.

**Comment by 7iomka** [comment]
> Hello,
> 
> Thanks for reporting. The script uses the first image inside the link as a thumbnail, but in your case it is a dummy image, so the result is what it is. I'll change the selector to ignore images with a `aria-hidden` attribute, and then it should work fine.
> 
> In the meantime, you can use the `data-thumb` attribute for links to specify a thumbnail.

Thanks, I not found in docs about this data attribute.
But, seems problem persist, if you operate with `slide.$thumb.src` in callbacks, result for other thums in gallery can be to aria-hidden image source.

For example, in this demo https://fancyapps.com/playground/vl when you will click to item, thumb can resolve correctly, but if you navigate inside modal to another item of gallery - wrong result.

**Comment by fancyapps** [comment]
I do not understand what and where is wrong, it works perfectly fine to me.
