### ISSUE TITLE
Close react fancybox programmatically

### ISSUE THREAD

**Issue by berdnikov** [fancyapps/ui#225]
Hello. Is it possible to close [react version](https://fancyapps.com/docs/ui/fancybox/react) fancybox programmatically?

**Comment by fancyapps** [comment]
Hi, You store Fancybox object somewhere globally, then use API close() method. Exactly how you do this depends on how you build your project. That react version is just a sample and is a basic wrapper.

Or maybe it would be enough for you to use `data-fancyboox-close` attributes on element to automatically close Fancybox on click event.
