### ISSUE TITLE
Autoplay mechanism, undocumented `fromOpener`

### ISSUE THREAD

**Issue by adriansuter** [fancyapps/ui#226]
Is it possible to add some sort of autoplay mechanism? I mean, first initialize and bind the fancybox, but then immediatly open the fancybox - not by using `Fancybox.show()`.

I found the following undocumented static method: `Fancybox.fromOpener('[data-fancybox="gallery"]');`.

See showcase: https://fancyapps.com/playground/1WR

 It kinda works, but I am not sure if that is the official way to achieve my goal. Is it?

**Comment by fancyapps** [comment]
Hi,

It is a perfectly fine way to start Fancybox from previously used selector. I was hesitant to document this method because I wasn't sure if anyone would find it useful, but it looks like it is and will be added to the documentation.
