### ISSUE TITLE
Vertical scrolling HTML type Fancybox on touch screen in Shadow DOM weirdness

### ISSUE THREAD

**Issue by hedgehog90** [fancyapps/ui#227]
Scrolling is not working properly.
I see the scrollbar, but touch scrolling is 'sticky'.
By 'sticky' I mean I have to move my finger up and down for a second before it starts scrolling.

Try initializing Fancybox in a Shadow DOM with an html slide (with lots of html so it requires scrolling) and you will see the same.
Behaviour confirmed on Android & Desktop (via Chrome debugger's mobile device simulation)

UPDATE: I've noticed this doesn't occur across **all** HTML type Fancyboxes and I can't work out what exactly causes it. I'm not entirely confident this is an issue with Fancybox, possibly an issue from another library.

Will update again if I understand the issue further.

UPDATE: The problem is with fancybox, and more broadly with scrolling in general inside a shadow DOM.
In the following sample I can't scroll up or down with the mouse wheel or touch, despite the scrollbar showing:
https://jsfiddle.net/96pcmjnw/1/

**Comment by fancyapps** [comment]
Hi,

Thanks for the report. I found that the ScrollLock plugin is causing this issue. set `ScrollLock: false` as a temporary fix to disable it. A proper fix will be included in the next release.
