### ISSUE TITLE
Remove fancyapps nav buttons from version 4.X

### ISSUE THREAD

**Issue by ninjadevs19** [fancyapps/ui#229]
is there any way to disable nav buttons from the latest version?

**Comment by fancyapps** [comment]
Hi,

You see, Fancybox is built around Carousel and navigation arrows are actually created by Carousel Navigation plugin, you can disable it like this: 

```JS
Fancybox.bind('[data-fancybox="gallery"]', {
  Carousel: {
    Navigation: false,
  },
});
```

Demo https://fancyapps.com/playground/1ZO
