### ISSUE TITLE
Hidding scrollbar doesn't work

### ISSUE THREAD

**Issue by Nic787** [fancyapps/ui#239]
Hi,

I'm coming from V3 and switching to V4. I have to say that there was more options in the older version like which buttons to show, transition effect, **disabling right click to protect your image**, transition duration, etc.

However, I'm now trying to use the option to hide scrollbar on my site and it doesn't work, so if I use the arrow up and down, it's moving the background page at the same time. http://aurora.nicolas-duclos.com/photographie/nouvelle-zelande/

I use 

```
Fancybox.bind(".fancybox", {
        // Options will go here
        groupAll : true, // Group all items
        // Enable keyboard navigation
        keyboard:{
            Escape: "close",
            Delete: "close",
            Backspace: "close",
            PageUp: "next",
            PageDown: "prev",
            ArrowUp: "next",
            ArrowDown: "prev",
            ArrowRight: "next",
            ArrowLeft: "prev",
          },
        hideScrollbar:true, //If browser scrollbar should be hidden
});
```

Is there something I should add to make it works?

Thank you

**Comment by fancyapps** [comment]
Hi,

You see, v4 is designed completely differently.

> which buttons to show

See https://fancyapps.com/docs/ui/fancybox/plugins/toolbar

> transition effect

Transition effects will be reintroduced in the future releases.

> disabling right click to protect your image

It is very simple, see this demo - https://fancyapps.com/playground/22G

> transition duration

Animations are based on momentum, and you can control the friction that will affect the duration of the animation (see https://fancyapps.com/docs/ui/carousel/options#friction)

> hide scrollbar on my site and it doesn't work

It is very interesting CSS quirk. In your page, you have this CSS rule that prevents hiding vertical scrollbar:

```CSS
html, body {
    overflow-x: hidden;
}
```
remove it or add this CSS snippet:

```CSS
html.with-fancybox {
    overflow: hidden;
}
```
