### ISSUE TITLE
Module import broken - reassigning const

### ISSUE THREAD

**Issue by Eldzej** [fancyapps/ui#244]
Ran into this problem in versions from 4.0.23 up (4.0.22 is fine).

When using ES6 import, I get the following error

```
node_modules/@fancyapps/ui/dist/fancybox.esm.js:2:73053: error: Cannot assign to "s" because it is a constant
    2 │ ...s.focus()}option(t,...e){const i=this.getSlide(),s=i?i[t]:void 0;return void 0!==s?("function"==typeof s&&(s=s.call(this,this,...e)),s):super.option(t,...e)}bindHandlers(){for(const t of["onMousedown","onKeydown","... 
```

Issue seems to be in the `s=s.call(this,this,...e)),s)`

**Comment by fancyapps** [comment]
Hi,

Could you, please, create a demo where this issue could be inspected? I can not find a way to trigger such issue, it works fine, demo - https://jsfiddle.net/uwmdf2na/

**Comment by fancyapps** [comment]
I think this issue has been fixed. If you believe that this or similar issue still exists, then, please, post a comment with a link to a working demo (use any code playground).
