### ISSUE TITLE
Inside Iframe Fancyapps

### ISSUE THREAD

**Issue by yhybulca** [fancyapps/ui#249]
I want the fancyapps that I put inside the iframe to open from outside the iframe. Is it possible? (fancyapps 4)

**Comment by fancyapps** [comment]
Hi,

If you want to start Fancybox from within iframed page, 1) include Fancybox in the parent page; 2) add click event to your elements and use API to start Fancybox with `window.parent` prefix, like `window.parent.Fancybox.open()`.
