### ISSUE TITLE
modelviewer.dev support

### ISSUE THREAD

**Issue by wisniowski** [fancyapps/ui#250]
I am working to use your plugin to display the interactive 3d mode with https://modelviewer.dev/ but I face two issues:

1. Is there an option to force the particular class on the selected thumb? Just like "has-video" and "has-image" is natively added?
2. The active section with the 3d model should have the disabled Fancybox swiping (so user can swipe the actual model) - is it something that can be done?

Thanks, in advance!

**Comment by gbcatrinoiu** [comment]
@wisniowski did you manage to implement 3d model in the fancybox?

**Comment by fancyapps** [comment]
@gbcatrinoiu Hi, Here is a sample code - https://jsfiddle.net/hj3dts5e/
