### ISSUE TITLE
Option to disable carousel swipe

### ISSUE THREAD

**Issue by knstyle** [fancyapps/ui#253]
Can we add an option to disable carousel swiping between slides? I think it's definitely useful in some situations to have more control or options over the carousel.

**Comment by fancyapps** [comment]
Hi,

You see, Carousel is build around Panzoom and you can use `Panzoom` option to pass options for Panzoom instance, like this:

```js
const myCarousel = new Carousel(document.querySelector(".carousel"), {
  Panzoom : {
    touch: false
  }
});
```

https://fancyapps.com/playground/2aH
