### ISSUE TITLE
HTML Error - Bad value button for attribute role on element li.

### ISSUE THREAD

**Issue by vnfrr** [fancyapps/ui#259]
Hi, 

the carousel__dots return HTML errors because role="button" is not allowed on `<li>` tags.
Valid HTML is a criteria for accessibility.

Is it possible for you to create inner buttons or make the markup customizable like the navigation buttons?
`<li class="carousel__dot is-selected" data-page="0" role="button" tabindex="0" title="Zur #1 Folie gehen"></li> `

**Comment by fancyapps** [comment]
Hi,

Why do you think that this is an issue? That attribute actually was added to improve accessibility.

**Comment by vnfrr** [comment]
Because an li may not have role=button, see https://www.w3.org/TR/html-aria/#el-li.
I know its not (for now) a WCAG error but I don't quite follow why you wouldn't be able to put a real button inside the li. 

Furthermore (I´m not quite sure) but if you use li[role=button] in IE, JAWS will not count it as a list item anymore, or have you tested it?

**Comment by fancyapps** [comment]
I myself have observed people with various disabilities using computers and software. I will add buttons for the sake of semantics.

**Comment by fancyapps** [comment]
Hi,

v5 has been released recently and button elements are used not only for carousel dot navigation, but also for thumbnails.
