### ISSUE TITLE
After closing via button or swipe-up gives duplicate url history

### ISSUE THREAD

**Issue by PimHaarsma** [fancyapps/ui#264]
Hello! Thanks for the great plugin!

I found a small annoying bug. To reproduce:

- Go to https://fancyapps.com/docs/ui/fancybox/
- Click on one of the photos
- Close the fancybox via the close button at the top right or via swipe-up
- Press back/previous-page button in browser
- The url (and page) remains the same
- Press back again: Only then will the browser return to the actual previous page.

**Comment by ChiaYuSu** [comment]
I have the same question too.

**Comment by ChiaYuSu** [comment]
Hi, @PimHaarsma. I fixed the problem.

You can add this script `$.fancybox.defaults.hash=false` in the javascript.

It works as I tried in the console to set the `hash` to `false`.

**Comment by PimHaarsma** [comment]
Hello @ChiaYuSu. Thanks for the workaround!
I like the hash-plugin, but I will use this fix, until the problem is fixed.

**Comment by snitchyuk** [comment]
I'm not an coder so please ignore me if this is a stupid suggestion - but as pressing the browsers back button results in closing the gallery, could the close button in the gallery simply be changed to something like "history.back()"? Wouldn't this result in the gallery closing, and then the back button working as expected?

**Comment by fancyapps** [comment]
@snitchyuk Unfortunately, you can not know what exactly happens. You can just observe URL hash changes, watch for `onpopstate` events and something like that. And there can be various scenarios. For example, user might change URL hash value manually. Then, if the code contains `history.back()`, then browser would navigate unexpectedly.

**Comment by 9mm** [comment]
I definitely agree this is painful. @fancyapps at the very least, perhaps you can offer an option to use history replace instead of history push, so at the very least when they open an image, and close on the image, and then hit back, it doesnt cause them to click a bunch of times. But then, at the very least, it would still work if someone wants to deep-link a URL to an image, thats the main purpose of me using it is so when someone copies the URL and another person clicks, it automatically opens the image. I actually dont like the history aspect because theres tons of images and it makes navigating back painful

**Comment by lubomirblazekcz** [comment]
```js
window.addEventListener('popstate', () => {
    window._fancyboxClosedWithPopstate = true
})

Fancybox.bind('[data-fancybox]', {
    on: {
        ready: () => {
            window._fancyboxClosedWithPopstate = false
        },
        shouldClose: (_, e) => {
            if (!window._fancyboxClosedWithPopstate) {
                e.preventDefault()
                window.history.back()
            }
        }
    }
})
```

This is my solution, every closing event with fancybox does `window.history.back()` so the browser navigation works as expected. It's a bit hacky because shouldClose doesn't return which action triggered close event.

**Comment by fancyapps** [comment]
Hello to all!

The Hash plugin has been redesigned in the latest release. It works a little better, but unfortunately still not perfect. Sorry, but I don't think it's technically possible to get this to work reliably in any situation. Therefore, in future releases, the Hash plugin will not be included in the core code, but will be provided as an option.

**Comment by fancyapps** [comment]
Well, since there don't seem to be any new reports of issues with this, I assume it's working fine now.
