### ISSUE TITLE
Customization: Backdrop opacity

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/ui#268]
Edit: deleted content.

I've found the correct way to change the backdrop is to set `--fancybox-bg` with the desired color and opacity value in RGBA format.

**Comment by mjcampagna** [comment]
A

**Comment by fancyapps** [comment]
Hi,

Background opacity is set using background color for the overlay element.
And you can easily customize it using CSS variable.

otrd., 2022. g. 29. marts, plkst. 22:20 — lietotājs Matthew Campagna (<
***@***.***>) rakstīja:
