### ISSUE TITLE
Dynamic elements not working

### ISSUE THREAD

**Issue by evgenyshev** [fancyapps/ui#269]
I am opening a page via Fancybox Ajax. My link looks like this:

`<a data-fancybox data-type="ajax" data-src="page.php" data-filter="#content_b">Open page</a>`

There are various dynamic elements on the page (image carousel, ajax comment form, ajax "like" link), none of them work properly. For example, if the page.php is opened via Fancybox, then the "I like" ajax link on it simply reloads the page, although it should produce an event similar to social networks.

Is there any possibility to run third party scripts (dynamic content) inside Fancybox ajax?

**Comment by fancyapps** [comment]
Hi,

> Is there any possibility to run third party scripts (dynamic content) inside Fancybox ajax?

1) Fancybox provides callbacks that allow you to run your code after, for example, content is loaded - https://fancyapps.com/docs/ui/fancybox/events
2) "event delegation" is a simpler/better approach to handle click events for elements that exists now or in the future
