### ISSUE TITLE
Optimize css rules

### ISSUE THREAD

**Issue by duannx** [fancyapps/ui#271]
Currently, style for `.carousel__dot` is nested inside `.carousel__dots`. It is unnecessary and makes things a bit verbose when someone wants to overwrite the style of the dot. My suggestion is to remove the parent selector from the style:
From:
```css
.carousel__dots .carousel__dot {
    ...
}
```
To:
```css
.carousel__dot {
    ...
}
```
By the way, the CSS variable for styling the `.carousel__dot` is nice to have. I can make a pull request for this.

**Comment by fancyapps** [comment]
Hi,

As of v5, the class name is `f-carousel__dot` and some CSS variables are available, such as `--f-carousel-dot-width`.
