### ISSUE TITLE
:focus-visible vs. :focus

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/ui#275]
Per the information on [this page](https://stackoverflow.com/a/45191208), I would love to see instances of `:focus` replaced with `:focus-visible` in the Fancybox stylesheet.

This should probably allow you to also remove logic and styling relating to `.is-using-mouse`.

**Comment by fancyapps** [comment]
Hi,

I think this was one of the first things I implemented when I started working on v5 :) I really wanted to include :focus-visible in v4, but browser support was not great at that time.

**Comment by fancyapps** [comment]
Hi,

The freshly released v5 uses `:focus-visible`.
