### ISSUE TITLE
How to render React Component inside fancybox?

### ISSUE THREAD

**Issue by sonupandit** [fancyapps/ui#287]
Hi,
I am new to React. I want to render React component. below is the code which I was trying to do.

```
import React from 'react';
import Fancybox from '../components/fancybox';
import Contact from '../components/Contact';

export default function FundFile() {
  return (
    <>   
    <Fancybox><button data-src="#cpop" data-type="inline" data-fancybox>Contact</button></Fancybox>
    <div id="cpop" style={{display:"none"}}>
      <Contact />
    </div>
    </>
  )
}
```

**Comment by mjcampagna** [comment]
Did you see the documentation about using in React?

https://fancyapps.com/docs/ui/fancybox/react

**Comment by sonupandit** [comment]
> Did you see the documentation about using in React?
> 
> https://fancyapps.com/docs/ui/fancybox/react

@mjcampagna Yes, I have seen the doc but there is no example for inline content.

**Comment by fancyapps** [comment]
You just have to follow the demo and put everything inside `<Fancybox>` tags. 
I have added the sample - https://codesandbox.io/s/fancybox-react-demo-9k2kz?file=/src/App.js
