### ISSUE TITLE
If viewport zoomed, fancybox images are incorrect size

### ISSUE THREAD

**Issue by 51graphix** [fancyapps/ui#289]
If the mobile viewport is zoomed in prior to clicking an image that opens in Fancybox, the image opens at incorrect size, and all images in the gallery are also wrong size. Is there a way to reset the zoom level of viewport during initialization? Same result on Chrome, Safari, Firefox in IOS 15.4.1 on iphone.

**Zoomed in:**
![fancybox4_zoomed](https://user-images.githubusercontent.com/12513230/167724092-ad6ee976-f7a5-40ad-b68f-deb73a0a0baf.jpg)

**No zoom:**
![fancybox4_nozoom](https://user-images.githubusercontent.com/12513230/167724060-938751b4-8fc0-4d66-8201-7a30c6600147.jpg)

**Comment by fancyapps** [comment]
Hi, Please upgrade to the latest version (currently v5.0.17) where the image sizes should be correct regardless of the pinch zoom level of the device.
