### ISSUE TITLE
Guys, why didn't it work?

### ISSUE THREAD

**Issue by yoowo222** [fancyapps/ui#294]
![image](https://user-images.githubusercontent.com/59963234/169066896-e03335ae-f3ea-4e94-8189-f5608bf71af0.png)
Why can't this option use 0 or 1, only true and false?

**Comment by fancyapps** [comment]
Hi,

Well, I could tweak code to make it work with 1/0 values, but you know, JavaScript world is moving towards stricter types (https://devblogs.microsoft.com/typescript/a-proposal-for-type-syntax-in-javascript/) and you should start getting used to strict data types 😄 BTW, next major version will be written in TypeScript.
