### ISSUE TITLE
Use src and srcset instead data-src data-srcset

### ISSUE THREAD

**Issue by NIIISH** [fancyapps/ui#297]
Is there any way to use src and srcset instead data-src data-srcset? I use nextjs with image component that use only src/srcset

**Comment by fancyapps** [comment]
Hi,

Which component do you think of?

**Comment by NIIISH** [comment]
Hi, about fancybox component, something like this:
```js
               <Fancybox>
                  <Image
                    data-fancybox="fancybox-1"
                    src={url}
                    alt={alternativeText}
                    layout='fill'
                    objectFit="cover"
                    sizes="600px"
                    placeholder="blur"
                    blurDataURL={blur.url}
                    data-sizes="100vw"
                    />
                </Fancybox>
```
for now fancybox uses only 600px image or if sizes="800px" it will use 800px image although the img tag has src and srcset

**Comment by fancyapps** [comment]
I think it would be best for you to use `Images.content` option to create custom `<picture>` element, see sample here - https://fancyapps.com/fancybox/plugins/images/#picture
