### ISSUE TITLE
Two instances on one page

### ISSUE THREAD

**Issue by eukraina** [fancyapps/ui#300]
Can I have two or more instances on one page with different css layout?
I have the main "page body" where I always have images with data-fancybox="gallery" code. And I have comments that can contain images with their unique data-fancybox="fancy-comments2676" code.
How can I bind different fancyboxes with different options, and different css?
Why when I do like
Fancybox.bind('[data-fancybox]', 
and specify Toolbar buttons here I dont see thumbs (as well as I dont have a carousel) in comments, but I see them in the first instance of the main body?

**Comment by fancyapps** [comment]
Hi,

Simply choose another selector for `Fancybox.bind(YOUR_SELECTOR);`. You can also use `mainClass` option to set different CSS class name for the main wrapping element, and you can use that to apply custom CSS.

**Comment by eukraina** [comment]
Fancybox.bind('[data-fancybox="gallery"]',  for a main gallery with its own layout and css (+ mainClass: 'main-gallery',)
And all other are by dafault, looks its OK working! Thanks!
