### ISSUE TITLE
Offset calculation error in carousel

### ISSUE THREAD

**Issue by alekseydrv** [fancyapps/ui#302]
Hello,

I have a carousel and width of .carousel__slide is like that: calc((100% - 60px) / 4); 
60px is for 'margin-right' between slides;

If I scroll to the right round about 40-50 slides, I see a part of fifth slide. 

Screenshot: https://paste.pics/H530C

And the distance between last and first slide is bigger than the rest: https://paste.pics/H544E

Example: https://codepen.io/alekseydrv/pen/LYQmvVm

**Comment by fancyapps** [comment]
Hi,

Please, upgrade to v5, it should work as expected.
