### ISSUE TITLE
slide # out of total added to captions?

### ISSUE THREAD

**Issue by morrow95** [fancyapps/ui#31]
Was doing this in the old jquery version which allowed me to add a '# of #' to the caption to show the current out of total for the viewing gallery.  Is there a similar method in this version?

```
    caption : function( instance, item ) {
        var caption = $(this).data('caption') || '';
	
        return ( caption.length ? caption + '<br>' : '' ) + '<span class="fancybox-number"><span data-fancybox-index></span> of <span data-fancybox-count></span></span>';
    },
```

**Comment by fancyapps** [comment]
Hi,

While it is possible to customize caption using callbacks, I forgot to include a simpler way. Sorry about that. Similar option will be available in the next commit.

**Comment by morrow95** [comment]
Thanks, callbacks is what I ended up using just thought there might have been something similar to before.

**Comment by fancyapps** [comment]
FYI, The first beta was released yesterday and offers a `caption` option to make it easier to customize captions, example:

```JS
Fancybox.bind('[data-fancybox="gallery"]', {
  caption: function (fancybox, carousel, slide) {
      return `${slide.index + 1} / ${carousel.slides.length} <br />` + slide.caption;
    },
});
```

Demo - https://gist.lipsum.app/gists/w9
