### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by littlegolden** [fancyapps/ui#311]
I'm using FancyBox in Vue.

I have set `touch-action: none;` to * dom element, but still got this error.

![image](https://user-images.githubusercontent.com/35162802/174481555-52709bda-368c-435d-add5-1b1fd41687a0.png)

**Comment by littlegolden** [comment]
Im curious thet how does your [example](https://fancyapps.com/playground/Fz) fix this? I noticed that your example used `touch-action: none;` css, but that is not work for me. do you have any suggestions?

**Comment by fancyapps** [comment]
I have no idea what you want to achieve. Any demo would help.

**Comment by littlegolden** [comment]
found the culprit: npm package [default-passive-events](https://www.npmjs.com/package/default-passive-events)

**Comment by fancyapps** [comment]
You can safely ignore that. FYI, Fancybox5 is just around the corner, it's a complete rewrite and it's not just a migration to TS, it works much better and covers almost all feature requests.

**Comment by littlegolden** [comment]
> You can safely ignore that. FYI, Fancybox5 is just around the corner, it's a complete rewrite and it's not just a migration to TS, it works much better and covers almost all feature requests.

can't wait!
