### ISSUE TITLE
Lazy-load thumbnails not appearing in slideshow

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/ui#313]
I've got an image gallery for which thumbnails are lazy-loaded as the page scrolls. I'm finding that if the thumbnails have not yet loaded into the page, then those thumbnails are missing in the slideshow view. For example, when clicking the first image and then advancing the slideshow to images below the page fold ...

For context, I'm using data-srcset with responsive images (I don't know whether this matters  for triggering this issue).

Is there a known way to handle this?

**Comment by mjcampagna** [comment]
I'm also using a base64 placeholder in my img src prior to the image being lazy-loaded.

**Comment by mjcampagna** [comment]
Okay, I've found that I can work around this issue by setting the `data-thumb` attribute.

**Comment by fancyapps** [comment]
Hi,

I think it should work as expected in v5.
