### ISSUE TITLE
Fancybox inside modal bootstrap, l can't change with keyboard because focus stay in back modal -

### ISSUE THREAD

**Issue by saturnov** [fancyapps/ui#323]

**Comment by fancyapps** [comment]
Any demo?

**Comment by saturnov** [comment]
![imagen](https://user-images.githubusercontent.com/108355105/181312218-ffb288ac-5436-4d4f-a34b-66eab3cd7b5d.png)

**Comment by saturnov** [comment]
l try to put inside modal of bootstrap and then call modal 
` $('#staticBackdrop').modal('show');
            Fancybox.bind('[data-fancybox="gallery1"]', {
                infinite: false,
                autoFocus: true,
                trapFocus : true,
                placeFocusBack  : true,
                Thumbs: false,
                Carousel: {
                    Dots: true,
                    on: {
                        change: (that) => {
                            myCarousel.slideTo(that.page, { friction: 0 });
                        },
                    },
                }
            });`

**Comment by fancyapps** [comment]
Any live demo?

**Comment by saturnov** [comment]
https://jsfiddle.net/0dev_babilonia0/Lfq3brmj/4/

**Comment by fancyapps** [comment]
But why do you use Bootstrap modal in the first place? Fancybox supports multiple open instances, so, you can use Fancybox to display modal with images and clicking them can open another Fancybox. Example - https://jsfiddle.net/c0td5461/
