### ISSUE TITLE
TypeError: Cannot call a class constructor without |new|

### ISSUE THREAD

**Issue by hassanmah** [fancyapps/ui#324]
I keep getting these console errors when using Fancybox (v4.0.30)

<img width="923" alt="image" src="https://user-images.githubusercontent.com/3025707/181304526-0ce44045-edb6-417f-98fa-4d33bf86fcfe.png">

It stops other JS code from running, this is my code:

`import { Fancybox } from "@fancyapps/ui";
function init() {
  window.Fancybox = Fancybox;
}`

Any pointers?

**Comment by fancyapps** [comment]
Hi,

Sorry, I have no idea what is jquery doing there.

**Comment by fhnb16** [comment]
Same issue with Vue3
