### ISSUE TITLE
please enhance caption to v3 level 

### ISSUE THREAD

**Issue by hanscees** [fancyapps/ui#328]
Hi,

I have nice pages here, where version three alas has a nasty bug (won't load beyond fourth image when swiping.)
https://www.bomengids.nl/2022/species/Tulpenboom__Liriodendron_tulipifera__Tulip_tree__Amerikanischer_Tulpenbaum__Tulipier_de_Virginie.html

Fancybox four has no such bug, but alas only has 

`caption= "some text" `

and not the much more elaborate
` <lightbox_caption> `

lots of html here

` </lightbox_caption>`

Just to let you know the version three option is much easier to work with. Any workaround would be nice, or better enhancement.

**Comment by fancyapps** [comment]
Hi,

Sorry, but I do not understand your comment about captions. In my opinion, it is very simple to use it, example:

```
Fancybox.bind('[data-fancybox="gallery"]', {
  caption: function (fancybox, carousel, slide) {
    return (
      `${slide.index + 1} / ${carousel.slides.length} <br />` + slide.caption
    );
  },
});
```

https://fancyapps.com/playground/GQ

**Comment by hanscees** [comment]
> Hi,
> 
> Sorry, but I do not understand your comment about captions. In my opinion, it is very simple to use it, example:
> 
> ```
> Fancybox.bind('[data-fancybox="gallery"]', {
>   caption: function (fancybox, carousel, slide) {
>     return (
>       `${slide.index + 1} / ${carousel.slides.length} <br />` + slide.caption
>     );
>   },
> });
> ```
> 
> https://fancyapps.com/playground/GQ

The problem I have is that I want a complex html structure as caption. In this version I cannot add this easily to a slide because the only option to fill slide.caption via html is by doing caption="Xxx".

I have for instance in the caption four languages all in different div structures. A page button determines what language you see, and what languages are hidden. And also I have a url in the caption. 
In version three you could load any html into slide.caption by wrapping it inside a html structure like <figurecaption>  lots of html  </figurecaption>

**Comment by fancyapps** [comment]
Well, it could be as simple as this - 

```js
Fancybox.bind('[data-fancybox="gallery"]', {
  caption: function (fancybox, carousel, slide) {
    const figurecaption = slide.$trigger.querySelector("figurecaption");

    return figurecaption ? figurecaption.innerHTML : slide.caption;
  },
});
```

https://fancyapps.com/playground/3n9

**Comment by hanscees** [comment]
that is fantastic, works like a dream:
https://www.bomengids.nl/2022/2022bugtest/fs4.html

thanx a million!

**Comment by gyurmey2** [comment]
> Well, it could be as simple as this -
> 
> ```js
> Fancybox.bind('[data-fancybox="gallery"]', {
>   caption: function (fancybox, carousel, slide) {
>     const figurecaption = slide.$trigger.querySelector("figurecaption");
> 
>     return figurecaption ? figurecaption.innerHTML : slide.caption;
>   },
> });
> ```
> 
> https://fancyapps.com/playground/3n9

Hi, does this also work in v5?

**Comment by fancyapps** [comment]
@gyurmey2 Yes, but it will be like this:

```js
Fancybox.bind('[data-fancybox="gallery"]', {
  caption: function (fancybox, slide) {
    const figurecaption = slide.triggerEl?.querySelector(
      "figurecaption"
    );

    return figurecaption ? figurecaption.innerHTML : slide.caption || "";
  },
});
```

https://jsfiddle.net/tzfjmy0k/

**Comment by fancyapps** [comment]
I've also created a new section in the documentation - https://fancyapps.com/fancybox/captions/

**Comment by gyurmey2** [comment]
@fancyapps, thanks a lot!

Unfortunately, WordPress generates the code below. Is there any way to do this?

```
<figure>
  <a href="full-size-image.jpg">
    <img src="thumb-image.jpg">
  </a>
  <figcaption>Example caption</figcaption>
</figure>
```

**Comment by fancyapps** [comment]
Simply replace selector here -

```slide.triggerEl?.querySelector("figurecaption")```

with the one that works for you, like `"figurecaption"`.

**Comment by gyurmey2** [comment]
Unfortunately it doesn't work. Could the reason be that `figcaption` is not nested in `a`?

```
Fancybox.bind('figure a', {

   caption: function (fancybox, slide) {
   const figurecaption = slide.triggerEl?.querySelector('figcaption');
   return figurecaption ? figurecaption.innerHTML : slide.caption || '';

   },
}
```

**Comment by fancyapps** [comment]
I somehow hoped that you will figure it out that you simply need to add
parentElement.

**Comment by gyurmey2** [comment]
I can't handle it, but thank you for your help.

**Comment by fancyapps** [comment]
Here is a working example with your HTML structure:

```js
Fancybox.bind('figure a', {
  groupAll: true,
  caption: function (_fancybox, slide) {
    const figcaption = slide.triggerEl?.parentElement.querySelector(
      "figcaption"
    );

    return figcaption ? figcaption.innerHTML : slide.caption || "";
  },
});
```

https://jsfiddle.net/vgeb1Lwj/

**Comment by gyurmey2** [comment]
You are very helpful. Thank you very much!

**Comment by gyurmey2** [comment]
@fancyapps, sorry to bother you, but is it possible to get the attribute caption from an image? I try with below code snippet but it doesn't work.

```
caption: function (fancybox, slide) {
   const atrr = slide.triggerEl?.querySelector('img').getAttribute('title');
   return atrr ? atrr.innerHTML : slide.caption || '';
}, 
```

**Comment by fancyapps** [comment]
Title attribute is a string, not HTML element :)

```js
caption: function (_fancybox, slide) {
  const title = slide.triggerEl?.querySelector('img').getAttribute('title');
  return title || slide.caption || '';
},
```
https://jsfiddle.net/qu6f8roy/

**Comment by gyurmey2** [comment]
@fancyapps, thank you again!
