### ISSUE TITLE
I can't show the hash in the URL without the data-fancybox attribute

### ISSUE THREAD

**Issue by Hubaxis7** [fancyapps/ui#331]
I'm using wordpress and can't add the **data-fancybox** attribute to links, so I use **class="fancybox-image"** with them. But I haven't found a way to show the hash in the URL when opening the gallery.
`Fancybox.bind('.fancybox-image', {
    groupAll: true,
  });`
Help me to do this.

**Comment by fancyapps** [comment]
Hi,

Sorry, but, if you are not able to use data attributes, you are then out of luck. Maybe you can add them using JS. You could also set `data-slug` attribute to set custom hash value - https://fancyapps.com/fancybox/plugins/hash/#customization
