### ISSUE TITLE
Case sensitive problem with Html.scss file

### ISSUE THREAD

**Issue by thebrokenbrain** [fancyapps/ui#34]
Hi, 

Shouldn't **ui/src/Fancybox/plugins/Html/html.scss** filename be in uppercase?

In **fancyapps/ui/blob/main/src/Fancybox/Fancybox.scss** the import is "Html.scss":
```
@import "plugins/Image/Image.scss";
@import "plugins/Html/Html.scss";
@import "plugins/Thumbs/Thumbs.scss";
```
Windows is not case sensitive, but when compiling in Linux occurs an error because the file plugins/Html/Html.scss doesn't exist.

Thanks!

**Comment by fancyapps** [comment]
Hi,

Thanks for reporting, this will be fixed in the next commit.

**Comment by fancyapps** [comment]
Sorry about that, the first beta was released today and it should be fine now.
