### ISSUE TITLE
Uncaught Error: No root element provided at new y (fancybox.esm.js:2:1)

### ISSUE THREAD

**Issue by danielLee0721** [fancyapps/ui#352]
I am currently using the Combine (CAROUSEL / FANCYBOX) example shown on the showcase page and I get the following error message on pages that aren't using the carousel / fancybox.

fancybox.esm.js:2 Uncaught Error: No root element provided
    at new y (fancybox.esm.js:2:1)

Any ideas? Thank you.

**Comment by ImTosS** [comment]
I had the same issue and it seems that this case is present when there's no DOM elements with the carousel class. What I did to solve this is to add a validation just before invoking:

```
if(document.querySelector(".lightbox-carousel")){
        // Initialise Carousel
        const mainCarousel = new Carousel(document.querySelector(".lightbox-carousel"), {
            infinite: false,
            Navigation: false,
        });

        // Initialise Fancybox
        Fancybox.bind('[data-fancybox="gallery"]', {
            Carousel: {
                on: {
                    change: (carousel, to) => {
                        // Sync Carousel slide
                        // ===
                        const $el = Fancybox.getInstance()
                            .getSlide()
                            .$trigger.closest(".carousel__slide");

                        const slide = mainCarousel.slides.find((slide) => {
                            return slide.$el === $el;
                        });

                        mainCarousel.slideTo(slide.index, {
                            friction: 0,
                        });
                    },
                },
            },
        });
    }
```
Hope it helps!

**Comment by danielLee0721** [comment]
Thank you! Much appreciated

**Comment by fancyapps** [comment]
Hi,

Carousel constructor expects HTMLElement that exists in the DOM. If it does not exists, then the script warns you that you trying to build Carousel on non-existing element.
