### ISSUE TITLE
what is the correct way to call the close method using Programmatic ?

### ISSUE THREAD

**Issue by jarwonozt** [fancyapps/ui#356]
Hello Fancybox Developers..
I'm using the latest fancybox, I want to call a close method. I tried various ways but didn't find perfect results. When I use `Fancybox.close();` managed to close the dialog but there are still HTML elements floating around. Is the way I did wrong or is this still under construction?
Hopefully answered, thank you.

**Comment by jarwonozt** [comment]
![closeFancyBoxError](https://user-images.githubusercontent.com/67833034/193621098-38b5d2e5-6724-4e8f-af9c-4e22131759a8.png)

this is the result when close fancybox using Programmatic, there is a fancybox element floating on the screen and it doesn't close

@fancyapps

**Comment by fancyapps** [comment]
`Fancybox.close();` is the correct way to close all instances.

**Comment by jarwonozt** [comment]
> `Fancybox.close();` is the correct way to close all instances.

okey thanks, maybe this is because I use laravel livewire, so the javascript code affects the perfection of the code from Fancybox.
