### ISSUE TITLE
Form element events not work inside fancybox dialog (React)

### ISSUE THREAD

**Issue by Mijeko** [fancyapps/ui#361]
Hi, i have form with one input, but events onChange, onKeyDown and etc not work inside modal dialog created from fanybox.
Sorry big image
![изображение](https://user-images.githubusercontent.com/12849469/195140527-ee649004-f60f-425e-8bf5-c37e76e58de9.png)

And result - empty console
![изображение](https://user-images.githubusercontent.com/12849469/195140991-425278a6-6c3a-4e41-b31e-2bea03ed3465.png)

**Comment by hugomendonca98** [comment]
> Hi, i have form with one input, but events onChange, onKeyDown and etc not work inside modal dialog created from fanybox.
> Sorry big image

Same issue here, did I get it resolved?

**Comment by fancyapps** [comment]
Hi,

I am closing this issue report because this project has been completely rewritten, please upgrade to v5 and report if the problem still exists
