### ISSUE TITLE
How to set a minimum width / height for an image slide?

### ISSUE THREAD

**Issue by hedgehog90** [fancyapps/ui#375]
I'm using Fancybox to present some small animated gifs.
A high quality animated gif may be very small dimensionally, but they look good when scaled up.
My gifs however are presented in their original size and take up very little of the available area.
How do I tell fancybox to scale the images to fit the available area, or better yet, to set a minimum image width/height?

I've tried the following to make them fit the slide area:

```
fb.on("reveal", ()=>{
    var slide = fb.getSlide();
    slide.$content.style.width = "100%";
    slide.$content.style.height = "100%";
    slide.$image.style.width = "100%";
    slide.$image.style.height = "100%";
});
```

It works but it leads to some glitchy looking effects when changing slides. I presume there's a better way?

**Comment by fancyapps** [comment]
Hi,

Try adding `data-width` and `data-height` attributes to your links. Also, this would work too:

```css
.fancybox__image {
    min-width: 100px;
    min-height: 100px;
}
```
