### ISSUE TITLE
Prevent click on Toolbar

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/ui#385]
Trying to do this:

```js
	on: {
		init: (fancybox) => {
			fancybox.plugins.Toolbar.$container.addEventListener('click', (e) => {
				e.stopPropagation()
			})
		},
```

... but `fancybox.plugins.Toolbar.$container` is apparently null when this runs. I've also tried in `initLayout`, as well as:

```js
	on: {
		"Toolbar.onInit": (fancybox) => {
```

... but nothing seems to work. Is there a way to do this?

**Comment by fancyapps** [comment]
Hi,

In v4, events are firing in this order: `init` (here you can, for example, do something with the content) -> `prepare` (here plugins like Toolbar are activated) -> `ready` (right before main container element is revealed).

So, you could try using `ready` event to access the Toolbar.

**Comment by mjcampagna** [comment]
That worked! Thanks!
