### ISSUE TITLE
Carousel doesn't clear its styles on destroy

### ISSUE THREAD

**Issue by pleomax13** [fancyapps/ui#387]
At the carousel, after calling the `destroy()` method, the `carousel _ track` block has inline styles. Workaround: clear styles manually before destroying using `slider.$track.style = ''`. Are there any other workarounds? 

Why do I need this: on a small screen resolution, I use a carousel, on the rest, the blocks line up with a grid.

Playground: https://fancyapps.com/playground/4hU

Reproduction steps: press the "destroy" button in the playground and look at the carousel styles through DevTools.

Can you please make changes to the carousel  source code? I will be very grateful.

**Comment by fancyapps** [comment]
Hi, Please, upgrade to v5.
