### ISSUE TITLE
rebuild fancyapp !

### ISSUE THREAD

**Issue by jehadja** [fancyapps/ui#39]
Hi, thanks for this great improvement to remove JQuery and make it JS vanilla plus add an amazing Carousel and zoom 
(Huge Thanks)

I have a small problem, I have a Carousel Gallary which includes many photos 10-12 but these photos are filtered into several tags eg: sport, education, kitchen, etc...
under the Carousel I have tags on each tag click I want to rebuild the Carousel according to the selected tag

but the method destroy is not working correctly, also init() the same  
```
    let myCarousel = new Carousel(document.querySelector("#myCarousel"), {
        slidesPerPage: 1,
        preload: 2,
        Dots: false

    });
const filterGallary = Fancybox.bind('[data-fancybox="gallery"]', {
    closeButton: "top",
    dragToClose: false,
    Thumbs: false,
    Carousel: {
        Dots: false,
    },
});
```

I tried several solutions mostly doesn't work, the final solution I made is to remove slides and add new slides 
the problem with this solution is that  Carousel is not considered these changes and I still have white places instead of old slides, the same also to redraw the slide itself eg 👍  
 ```

    document.querySelector("#myCarousel .carousel__track").innerHTML = ""
let templates = ''
    needed.forEach((item, i) => {
        let template = `  <div
          class="carousel__slide"
          data-src="/storage/${item.src}"
          data-fancybox="gallery"
          data-caption="${item.name}"

        >
          <img
          width="600"
          height="420"
              src="/storage/Thumbs/fit/850/600/${item.src}"
             alt="${item.name}"
          />
        </div>`
        templates += template
    });
    document.querySelector("#myCarousel .carousel__track").innerHTML = templates
    myCarousel.destroy();

    let myCarousel = new Carousel(document.querySelector("#myCarousel"), {
        slidesPerPage: 1,
        preload: 2,
        Dots: false,
    });

 
```

thanks for helping in advance!

**Comment by fancyapps** [comment]
Hi,

Sorry for the late reply, a new version will be released this week and will include an easier way to rebuild carousel. I will then provide a full demo for filtering the content.

**Comment by fancyapps** [comment]
Hi,

The first beta was released today, and here in a working demo - https://fancyapps.com/playground/vv

**Comment by jehadja** [comment]
@fancyapps Thanks very much for the answer, updates, and example it made my day!
have a good day
