### ISSUE TITLE
how to remove all animations including sliding?

### ISSUE THREAD

**Issue by AucT** [fancyapps/ui#390]
This slides gvie me headache. How to make it like in v3?

I want zero animations. Just picture replacing like in v3

**Comment by fancyapps** [comment]
Hi,

You could set friction to `0` for Carousel, like this:

```js
  Carousel : {
    friction: 0,
  }
```

Sorry about that, the upcoming v5 will work totally different and the default animation will be "fade".

Janis

**Comment by AucT** [comment]
perfect. thx.

**Comment by AucT** [comment]
I'm going to use fancybox3. I need jquery only for it, but it worth it.
I want to note that fancybox 3 is AWESOME! Best lightbox in galaxy.

If you will make new version, please take awesome things v3 version has:
1) awesome defaults. It has very small animation when you tocuh scroll, and nice small animation when you first time open image. But has human friendly no slide animation on desktop. It's perfect.
2) Also it has not glitches. v4 version when you open and close it remove scrollbar and that creates glitches (layout shift). Besides, default slide animation on desktop in v4 is super annoying.

I'm not forcing or something, just friendly tips.
Thanks for fancybox v3. It's just rocks!

**Comment by fancyapps** [comment]
@AucT Would you be willing to take a look at v5 and give some feedback? It's 99% done, I'm currently working on the final touches and documentation.

About glitches - I am surprised that v3 works better for you, because it also hides scrollbar by default and that can cause layout shift. I am going to write a dedicated article about what, why it happens and what the possible solutions are.

**Comment by AucT** [comment]
Yeah, I'd like to.

**Comment by AucT** [comment]
Just tested again.
v3 is perfectly soft animation and soft animation on hide/unhide scrollbar
v4 is very harsh / hard animation. Very fast and have some animation glitches on opening and closing. Not sure how to describe, but if v3 is speed constant 100, then speed of v4 is 500-300-500. Which make laggs on poor gpu. Also when image is back from fancybox to it's image it shaking a little.
This v4 fast speed ease-out make it shaking like earthquake.

**Comment by fancyapps** [comment]
@AucT Please, join the Discord server for chat - https://discord.gg/6QYFwv6Z

Long story short, your images are probably too large/heavy.
