### ISSUE TITLE
Which event replaces the old event beforeLoad?

### ISSUE THREAD

**Issue by CodeTappert** [fancyapps/ui#392]
I did this in an older version of fancybox. Today i upgraded to the newest version (fancyapps/ui) and it seems that the beforeLoad event is no longer supported. How can i access the slide  before the content is loaded?

I am mainly asking this because i have to include videos via hls and need to create a hls instance if one of those videos is coming up.

```
beforeLoad(instance, slide) {
					if (slide.type === constants.SLIDETYPES.video) {
						self.currentGallerySlide = slide;
						return true;
					} else if (slide.type === constants.SLIDETYPES.pdf) {
						const src = slide.src;
						const imageObjID = src.substr(src.lastIndexOf("/") + 1);
						self.showDoc(imageObjID);
						instance.close();
					} else if (slide.type === constants.SLIDETYPES.misc) {
						self.initiateDownload(slide.pos);
						instance.close();
					}
				}
```

**Comment by fancyapps** [comment]
Hi,

Have you tried `Carousel.createSlide` event?

**Comment by CodeTappert** [comment]
Yes after i posted this issue i tried ```Carousel.createSlide``` to check if my slide has the "inline" and the source "#video-player".
Then i just call my HLS Method and attach a hls player to the videoplayer div.

It works fine. Thank you
