### ISSUE TITLE
No root element provided?

### ISSUE THREAD

**Issue by consigliere23** [fancyapps/ui#394]
Hi, 

I am using Fancybox with mobirise site.
Seems the issue is this script: https://cdn.ampproject.org/v0.js

Is there any solution to this?
It's like conflict issue or something else...
When remove this mobirise script it's working but need to keep it due to other functions on site.
I tried also replacing the order of loading scripts, but no luck.
Here is the error:
`fancybox.js:2 Uncaught Error: No root element provided
    at new n (fancybox.js:2:37635)
    at i.value (fancybox.js:2:91602)
    at new i (fancybox.js:2:87894)
    at Function.value (fancybox.js:2:104139)
    at HTMLBodyElement.value (fancybox.js:2:102961)
n @ fancybox.js:2
value @ fancybox.js:2
i @ fancybox.js:2
value @ fancybox.js:2
value @ fancybox.js:2`

Thanks!

**Comment by fancyapps** [comment]
Hi,

I can confirm that Carousel (and therefore Fancybox) breaks after including that JS file.
And the reason why it breaks is that DOM elements are no longer instances of `HTMLElement`. You can easily check that by yourself, for example, create `<div>` element and run `document.querySelector("div") instanceof HTMLElement`:

- output before including that JS file: `true`
- output after including that JS file: `false`

I could fix this by changing the check from `HTMLElement` to `Element`, but I'm not sure if that's the right way. :/

**Comment by consigliere23** [comment]
Hm... I see, thanks.
Anything I could do to make it to work?

**Comment by fancyapps** [comment]
This issue seems to be related to this bug report on ampproject - https://github.com/ampproject/amphtml/issues/26424 

I have made changes in upcoming v5 to make it work with AMP project. If you wish, you can join Discord server to get information about the new version - https://discord.gg/6QYFwv6Z

**Comment by consigliere23** [comment]
Thanks @fancyapps

**Comment by consigliere23** [comment]
> I have made changes in upcoming v5 to make it work with AMP project...
Is there any option to get this latest version please? :)

**Comment by fancyapps** [comment]
It will be available in the coming days

**Comment by fancyapps** [comment]
@consigliere23 Could you, please, try out the latest release (currently v5.0.1)?

**Comment by consigliere23** [comment]
Yes of course :)

**Comment by consigliere23** [comment]
Yes it works, perfect! 👍
