### ISSUE TITLE
Events triggered for preloaded images

### ISSUE THREAD

**Issue by Nimrod-666** [fancyapps/ui#4]
Hi, when i use something like

```
Fancybox.bind("[data-fancybox]", {
  on: {
        done: (fancybox, slide) => {
            console.log(slide);
        }
   }
});
```

i would expect that the event only fires when a slide is shown, but it's also triggered for the slide before, and the slide after. So it seems the preloaded slides trigger the event too. I tried it with the load and reveal event too, with the same result. Maybe i understand here something wrong?

**Comment by fancyapps** [comment]
Hi,

That is expected as preloading will load actual content and will trigger all lifecycle events. Here is how to check if that slide is current one -

```js
console.log(`is selected: ${fancybox.getSlide().index === slide.index}`);
```
I'll add this snippet to the docs. Thanks for the feedback!

**Comment by SamuelGaona** [comment]
When you open it again, it doesn't trigger properly the 'onDone' event on the slides before/after .
