### ISSUE TITLE
Fancybox video gallery autoplays all the videos

### ISSUE THREAD

**Issue by geloboyao** [fancyapps/ui#40]
I created a gallery of all videos using html type and I want it to be autoplayed when clicked but all videos (even when not selected) is autoplaying in the background (because I'm hearing the audio of the all the videos I included).

**Comment by steve3d** [comment]
why this is closed? I also have this problem.

**Comment by fancyapps** [comment]
@steve3d Because there is no problem, see - https://fancyapps.com/playground/1xA If you have an issue, please take a minute to create a demo where your issue could be inspected.
