### ISSUE TITLE
Caption used as TITLE in toolbar and not the COUNTER 

### ISSUE THREAD

**Issue by emage** [fancyapps/ui#400]
Using this as a reference: https://fancyapps.com/playground/GP

Is it possible to simply  have the caption TITLE there instead of the counter? In some gallery, there is only 1 item and I was wondering if the TITLE can be placed in the topbar

Basically I want to be able to move the caption to the fixed topbar and have the counter within the image itself.

**Comment by fancyapps** [comment]
Hi,

Please, upgrade to v5 and use this demo as reference - https://stackblitz.com/edit/js-ktcv4h?file=index.js - here you can see how to use `tpl.main` option to create customized layout, how to use `Carousel.change` event to update your info based on the active gallery item.
