### ISSUE TITLE
swipe video mobile

### ISSUE THREAD

**Issue by sahar-08** [fancyapps/ui#401]
hi, swipe video doesn't work on mobile devices

**Comment by fancyapps** [comment]
Hi,

Sorry, but why do you expect that it will work? It will not work unless you create some transparent element over your video/iframe, because touch actions are trapped inside those elements.

**Comment by fancyapps** [comment]
Closing this as the only solution I can think of is to create some element on top of the video element that would intercept the touch events. You can use some events (like `reveal`) for this. But this would of course break the functionality of the video element controls.

```js
Fancybox.bind('[data-fancybox]', {
  on : {
    reveal : (fancybox, slide) => {
      const overlay = document.createElement('div');
      overlay.classList.add('fancybox-video-overlay');
      slide.contentEl.append(overlay);
    }
  }
});    
```

https://jsfiddle.net/xde3rw7o/
