### ISSUE TITLE
Problem with preloading images

### ISSUE THREAD

**Issue by gyurmey2** [fancyapps/ui#403]
[I noticed a problem with preloading images.](https://vento.so/view/22911386-3f64-4c5d-9264-860c707e6c3d)

**Comment by fancyapps** [comment]
Hi,

Thanks for reporting. Well, that was embarrassing, but it should be fixed in v5.0.1

**Comment by gyurmey2** [comment]
@fancyapps Thanks for the amazing quick response. Now it works perfectly.
