### ISSUE TITLE
The [disabled] and [tabindex="-1"] attributes are not added to toggle zoom level

### ISSUE THREAD

**Issue by gyurmey2** [fancyapps/ui#404]
The [disabled] and [tabindex="-1"] attributes are not added to iterate Zoom when the image is not zoomed.

1. Add the snippet below:

```
const options = {
  Toolbar: {
    display: {
      left: [],
      middle: [],
      right: ["iterateZoom"],
    },
  },
};
```

**Comment by fancyapps** [comment]
Hi,

Could you, please, update to the latest (5.0.1) and check if the problem still exists?
If yes, then, please, tell what are your image and viewport dimensions.

**Comment by gyurmey2** [comment]
Now I can't reproduce the problem, so it's ok.

**Comment by fancyapps** [comment]
OK, great, thanks for reporting.
