### ISSUE TITLE
FancyBox 5.01 doesn't work offline?

### ISSUE THREAD

**Issue by alecos71** [fancyapps/ui#405]
I downloaded and then linked FancyBox 5.01 like below but doesn't work.

`<link rel="stylesheet" type="text/css" href="/css/fancybox.css">`

`<script src="/jsc/fancybox.umd.js"></script>`

`<a href="/gfx/QR_b.png" data-fancybox><img src="/gfx/QR.png" class="qr-code" alt="QR Code"></a>`

With previous FancyBox 3 (JQuery Plugin) worked great but coming with version 5.01 written in TypeScript won't work anymore.

Do I need something else to have FancyBox working?

https://fancyapps.com/fancybox/getting-started/

I see only a CDN link, local files are not covered by your documentation.

Please, point me to the solution.

Thanks.

**Comment by alecos71** [comment]
I just tried with:

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css">`

`<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>`

`<a href="/gfx/QR_b.png" data-fancybox><img src="/gfx/QR.png" class="qr-code" alt="QR Code"></a>`

but doesn't work. It's a bug or I need something else?

Thanks

**Comment by fancyapps** [comment]
Hi, Have you added ‘Fancybox.bind()’? That is required for v5.

**Comment by alecos71** [comment]
No, where I need to place it?

**Comment by alecos71** [comment]
I just tried with local files instead with CDN but nothing changed, FancyBox 3 works great, version 5.01 won't work.

I' using Apache 2.4.55 and Php 8.2.3 in Windows and Linux (CentOS).

I have no idea that able me to see it working. It's a bug?

I have Firefox 110.

Thanks.

**Comment by alecos71** [comment]
It's possible to put?

`<body onload="fancybox.bind(), prettyPrint(), clock('clock')">`

**Comment by alecos71** [comment]
Hi again!

I added

`<script>Fancybox.bind("[data-fancybox]", {});</script>`

Before FancyBox is loading and also after FancyBox loading but nothing change, the library won't work.

**Comment by alecos71** [comment]
This is a Test Page for testing purpose...

```
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Alecos">
  <meta name="generator" content="Notepad2">
  <meta name="description" content="Test">
  <meta name="keywords" content="Alecos">
  <meta name="distribution" content="global">
  <meta name="language" content="italian it">
  <meta name="language" content="english en">
  <meta name="rating" content="general">
  <meta name="revisit-after" content="6 days">
  <meta name="pragma" content="no-cache">
  <meta name="robots" content="index, follow">
  <title>Infos</title>
  <link rel="stylesheet" type="text/css" media="screen" href="/css/alecos_screen.css">
  <link rel="stylesheet" type="text/css" media="print" href="/css/alecos_print.css">
  <link rel="stylesheet" type="text/css" media="screen" href="/css/ratings_screen.css">
  <link rel="stylesheet" type="text/css" media="print" href="/css/ratings_print.css">
  <link rel="stylesheet" type="text/css" href="/css/fancybox.css">
  <link rel="stylesheet" type="text/css" href="/gcp/prettify.css">
  <link rel="shortcut icon" href="/favicon.ico">
  <script src="/jsc/fancybox.umd.js"></script>  
  <script src="/jsc/jquery.min.js"></script>
  <script src="/jsc/age_en.js"></script>
  <script src="/jsc/jquery.shorten.min.js"></script>
  <script src="/jsc/more.js"></script>
  <script src="/jsc/popup.js"></script>
  <script src="/jsc/time_en.js"></script>
  <script src="/jsc/scroll_top.js"></script>
  <script src="/jwp/jwplayer.js"></script>
  <script src="/jwp/silverlight.js"></script>
  <script src="/jwp/wmvplayer.js"></script>
  <script src="/gcp/prettify.js"></script>
  <script>Fancybox.bind();</script>
</head>

<body onload="prettyPrint(), clock('clock')">

<div class="mainbox">
  <div class="sidebar">
    <div class="box-menu">
      <a class="menu" href="/infos.php">Infos</a><br>
    </div>
    <div class="rotate"><a href="/pic/236.jpg" data-fancybox><img class="beauty" src="/pic_small/236.jpg" style="border: none" alt="Gallery"></a></div><br>
    <div class="otherbox">
      <a href="/gfx/QR_b.png" data-fancybox><img src="/gfx/QR.png" class="qr-code" alt="QR Code"></a>
    </div><br>
  </div>
</div>

<script src="/jsc/ratings_en.js"></script>

</body>

</html>

<!-- Load Time: 00042.0000 seconds -->
```

**Comment by fancyapps** [comment]
Hi,

It is as simple as this - https://jsfiddle.net/tgcpey0m/

**Comment by alecos71** [comment]
In future release would be possible to remove Fancybox.bind() for compatibility purpose with previous version fancybox 3?

So the easy way to upgrade it's only to renaming the new files like the olds placing them in the same path.

Example:

I'd like to rename

fancybox.css

into

jquery.fancybox.css

and

fancybox.umd.js

into

jquery.fancybox.min.js

so I can try the new version without editing my source files.

I know that FancyBox 5 is written in TypeScript but I'd like to find a way to keep my files updated without editing the sources.

Kind regards.

**Comment by alecos71** [comment]
Now works! Thanks a lot for the help!

Kind regards.

**Comment by fancyapps** [comment]
Sorry, but no, this auto-bind feature was removed for two reasons:

- if there was some delay between custom code has been applied and user clicks, then Fancybox starts with defaults and that leads to confusion;
- auto-bind (and `bind()` method generally) applies the same settings to all elements on the page, and that is problem with frameworks like React where you can have multiple components on the same and users would obviously want different settings per component.

**Comment by alecos71** [comment]
Thanks for the explanations.

kind regards
