### ISSUE TITLE
Carousel missing export in v5.0.1

### ISSUE THREAD

**Issue by ConnorCairns** [fancyapps/ui#407]
**Describe the bug**
When trying to import the carousel JS or CSS file you receive an error about missing exports in the package. The CDN seems to work so it seems like this issue is only when installing through a package manager.

**To Reproduce**
See minimal code sandbox [here](https://codesandbox.io/p/sandbox/crazy-sara-vn14ut?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D)

**Comment by fancyapps** [comment]
Hi,

Well, that is strange, I created a minimal demo on Codesandbox and Stackblitz, and it just works fine:

- https://codesandbox.io/s/interesting-panini-wbe1gx?file=/src/index.js
- https://stackblitz.com/edit/js-rnwgwm?file=index.html,index.js,style.css

Could it be something with your setup?

**Comment by ConnorCairns** [comment]
Found the issue, moving fancyapps from dependencies to dev dependencies fixed the issue for me. I assume it's something to do with how vite loads modules

**Comment by fancyapps** [comment]
This is great news because esm/umd builds are simply created using the Rollup (and transpiled with Typescript plugin to ES6) and there is nothing special about the process.
