### ISSUE TITLE
Weird behavior since 5.x

### ISSUE THREAD

**Issue by msev** [fancyapps/ui#408]
Hi,

I have a strange behavior when I navigate from photo to photo and zoom in since the update to 5.x, I had previously the version 4.0.31.

Tested on Safari iOS 16.3.1.

Screencast on 4.0.31 (good behavior) : 
https://user-images.githubusercontent.com/1529562/220976880-cd91166e-bd41-4622-ac4c-5068e1f9d035.mp4

Screencast on 5.0.1 (weird behavior) :
https://user-images.githubusercontent.com/1529562/220977264-1bcdffee-2095-4504-ab96-dcd72c49c379.mp4

**Comment by fancyapps** [comment]
Hi,

Can you reproduce that on the homepage - https://fancyapps.com/ ? What device are you using? And are you sure you are using 5.0.1 and not 5.0.0?

**Comment by msev** [comment]
I don't reproduce on the homepage of fancyapps.

Tested on Safari iOS 16.3.1.

Yes i am sure iam on 5.0.1

**Comment by msev** [comment]
Hi,

I tested again by removing all CSS and JS from my env, I kept only the CSS and JS from fancyapps.
I have a weird behavior when I double click to zoom: it works once but when I navigate to change the image it doesn't work.
I don't reproduce on the homepage of fancyapps :(

Screencast on my env :
https://user-images.githubusercontent.com/1529562/221143126-689254c6-3d54-48b6-a112-d916858f0b72.mp4

Screencast on fancyapps homepage :
https://user-images.githubusercontent.com/1529562/221143794-9ec8df03-a354-4960-bdcb-51354e55b011.mp4

**Comment by fancyapps** [comment]
Could you, please, give a link to your page/demo?

Maybe be could chat on discord - https://discord.gg/PtQum6Zr

**Comment by msev** [comment]
I found something :

When i edit the CSS import it's works.

From (in JS) : 

`import '@fancyapps/ui/dist/fancybox/fancybox.css';`

To (in HTML <head>) :

```
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"
/>
```

My webpack configuration has PostCSS and cssnano, so I have the impression that they modify this CSS in output

**Comment by msev** [comment]
Fixed by modifying the webpack configuration of my project (ignored PostCSS on node_modules)

Sorry for the waste of time

**Comment by fancyapps** [comment]
Ok, no problem.
