### ISSUE TITLE
fancybox.umd.js can’t in head tag

### ISSUE THREAD

**Issue by Liripo** [fancyapps/ui#41]
Hello,
It seems that fancybox.umd.js cannot be included in the head tag, but the help document does not explain.
How should I make `fancybox.umd.js` dependencies can be included in the head tag?
<details><summary>html example, it can‘t work</summary>

```html
<!DOCTYPE html>
<html>
<head>
  <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css"
/>
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.umd.js"></script>
</head>
<body>


<button data-fancybox data-src="#dialog-content">
  HTML element
</button>

<div id="dialog-content" style="display:none;">
  <h2>Hello, world!</h2>
</div>

<script>
  Fancybox.bind("[data-fancybox]", {
  // Your options go here
});
</script>
</body>
</html>
```

</details>

**Comment by fancyapps** [comment]
Hi,

This is very interesting issue. Fancybox fails if `document.body` is not accessible, and sometimes it is not accessible if script is inside `head` section. You can check it with this simple snippet:

```JS
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World</title>
    <script>
      console.log(document.body);
    </script>
  </head>
  <body>
  </body>
</html>
``` 

In my dev server, it works fine anytime, but, for example, if I try this on Stackblitz/Codepen, it outputs `null`. I will fix Fancybox so it would continue working even if `document.body` is not accessible. Thanks for the feedback!

**Comment by fancyapps** [comment]
The first beta was released today and It should work now.
