### ISSUE TITLE
Cookie compliance

### ISSUE THREAD

**Issue by JesperBOlsen** [fancyapps/ui#411]
Is it possible to make fancybox automatically cookie compliant, when opening Youtube and Vimeo videos?

**Comment by fancyapps** [comment]
Hi,

Could you, please, explain what you mean by that?

Youtube videos are already use `https://www.youtube-nocookie.com` domain name to load an embedded video without automatically setting any cookie. Vimeo videos have `dnt` URL parameter (e.g., "Do Not Track").

**Comment by JesperBOlsen** [comment]
Thank you! I just couldn't find anything about it in the documentation
