### ISSUE TITLE
avoid export option in package.json

### ISSUE THREAD

**Issue by steve3d** [fancyapps/ui#419]
:warning: **Please provide a link to a live sample/demo to get a quick and accurate response!**

**Describe the bug**
First of all, thank you for this big 5.0 upgrade. I'm using angular to develop my applications, but in 5.0's `package.json` file, there is export like: 
```
  "exports": {
    ".": {
      "import": "./dist/index.esm.js",
      "require": "./dist/index.umd.js"
    }
  },
```

Angular now uses `dart-sass` to process styles, so when I want to import the css file in any component or global styles by 
```
@import "@fancyapps/ui/dist/fancybox/fancybox.css";
@import "@fancyapps/ui/dist/carousel/carousel.css";
@import "@fancyapps/ui/dist/carousel/carousel.autoplay.css";
@import "@fancyapps/ui/dist/carousel/carousel.thumbs.css";
@import "@fancyapps/ui/dist/panzoom/panzoom.css";
@import "@fancyapps/ui/dist/panzoom/panzoom.toolbar.css";
```

then angular-cli will throw error:
```
./projects/demo/src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package path ./dist/fancybox/fancybox.css is not exported from package /Volumes/Data/webprojects/ngx-utilities/node_modules/@fancyapps/ui (see exports field in /Volumes/Data/webprojects/ngx-utilities/node_modules/@fancyapps/ui/package.json)
```

So, using the export field in package.json when you have multiple exports are commonly bad idea. Checkout the `package.json` documentation here: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#main

so the correct way of writing these info is :
```
  "main": "dist/index.umd.js",
  "module": "dist/index.esm.js",
  "typings": "types/index.d.ts",
```

**To Reproduce**
1. create some project using dart-scss as scss processor
2. import any css from this package, 
3. then the import are invalid because the package.json said there is only js export no css export.

**Additional context**

**Comment by steve3d** [comment]
also, please do not add `browser` field in package.json, `main` and `module` is enough.

**Comment by fancyapps** [comment]
Hi, Thanks for the suggestions! I have made the changes as you suggested, can you please upgrade to the latest version and check if the problem still persists?

**Comment by fancyapps** [comment]
Looks like it's resolved, thanks for the help!
