### ISSUE TITLE
Wheel slide and fadein/out

### ISSUE THREAD

**Issue by syshut** [fancyapps/ui#425]
Hello, I have two questions:
1.
```
Fancybox.bind('[data-fancybox="images"]', {
    wheel: 'slide',
});
```
When I scroll the mouse wheel, scroll down, the picture will show the previous one, and customarily speaking, I would hope that it is the next one.

2.
```
Fancybox.bind('[data-fancybox="images"]', {
    showClass: 'f-fadeIn',
    hideClass: 'f-fadeOut',
});
```
The corresponding of these two options in v4 should be
```
    showClass: 'fancybox-fadeIn',
    hideClass: 'fancybox-fadeOut',
```
In v4, there were fade-in and fade-outs, but in v5, there is no difference in the display effect after I set it and before it is set. Why?

Thank you for the above two questions!

**Comment by syshut** [comment]
3.
```
Fancybox.bind('[data-fancybox="images"]', {
    wheel: 'slide',
    hideScrollbar: false,
});
```
the scrollbar scrolls when I slide the images with wheel. In v3/v4 the scrollbar would not scroll.

**Comment by fancyapps** [comment]
Hi, Thank you for your valuable feedback!

1) True, I somehow did not notice it, I will change the direction;
2) I guess your images are zooming in/out, right? If you disable that, then images will reveal/hide using CSS transitons, see https://jsfiddle.net/nytuj8sv/
3) Thanks for reporting, I will fix that in the next release.

**Comment by fancyapps** [comment]
@syshut Could you please upgrade to the latest (currently v5.0.6) to check if you are still facing these issues?

**Comment by syshut** [comment]
Great, all bugs are fixed in 5.0.6, thanks!

**Comment by syshut** [comment]
Hi,

it seems that the first problem has appeared again in version 5.0.9, please take a look.

**Comment by fancyapps** [comment]
Hi,

Are you sure? If I scroll down using the mouse wheel, the picture will show the next one https://jsfiddle.net/dbrujx08/

**Comment by fancyapps** [comment]
Oh, sorry about that, it somehow changed again while fighting with macbook trackpad buggy wheel events :/

**Comment by fancyapps** [comment]
@syshut Please, upgrade to the latest. And thank you for your patience :)

**Comment by syshut** [comment]
Yes, it has been fixed again, thank you!
