### ISSUE TITLE
Property 'Hash' does not exist on type 'Partial<OptionsType>'

### ISSUE THREAD

**Issue by sh1zukey** [fancyapps/ui#427]
### Describe the bug

Hi
The new fancybox is cool and nice.

How do I disable the Hash plugin?
I implemented as documented, but the property does not seem to exist.
![image](https://user-images.githubusercontent.com/31560711/222833502-6d105fa7-cd37-4a76-8086-19ac0912f092.png)

Sorry if you are in the process of updating the document.

Sorry my bad english.
Thank you.

### Reproduction

Execute in @fancyapps/ui 5.0.6

The error occurred when passed as an option to the Fancybox constructor.
![image](https://user-images.githubusercontent.com/31560711/222834468-705f8a19-0c2f-4ac8-817b-20aad7873acd.png)

### Validations

- [X] Read the [docs](https://fancyapps.com/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fancyapps** [comment]
Hi,

It should be fixed in the latest release. Thanks for reporting!
