### ISSUE TITLE
Ajax return content

### ISSUE THREAD

**Issue by AlexJMcloud** [fancyapps/ui#430]
Hello.
Created a price request form. The form itself is filled in a modal window. How to return the result of the answer there.

**Comment by fancyapps** [comment]
Hi, I am glad you sorted it out :) Sorry, I did not have time to respond.

**Comment by AlexJMcloud** [comment]
> Hi, I am glad you sorted it out :) Sorry, I did not have time to respond.

Made it the old fashioned way. By replacing the element's content. And without using your methods.

**Comment by fancyapps** [comment]
Quick tip, you can easily access the element that contains your content inside the current Fancybox slide:

```js
Fancybox.getSlide().contentEl
```
