### ISSUE TITLE
How to add custom button to fancybox v5 toolbar and enable click on mobile?

### ISSUE THREAD

**Issue by xdadda** [fancyapps/ui#433]
### Describe the bug

Hi,
I'm upgrading an old fancybox version to the new v5.
I'm struggling to handle a custom button in the toolbar plugin.
I have added the button and can capture a click event  if I'm using a desktop browser (within fancybox option {on: {click: ()=>{ ...} } }) . The click event however is not triggered if using a mobile browser.

In the docs the add a custom button tutorial is missing.

Can you please point me in the right direction?
thanks

### Reproduction

...

### Validations

- [X] Read the [docs](https://fancyapps.com/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fancyapps** [comment]
Hi,

Here is an example - http://fancyapps.com/fancybox/plugins/toolbar/#custom-button

Basically, use `Toolbar.items` option to create new button and then choose the position, example:

```js
Toolbar: {
  items: {
    myButton: {  // name of your button
      tpl: ``, // template of the button
        click: () => {}, // click event
    },
  },
  display: {
    left : [],
    middle : [],
    right : ["myButton"]
  }
}
```

**Comment by bangank36** [comment]
@fancyapps Thanks for the reply, how can we access the `fancybox` instance in toolbar item? Regards

**Comment by bangank36** [comment]
I think can use the static method `Fancybox.getSlide();`, it works
Another question: can we show/hide the toolbar buttons based on active slide? Thanks

**Comment by fancyapps** [comment]
Hi,

1) That is one option. Actually, starting from the next minor release, reference to the instance will be available as first argument inside click event;
2) There is currently no option for that out of the box. You could, for example, use `Carousel.change` event to toggle class name for the container and you could use that to toggle your button using CSS.

**Comment by bangank36** [comment]
Thanks a million, for quick reply too!
