### ISSUE TITLE
Don't show a thumbnail, when the image link is a plain text link

### ISSUE THREAD

**Issue by IMC-GER** [fancyapps/ui#434]
### Is your feature request related to a problem? Please describe.

Fancybox5 don't show a thumbnail, when the image link is a plain text link.
Please look at this example: https://jsfiddle.net/dvhmaL1u/

### Describe the solution you'd like

PLease display the thumbnail.

**Comment by IMC-GER** [comment]
Yes, you are right, it is terrible for performance.

I use Fancybox at my phpBB forum as imageviewer. There are often plaintext links to external images.
At time now i use Fancybox 3. This version shows a thumbnails from this links. I mean the visibility in the thumbnail bar.

The display of these links as thumbnail is already better solved in Fancybox 5 than in version 4. The display as image, as in Fancybox 3 would be nicer.

**Comment by fancyapps** [comment]
OK, but you did not answer to the question - "What do you expect to be shown there"? Do you expect to display there full size image or some dummy element?

**Comment by IMC-GER** [comment]
I expect there the full size image.
https://raw.githubusercontent.com/IMC-GER/images/main/temp/FancyboxScreenshot.jpg

Am 09.03.2023 um 12:33 schrieb Jānis Skarnelis:

**Comment by fancyapps** [comment]
Hi, Please, upgrade to the latest, I have added image src as the fallback.
