### ISSUE TITLE
How to add a Link in data caption and make it work with react router

### ISSUE THREAD

**Issue by AhmadXotox** [fancyapps/ui#435]
Hello, 

I'm using Fancybox in my react app , I need to add a Link in my data caption and make it work with react router, how can I do this ?

**Comment by alecos71** [comment]
Simply use this:

`<a href="/gfx/Avatar_b.png" data-fancybox data-caption="Made with <a style='color: #FF8C00' href='https://www.getpaint.net/index.html' target='_blank'>Paint.NET</a>"><img src="/gfx/Avatar.png" class="avatar" alt="Avatar"></a>`

This is only an example...

**Comment by fancyapps** [comment]
Hi,

You can use the `caption` option where you can create your own elements and attach click handlers. The return value will be added to the caption area (return value can be string or HTMLElement).

**Comment by fancyapps** [comment]
Hello, I hope you managed to achieve your goal. If you have any further questions, please, create a demo using any code playground (codesandbox, stackblitz, etc).
