### ISSUE TITLE
Vimeo private video does not work

### ISSUE THREAD

**Issue by janhenkes** [fancyapps/ui#436]
### Describe the bug

A private vimeo video does not work with Fancybox. The box opens but an error message is displayed: "Sorry This video does not exist."

It seems that the code is not added to the embed URL. Is there a workaround for this? 

### Reproduction

I created this link: 

`<a href="https://vimeo.com/705652986/edf22302ef" data-fancybox="">Bekijk video</a>`

But the "edf22302ef" part is not used in the embed URL. This is the embed URL Fancybox generates:
https://player.vimeo.com/video/705652986?byline=1&color=00adef&controls=1&dnt=1&muted=0

If I manually embed the video without Fancybox, this is the embed URL:
https://player.vimeo.com/video/705652986?h=edf22302ef&dnt=1&app_id=122963

### Validations

- [X] Read the [docs](https://fancyapps.com/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fancyapps** [comment]
Hi,

It should work with the latest update - https://jsfiddle.net/yn6pwgrv/
