### ISSUE TITLE
Image zooming out after open (original size is 1080px x 1080px)

### ISSUE THREAD

**Issue by appdromeda** [fancyapps/ui#437]
### Describe the bug

All problem is described in title. Here is preview:

![Recording 2023-03-14 at 19 25 21](https://user-images.githubusercontent.com/34538050/225102921-45f4281a-0d13-44d4-b39f-acaa3e6e6aee.gif)

### Reproduction

Follow instruction https://fancyapps.com/fancybox/plugins/images/#gallery-with-one-preview-image.
Changing option to:

Images: {
    initialSize: "cover",
},

works but i need initial size as "fit"

### Validations

- [X] Read the [docs](https://fancyapps.com/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fancyapps** [comment]
Hi,

Can you, please, provide link to your page or some demo? I am not able to reproduce this (https://jsfiddle.net/fu6zcjno/) and, as since original size of the image is defined using CSS, I suspect that there might be some CSS conflict on your page. But I am not sure, a live demo would help.

**Comment by appdromeda** [comment]
hello, feature is not public :( i will try to reproduce. Additional info about app:

- fancybox is dynamically imported const { Fancybox } = await import('@fancyapps/ui/dist/fancybox/fancybox.esm.js');
- in options i am providing l10n
- i am initiating fancybox like this: Fancybox.bind($gallery, '[data-fancybox]', config); ($gallery wraps clickable, big image and all hidden thumbs)

**Comment by appdromeda** [comment]
Damn it was indeed CSS. Thank you!

**Comment by fancyapps** [comment]
@appdromeda btw, I noticed your page has a layout shift when opening/closing Fancybox. This article should help you fix that - https://fancyapps.com/fancybox/layout-shift/
