### ISSUE TITLE
Allow slide image/video/pdf to download as different names.

### ISSUE THREAD

**Issue by steve3d** [fancyapps/ui#440]
### Is your feature request related to a problem? Please describe.

many sites use guid as file's basename to store the actual image/video/pdf, but also keeps the original filename.

Now `fancyapps/ui` support download, but the actual downloaded file name are very strange. for example I have a image which url is `files/bridge/2022/19/1ee36ab3-d28f-45ea-b0c4-18df00107699.jpg`, and I also have the original file name like `this-is-a-very-beautifull-picture.jpg`, but when I download the slide image using the download button of toolbar , the actual file name downloaded becomes `files_bridge_2022_19_1ee36ab3-d28f-45ea-b0c4-18df00107699.jpg`. I think this is wrong, either I can download the actual file name `1ee36ab3-d28f-45ea-b0c4-18df00107699.jpg` or I can download the original file name `this-is-a-very-beautifull-picture.jpg`.

### Describe the solution you'd like

I think the better way to do this is add an option to specify the name of download, for example I can give it a name to download as, or if this option did not exists, then just the file name part of the actual url, without the `files_bridge_2022_19_` part.

Add a nullable option like `downloadAs` to specify the downloaded name.

**Comment by fancyapps** [comment]
Hi,

First, if you want full control over the download process, you have to use some server-side script. For example, create a page like "/download/something" and set appropriate headers. For example, using PHP it would be like `header('Content-Disposition: attachment; filename="downloaded.pdf"');`

Fancybox uses the standard `download` attribute for anchors (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download) and, as of v5.0.9, a new data attribute `data-download-filename` is supported and allows you to set a custom file name. Note that the result depends on the browser and whether the file is on the same domain name.

Demo - https://jsfiddle.net/1rj9Lgvc/

**Comment by steve3d** [comment]
thank you for the update, but I'm currently using fancybox with it's api, How can I specify the download name with api? 

https://github.com/fancyapps/ui/blob/448cac8434ada74a6537d9c12d8ea410766ce88c/types/Fancybox/Fancybox.d.ts#L8

there seems no way to specify the download name in slide option?

**Comment by fancyapps** [comment]
Simply camel-case these attributes, like this:

```js
Fancybox.show([{
  src : 'https://lipsum.app/id/15/1600x1200/',
  downloadFilename: "myImage.png",
  downloadSrc: "https://lipsum.app/id/15/3200x2400/"
}], {
  Toolbar: {
    display: {
      left: ["infobar"],
      middle: [],
      right: ["slideshow", "download", "thumbs", "close"],
    },
  }}, {
  Toolbar 
});
```

**Comment by steve3d** [comment]
thanks~
