### ISSUE TITLE
Opt out of youtube nocookie 

### ISSUE THREAD

**Issue by reimerben** [fancyapps/ui#447]
I see fancybox use a https://www.youtube-nocookie.com domain when loading embedded videos, even if the url provided does not specify it. Makes sense for cookie compliance. However, is it possible to opt out of this nocookie behaviour and maintain the original youtube link?

**Comment by fancyapps** [comment]
Hi,

As of v5.0.9, there is a "nocookie" option that allows you to use the usual hostname, use it like this:

```js
Fancybox.bind('[data-fancybox]', {
  Html: {
    youtube: {
      nocookie: 0,
    },
  },
});  
```

Demo - https://jsfiddle.net/jw10vkym/

**Comment by santhoshbalusamy** [comment]
seems like this is not working, even though if we added nocookie option, it is asking to login to view the youtube video, can you please check

@fancyapps

**Comment by fancyapps** [comment]
@santhoshbalusamy Sorry, but what else could be done here? The script uses the domain name "https://www.youtube-nocookie.com" for embedding, and also adds “nocookie=1” to the URL, the rest is up to Google.

**Comment by santhoshbalusamy** [comment]
actually, it is not adding and it is not use the domain name as https://www.youtube-nocookie.com/ when I tried to inspect the URL

**Comment by fancyapps** [comment]
@santhoshbalusamy Sorry, but what did you check? You can clearly see that even on the homepage - 

![Image](https://github.com/user-attachments/assets/ca25cf18-e9bf-4d3f-ac1e-0433947e64d6)

**Comment by santhoshbalusamy** [comment]
@fancyapps 

here is my code 👇 

<img width="1054" alt="Image" src="https://github.com/user-attachments/assets/7ec5e4c5-306c-4184-b2c6-97daebd04672" />

and the output 👇 

<img width="1725" alt="Image" src="https://github.com/user-attachments/assets/10cca367-409d-4002-b663-d44272742fbf" />


PS: I opened it in incognito

**Comment by fancyapps** [comment]
What version of Fancybox are you using?

**Comment by santhoshbalusamy** [comment]
we are using `^5.0.36` this version

**Comment by fancyapps** [comment]
@santhoshbalusamy Oh, I see, your code tells to NOT use `https://www.youtube-nocookie.com` domain name. Remove your code and it will work as expected.
