### ISSUE TITLE
toolbar.scss - can't compile

### ISSUE THREAD

**Issue by morrow95** [fancyapps/ui#45]
Not sure if this is a problem with my compiler being older or what, but it is not liking line 22 in Toolbar.scss in the 4.0.0-beta.0

Error: wrong number of arguments (1 for 3) for `rgb'

```
text-shadow: var(--fancybox-toolbar-text-shadow, 1px 1px 1px rgb(0 0 0 / 40%));
```

Unfortunately the app I use for 'on the fly compiling/minimizing' in Windows hasn't been updated in some time so hopefully there is a work-around for this.

**Comment by morrow95** [comment]
Changing this to the old format does the trick : 

```
text-shadow: var(--fancybox-toolbar-text-shadow, 1px 1px 1px rgba(0, 0, 0, .40));
```

**Comment by fancyapps** [comment]
Hi,

This is the new syntax supported by most browsers - https://caniuse.com/mdn-css_types_color_space_separated_functional_notation - so I think your setup is pretty outdated.

I'll change the syntax to the older format, but is this the only problem you encountered?

**Comment by morrow95** [comment]
@fancyapps Yes, the app I use on Windows to compile/minimize on the fly is definitely outdated as support stopped some time ago.  I'd love to move to another, but have yet to find anything close as far as usability goes.

Other than changing some css around to get my own style/look I haven't come across anything so far.
