### ISSUE TITLE
Background scrolls behind dialog

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/ui#450]
### Describe the bug

The background page scrolls while modal dialogs are open.

### Reproduction

Open a modal dialog. Use the trackpad to scroll the page; the background scrolls.

### Additional context

Seems like the `html.with-fancybox body.compensate-for-scrollbar` classes are not being applied in this scenario.

You can observe this behavior on the [Fancybox website](https://fancyapps.com/fancybox/); click the "Launch Dialog" button in the Examples section, then scroll the page.

### Validations

- [X] Read the [docs](https://fancyapps.com/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fancyapps** [comment]
Hi,

Thanks for reporting, it should work better now.
