### ISSUE TITLE
Fancybox.destroy on mobile device

### ISSUE THREAD

**Issue by alecos71** [fancyapps/ui#462]
### Is your feature request related to a problem? Please describe.

Would it be possible to have the ability to destroy Fancybox only if a mobile device is recognized?

I ask this because I have some digital documentation, which is not manageable via view-port as they are text files that occupy 80 columns and must be printed as they are without reduction or scale or adaptations for devices for which the images attached to the documentation they can be consulted from desktop pc via fancybox but then on mobile devices fancybox must be deactivated to prevent horrendous situations due to the fact that the documents do not respect the view-port of a normal html document.

Would it be possible to add something that destroys fancybox only when there are mobile devices?

Thanks for any suggestions.

### Describe the solution you'd like

```
if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
  Fancybox.destroy();
} else {
  Fancybox.bind('[data-fancybox]', {});
}
```

**Comment by alecos71** [comment]
Solved by putting:

```
<script src="/jsc/fancybox.umd.js"></script>
<script>if (!/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) { Fancybox.bind('[data-fancybox]', {}); }</script>
```

**Comment by fancyapps** [comment]
Hi,

This is the correct answer because you don't need to destroy anything, just add a click handler (via the `Fancybox.bind()` method) only when needed.
