### ISSUE TITLE
Annoying sub-pixel sizing of images

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/ui#463]
### Describe the bug

I am sometimes seeing images appearing with a sub-pixel size. For example, a 1024px image will be displayed as 1023.99px, and the Zoom button will be enabled when it doesn't practically nothing. 

### Reproduction

Display images 1024px on the long side, at maybe a 16:10 or 16:9 aspect ratio. Use srcset definitions with 2x sizes (2048px long edge).

### Additional context

I do not recall this being an issue in Fancybox 4.

**Comment by fancyapps** [comment]
You know what is really annoying? That everyday I have to prove that Fancybox works fine and, for the millionth time, I have to ask for a demo, because I can not reproduce an issue.

I know that you are busy, etc, but there is a reason for this warning:

> ⚠️ Please provide a link to a live sample/demo to get a quick and accurate response!

**Comment by mjcampagna** [comment]
Dude, relax. I know Fancybox works. I’ve been using v3 for ages, dabbled with v4, and I’m now experimenting with v5 with hopes to use it in upcoming projects. 

I’m just letting you know about an issue in hopes to see a fix or improvement, not trying to put you in defense. 

I don’t have a live demo to share at the moment, as I am currently working locally, and not in a good place to push things to a production environment.

**Comment by mjcampagna** [comment]
I think this issue is occurring when setting both `data-width` and `data-height` for images, presumably because Fancybox is trying to abide the `data-height` value. The issue seems to be solved when I remove `data-height` from the markup.

**Comment by mjcampagna** [comment]
I've put together a demo to show the problem.

https://slithy.me/blog/fancybox-5012

**Comment by fancyapps** [comment]
Thanks for your effort, but you could have used any code playground, like jsfiddle, stackblitz, etc.

I'm very sorry, but I can't find any problem. Could you please point it out?
![hmm](https://user-images.githubusercontent.com/1055589/227966159-be5d6b23-e9a7-4256-8fa6-bf1b8e9d016f.png)

Maybe it would be easier to chat, please join Discord (the link is on the homepage).

**Comment by mjcampagna** [comment]
I've joined the discord.
