### ISSUE TITLE
Custom Button Focus Issues

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/ui#464]
### Describe the bug

After clicking a custom button, the carousel loses focus / keyboard listeners no longer function.

For example, after clicking a custom button, I can no longer use the arrow keys to navigate. I first have to re-focus the carousel by clicking one of the native buttons, then can use the keyboard navigation again.

### Reproduction

Add a custom button element somewhere in the UI. In the config, use `on: { click: () => ... }` to do whatever the button does.

After clicking, try to use the keyboard arrow keys to navigate within the carousel.

### Additional context

In my particular case, the button has been added within the `.fancybox__caption` element.

**Comment by fancyapps** [comment]
I'm going to try to fix this, but since you didn't bother to make a demo, I'm not sure I'll succeed.

**Comment by mjcampagna** [comment]
Thanks. If I can share a demo sometime, I’ll try.

**Comment by mjcampagna** [comment]
Demo:
https://slithy.me/blog/fancybox-5012

* Scroll down to the "Captions UI" section. 
* Open the slideshow by clicking any image.
* Click the "i" button in the caption bar.
* Try to use the arrow keys to navigate (it won't work).

Here's the config I'm using:

```js
{
    caption: (fancybox, slide) => {
      const toggleCaptionButton = `
        <button class="fb_caption-button">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="16" x2="12" y2="12"></line><line x1="12" y1="8" x2="12.01" y2="8"></line></svg>
        </button>
      `
      return `<div>${slide.caption}</div>${toggleCaptionButton}`
    },
    commonCaption: true,
    compact: false,
    tpl: {
      main: `
        <div class="fancybox__container fb__kookaburra" role="dialog" aria-modal="true" aria-label="{{MODAL}}" tabindex="-1">
          <div class="fancybox__backdrop"></div>
          <div class="fancybox__carousel"></div>
          <div class="fancybox__footer"></div>
        </div>
      `,
    },
    on: {
      click: (fancybox, event) => {
        // prevent close on off-image click
        if (event.target.closest('.fancybox__slide')) {
          event.preventDefault();
        }
        // captions button
        if (event.target.closest('.fancybox__caption')) {
          console.log(event)
        }
      },
    },
  }
```

In this case, I'm only seeing the issue when using `commonCaption: true`, though in my local environment -- which I am not able to deploy -- I'm also seeing the issue when `commonCaption: false`.

**Comment by mjcampagna** [comment]
Yes, that seems to be better. Thank you.
