### ISSUE TITLE
Running inline js inside fancybox content

### ISSUE THREAD

**Issue by systemshock89** [fancyapps/ui#467]
### Describe the bug
Hi.
In all previous versions Fancybox I can run js inside fancybox content (see example)
Since version 5.0.13 this is not available.
Is it possible to do it again?

### Reproduction

`  new Fancybox(
        [{
            src: '<div>Something</div>' +
                '<script>console.log("test");</script>',
            type: "html"
        }]
    );`

**Comment by fancyapps** [comment]
Hi,

Are you sure you need that? It looks like a hack and I am not sure if it is safe to automatically execute any code :/

Also,  your code snippet is equivalent to this:

```js
new Fancybox( [{ src: '<div>Something</div>', type: "html" }], { on : { "reveal" : () => { console.log("test"); } } } );
```

And it is even more useful as you have access to Fancybox instance and slide object that contains useful info, example:

```js
new Fancybox( [{ src: '<div>Something</div>', type: "html" }], { on : { "reveal" : (fancybox, slide) => { console.log(slide.el); } } } );
```

**Comment by systemshock89** [comment]
Rewrote my code using reveal

**Comment by somegooser** [comment]
I also run into this problem after upgrading from V4. It worked before in V4.

**Comment by 0zd0** [comment]
@fancyapps 
> Are you sure you need that?

Yes, we need this. Since ajax receives dynamic data in scripts from the server and they are not executed
