### ISSUE TITLE
Images are not showing when base href set to "/"

### ISSUE THREAD

**Issue by ze6t9er** [fancyapps/ui#468]
### Describe the bug

I can't get images to be shown when having following tag set in html head :

`<base href="/">`

Is there a way to have the images displayed correctly in this case ?

Thanks in advance.

### Reproduction

I installed Fancybox v5 from CDN along with JQuery 3.4.1 and this is the javascript code which is executed :

```
$(document).on("click", ".file-preview", function(e) {
        e.preventDefault();
        let element = $(this);

        console.log(element.data("src"));
        // https://lipsum.app/id/2/1600x1200

        // Single element
        new Fancybox(
            // Array containing gallery items
            [
                // Gallery item
                {
                    src: element.data("src"),
                    caption: element.data("caption"),
                },
            ],
            // Gallery options
            {
            },
        );
    });
```

**Comment by fancyapps** [comment]
Hi,

Are you sure you are using absolute URLs? Fancybox works fine when absolute URLs are used, see this demo - https://jsfiddle.net/znbkf18r/

I actually do not remember jQuery that well, try replacing `data` (here `element.data("src")`) with `attr` or simply `element[0].src`. But, like I said, I am not sure, I have not been using jQuery for years.
