### ISSUE TITLE
Close button is not showing in HTML 5 Video

### ISSUE THREAD

**Issue by sonupandit** [fancyapps/ui#469]
### Describe the bug

Close button is not showing in HTML5 video. it's coming inside the video tag.

Fancybox version:- 5.0.14

### Reproduction

Please check the codepen link below.

https://codepen.io/pndtsonu/pen/wvYwaaN

**Comment by fancyapps** [comment]
Hi, Please, upgrade to v5.0.15, it should be fixed. Thanks for reporting!
