### ISSUE TITLE
click when select text in input

### ISSUE THREAD

**Issue by systemshock89** [fancyapps/ui#471]
### Describe the bug

Hi, 

Starting from version 5.0.6, I noticed that if you select text in an input field by holding down the left mouse button and then release the button outside of the input field, a click event will occur at the location where the button was released.

As a result, two unexpected outcomes occur:

1. The focus on the input field is lost.
2. If the left mouse button is released outside of the fancybox__content div, the fancybox window will close (because a click occurred outside of the fancybox__content div).

Everything worked fine in version 5.0.5.

### Reproduction

`new Fancybox( [{ src: '<input type="text">', type: "html" }] );`

**Comment by fancyapps** [comment]
Hi, Please, upgrade to v5.0.15, it should be fixed. Thanks for reporting!
