### ISSUE TITLE
I need an exmaple of fancyapps using iframe

### ISSUE THREAD

**Issue by JattJames** [fancyapps/ui#472]
Hi, I got this fancyapps but the iframe does not trigger on my website, for other functionalities, i am using jquery but whenver i create a button and pass data attributes to it, it does not trigger anything, i am planning to a call file in iframe and work over it but it does nothing, literally nothing

**Comment by fancyapps** [comment]
Hi,

Here is a simple iframe demo - https://jsfiddle.net/nk7qLr98/
