### ISSUE TITLE
Allow setting iframe html attributes

### ISSUE THREAD

**Issue by bre7** [fancyapps/ui#473]
### Is your feature request related to a problem? Please describe.

It's not really an edge case, but being able to set `referrerpolicy` and `allow` could help prevent issues when loading referrer protected sites (specially when changing HTTP headers isn't an option).

### Describe the solution you'd like

New `data-iframe-referrerpolicy` and `data-iframe-allow` settings on https://github.com/fancyapps/ui/blob/main/types/Fancybox/plugins/Html/Html.d.ts

```js
iframeReferrerPolicy:
        | "no-referrer"
        | "no-referrer-when-downgrade"
        | "origin"
        | "origin-when-cross-origin"
        | "same-origin"
        | "strict-origin-when-cross-origin"
        | "unsafe-url";

iframeAllow: string;
```

### Describe alternatives you've considered

Hacky JS + Fancybox's events

**Comment by fancyapps** [comment]
Hi,

Starting from v5.0.16 there is an `Html.iframeAttr` option that allows you to customize any attribute for iframe element. 
Usage example:

```js
Fancybox.bind("[data-fancybox]", {
  Html : {
    iframeAttr : {
      referrerpolicy : "no-referrer",
      allow: "geolocation"
    }
  }
}) 
```


Demo - https://jsfiddle.net/euswon0h/
