### ISSUE TITLE
How can i pass values to the fancyapps

### ISSUE THREAD

**Issue by JattJames** [fancyapps/ui#474]
### Describe the bug

I am trying to pass a value by either url or form, but none of the dumps is working on my iframe popup

### Reproduction

pass a url and form and see i cannot pass the values to the fancybox

**Comment by fancyapps** [comment]
Hi,

Sorry, but I couldn't understand what you were trying to accomplish. If you want to access Fancybox instance from withing iframed page, then do it somth like this: `window.parent.Fancybox.getInstance()` (assuming that `Fancybox` is a global object, it depends on how you include Fancybox).

**Comment by JattJames** [comment]
here is my code 

<a href="pages.cfm?id=#pageID#' data-fancybox data-type="iframe">Open Link</a>

Now i want tin my iframe, i should be able to access the ID being passed as URL. 

same is the case with form, on submit, open an fancybox iframe and pass all the form data in there

**Comment by fancyapps** [comment]
But that is up to you, for example, if you are using PHP, then use `$_GET` - https://www.php.net/manual/en/reserved.variables.get.php

**Comment by JattJames** [comment]
i tried that, but did not showed up, so i thought it does require some special changes, i am trying again now
