### ISSUE TITLE
Closing Fancybox hides other element that is shown from jquery code

### ISSUE THREAD

**Issue by nickidotdk** [fancyapps/ui#475]
I am experiencing some weird behaviour with Fancybox. 

I have a "Read more" label that is shown if a div is overflown with text. This is determined on load of the content. By default these labels are hidden, and are shown if the content overflows the div.

If a div is overflown, and the "Read more" label is shown, then adter closing a fancybox, the "Read more" label is hidden, which is its default state, before determining from Javascript if it should be shown. It makes absolutely no sense, since it is an entirely different div than the "Fancybox" link and image.

I have no clue why this happens, and cannot find any similar issue or solution.

Any ideas?

Best regards

**Comment by fancyapps** [comment]
Hi,

Without seeing a live demo, I can only guess that placing focus on the trigger element somehow affects your code. So, please, try setting `placeFocusBack: false` or create a demo where your issue could be inspected.

**Comment by nickidotdk** [comment]
I found the problem. I am using Livewire and Laravel, and I forgot to add wire:ignore to the container. Stupid mistake, and now everything works as expected.
