### ISSUE TITLE
Add the ability to statically set default options for the Navigation plugin

### ISSUE THREAD

**Issue by rhaglennydd** [fancyapps/ui#476]
### Is your feature request related to a problem? Please describe.

Unless I'm mistaken, there doesn't seem to be a way to statically change the `Navigation` options for all instances. For example, this code does nothing:

`Carousel.defaults.Navigation.nextTpl = '...';`

### Describe the solution you'd like

Please add a way to statically change the options for `Navigation`.

### Describe alternatives you've considered

I'm trying to change the arrows for all Fancybox instances with a `Fancybox.bind()` command. It works until you refresh the page with Fancybox loaded, i.e., with a hash value in the URL. Then Fancybox automatically loads when the page refreshes but without the `Navigation` options specified in `bind()`. That's why being able to change the options statically would be nice, unless there is a way to do that that I'm ignorant of.

**Comment by fancyapps** [comment]
Hi,

That would be like this:

```js
Carousel.defaults.Navigation = {
  ...Carousel.defaults.Navigation,
  nextTpl: "NEXT",
};
```

Note: That would affect Fancybox too, because it is built around Carousel component.

**Comment by rhaglennydd** [comment]
OK, first of all, I apologize for being way behind on the latest in Fancybox. I was not aware that Fancybox 5 was out. Now that I've updated to 5, I'm running into more trouble. `Carousel` is no longer a global object when I load `fancybox.umd.js`, so I can't set the default options. Am I supposed to load it separately (i.e., from `carousel.umd.js`)?

**Comment by fancyapps** [comment]
Oh, I am very sorry, I forgot to expose Carousel and Panzoom components within Fancybox JS file. I will fix that in the next minor release. In the meantime, please, include Carousel separately.
