### ISSUE TITLE
is this an way to do a carousel if the items are 4 then start doing carousel else, it should display only 4, i see the one with width

### ISSUE THREAD

**Issue by JattJames** [fancyapps/ui#477]
https://fancyapps.com/carousel/responsive-design/
 and even trying to locate the example where i have 5 products, and it shows like 

1,2,3,4 then 5,1,2,3 so its not showing blank and continous carousel

**Comment by fancyapps** [comment]
HI,

Sorry, but I don't understand your comment at all. Please, create a demo using any code playground like jsfiddle, codepen, etc.
