### ISSUE TITLE
Different Fancybox.defaults

### ISSUE THREAD

**Issue by anitr** [fancyapps/ui#479]
Hi,

I have a code like that:

```
Fancybox.bind("[data-fancybox]", {
        autoStart: true,
        dragToClose: false
    });
Fancybox.defaults.showClass = "my-custom-class";
```

It works great. But now, for some other types of popups on the page, I want to add some other class. So, basically I want two types of fancyboxes on the page that I can style or add options to, one with 'my-custom-class' and one with 'another-custom-class'. Is it possible and how can I do it?

Thank you

**Comment by fancyapps** [comment]
Hi,

Simply use different selectors that matches your links, for example:

```js
Fancybox.bind('[data-fancybox].with-fade', {
  showClass: "f-fadeIn"
})
```

Demo - https://jsfiddle.net/s6uon7xp/

**Comment by anitr** [comment]
Great, thank you for both options. It works as expected :)
