### ISSUE TITLE
New version (5.0.16) popups closes slowly

### ISSUE THREAD

**Issue by anitr** [fancyapps/ui#480]
Hi,

Today I updated my code to the latest version of Fancybox (because I needed to set mainClass) and now, popups closes slowly. Before, I used version 5.0.3 and popup closed immediately after clicking X - close button. Is this optionable or how can I achieve back this?

Thank you.

**Comment by anitr** [comment]
I found out that option animated: false did this. I deleted this option and now it works like before. Sorry for bothering.

**Comment by fancyapps** [comment]
Can you show any demo? I do not see any issue.

**Comment by anitr** [comment]
I figured out that it happens because I need to have background color in my slide. I created jsfiddle.

https://jsfiddle.net/cfb947es/

**Comment by fancyapps** [comment]
Well, there is no issue in your demo, it works as expected. You gave background color to the slide element and therefore you do not see backdrop element. Your content is fading with default animation, as expected. You can disable it like this:

```js
Fancybox.bind("[data-fancybox]", {
  mainClass: "fullscreen-popup",
  showClass: "f-fadeIn",
  hideClass: false,
  hideScrollbar: true,
  dragToClose: false,
  autoStart: true
});
```

https://jsfiddle.net/Lcnzy84f/
