### ISSUE TITLE
closeButton: true; yet no close button shows?

### ISSUE THREAD

**Issue by morrow95** [fancyapps/ui#481]
### Describe the bug

closeButton: true,

Single fancybox that links to a YouTube video - no gallery or anything else grouped with it.  I would expect the above to 'force' a close button to show in the toolbar, but nothing shows.  This is the opposite of how version 4 behaved which would show a close button in this scenario.

### Reproduction

closeButton: true,

Single fancybox that links to a YouTube video - no gallery or anything else grouped with it.  I would expect the above to 'force' a close button to show in the toolbar, but nothing shows.  This is the opposite of how version 4 behaved which would show a close button in this scenario.

### Additional context

Am I missing something with this option and perhaps it is different from version 4?

**Comment by fancyapps** [comment]
Hi,

First, the close button management is really simplified in v5 (compared to v4). An inline close button (e.g., directly above the content) is only created if there is no toolbar.

Then I don't understand your comment because the close button is created as you described without any extra option, see this demo - https://jsfiddle.net/mon2zuab/
(tip: set 'compact: false' to disable compact mode, then it won't overlap the content in a smaller viewport)

**Comment by morrow95** [comment]
This is the behavior I am noticing : 

- If closeButton: true, then there is a close button above the content regardless if toolbar is shown or not (always there).
- closeButton: false, there is never a close button above the content.

I guess what I feel should be happening is the toolbar close button should show when there is a single youtube video in the gallery.  I should be able to have closeButton: false, set and when a single youtube video is shown the toolbar close button still shows in the top right.  Instead, no toolbar buttons of any kind show up.  If the video is in a gallery with multiple items then the toolbar does show, and has buttons that are n/a (such as download, zoom, etc), but when the video is the only one in the gallery there is no toolbar buttons of any kind showing.  This is opposite of what happens when a single image is in the gallery - it still shows toolbar buttons.
