### ISSUE TITLE
Hello sir, can I replace the image in the slide?

### ISSUE THREAD

**Issue by jmm1688** [fancyapps/ui#486]
### Is your feature request related to a problem? Please describe.

I am writing a product detail page and I am using carousel and fancy box, when the product has variants I need to replace the image of the first slide when the user selects a specific variant, I have been trying for two days but without success, can you help me, thank you.

### Describe the solution you'd like

It is good to give some hints，thanks

**Comment by fancyapps** [comment]
Hi,

Glad you got it going, but next time please give a demo with your current progress.
