### ISSUE TITLE
Introduce event for click of the default buttons

### ISSUE THREAD

**Issue by CodeTappert** [fancyapps/ui#488]
### Is your feature request related to a problem? Please describe.

I am currently trying to implement a percentage view of how much the image is zoomed in. 
This is working for every action but the click of the default buttons.

### Describe the solution you'd like

An event that is triggered when one of the default buttons in toolbar is pressed

### Describe alternatives you've considered

A way to add event listeners to the click of the default buttons.

### Additional context

Specifically the "toggle1to1","zoomIn" and "zoomOut" Buttons

**Comment by fancyapps** [comment]
Hi,

I think you need to do it the other way around - add listener to the Panzoom instance and then do your thing. Example:

```js
Fancybox.bind('[data-fancybox="gallery"]', {
  Images : {
    Panzoom : {
      on : {
        "afterTransform" : (instance) => {
          console.log(instance.scale);
          // check this object, it contains useful information that you can use to make calculations
          console.log(instance.contentRect)
        }
      }
    }
  }
});      
```

https://jsfiddle.net/eq1rzh7k/

**Comment by CodeTappert** [comment]
Thank you. This is what i needed!
