### ISSUE TITLE
The thumbnail can not get the correct photo when the photo use lazyload

### ISSUE THREAD

**Issue by jerryc127** [fancyapps/ui#49]
The thumbnail can not get the correct photo when the photo use lazyload

I use the loading photo

![image](https://user-images.githubusercontent.com/16351105/128608923-031b02b4-7e61-4297-ab32-ed9905eeaf98.png)

**Comment by fancyapps** [comment]
Hi,

First, It just not possible to help you with such little information. 

Maybe try using the `data-thumb` attribute for links, example:

```HTML
<a
  href="image.jpg"
  data-fancybox="gallery"
  data-thumb="thumbnail.jpg"
>
  ...
</a>
```
