### ISSUE TITLE
Missing types for l10n translation files

### ISSUE THREAD

**Issue by r-Larch** [fancyapps/ui#490]
### Describe the bug

Fancybox l10n translation files don't have any type definitions, so using them in `typescript` shows an error:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/26417776/235985461-3c3a3ae3-6246-4017-8285-07f51101c4d0.png">

### Reproduction

I use a standard typescript compilation based on `vite@4.2.1` and `typescript@5.0.4`

**Comment by fancyapps** [comment]
Hi,

Sorry for the late reply. The solution is to load the translations directly from the `l10n` directory that contains the TypeScript files:

```js
import { de } from "@fancyapps/ui/l10n/Fancybox/de";
```

https://codesandbox.io/p/sandbox/fancybox-localization-966lhz?file=%2Fsrc%2Fmain.ts%3A4%2C1-4%2C53
