### ISSUE TITLE
Prototype js issue

### ISSUE THREAD

**Issue by anitr** [fancyapps/ui#491]
### Describe the bug

Hi,

on some pages I still have to use prototype js (Prototype JavaScript framework, version 1.7), at the moment, it is too complicated to go to another framework. And on that pages, when I try to use Fancybox 5 or Carousel, it throws errors:

Uncaught TypeError: .for is not iterable:
    at q.updateMetrics (carousel.umd.js?q=1683108117:1:64856)
    at q.init (carousel.umd.js?q=1683108117:1:50384)
    at carousel.umd.js?q=1683108117:1:50207

Is there any solution for that? I know that prototype.js is soo out of date, but for now, I have to stick with it.

Thank you
  

### Reproduction

Using prototype.js and fancybox or carousel on the same page.

**Comment by fancyapps** [comment]
Hi,

I think Prototype modifies native JavaScript methods, and if so, I don't think there is a solution. Both UMD and ESM versions are generated from TypeScript code using the TypeScript compiler and I have no control over it.

You could try to remove the Prototype dependancy, fix it, or remove/fix changes made by the Prototype.
