### ISSUE TITLE
Upgrading from V4

### ISSUE THREAD

**Issue by somegooser** [fancyapps/ui#493]
Hi,

Quick question. Could not find my answer in the documentation. Are there any breaking changes for upgrading fancybox from V4 to V5?

Thanks in advance!

**Comment by Patta** [comment]
https://fancyapps.com/resources/upgrading/

**Comment by fancyapps** [comment]
Hi,

v4 and v5 are similar, but they are not compatible. Therefore it would be
best to take a fresh start when upgrading.

Janis Skarnelis
fancyapps.com

otrd., 2023. g. 9. maijs, plkst. 08:04 — lietotājs Patrick Lenk (<
***@***.***>) rakstīja:
