### ISSUE TITLE
prevent autoplay video

### ISSUE THREAD

**Issue by cheboza** [fancyapps/ui#496]
### Describe the bug

Is there a way to prevent autoplay on youtube videos for plugin? Parameters in url and property youtube:{autoplay:0} not help

### Reproduction

In doc on page https://fancyapps.com/fancybox/plugins/html/

**Comment by fancyapps** [comment]
Hi,

There are two ways:

1) Using `data-video-autoplay="false"` data attribute:

```html
<a
   data-fancybox=""
   href="https://www.youtube.com/watch?v=DLX62G4lc44"
   data-video-autoplay="false"
>
  YouTube
</a>
```

2) Using JS options:

```js
Fancybox.bind('[data-fancybox]', {
  Html: {
    videoAutoplay: false,
  },
});
```

**Comment by cheboza** [comment]
it works, thanks a lot
