### ISSUE TITLE
Carousel jumps back on last page click

### ISSUE THREAD

**Issue by mmoollllee** [fancyapps/ui#498]
### Describe the bug

If a user clicks on the last (incomplete) page of a carousel, a slide to the previous page is triggered.

### Reproduction

[In this demo](https://stackblitz.com/edit/js-4e4dq7?file=index.js) navigate to the last slide and click on the last card.
Carousel will jump back one slide / page

**Comment by fancyapps** [comment]
Hi,

Sorry, but 1) I do not understand what you mean by "incomplete", because slides have 100% with and next/prev slides are visible due to padding on the viewport; 2) I can not recreate an issue, I can click wherever I want and nothing unexpected happens.

**Comment by mmoollllee** [comment]
Sorry for the bad explanation... I can't really tell what "inclomplete" should mean...
Second try:
The example has 6 slides. Depending on the viewport width it's 2 pages x 3 slides -> Problem does not occour.
If viewport is for example 1156px wide, carousel creates 3 pages width 2 slides. In this case, clicking on the last slide Element, while on the last page, carousel swipes one page back.

[output2.webm](https://github.com/fancyapps/ui/assets/26859300/83b7debd-0395-4f5f-ac41-824cd39485d1)

**Comment by mmoollllee** [comment]
This is how it behaves in my local project. It's not only the last slide, but the whole page.
```js
   const container = document.getElementById("thumbs");
   const options = {
      infinite: false,
      transition: "slide",
      initialSlide: container.childElementCount - 1,
      Dots: false,
      Panzoom : {
         touch: false,
         bounce: false,
         click: false
      }
   };

   new Carousel(container, options);
}
```
[output2.webm](https://github.com/fancyapps/ui/assets/26859300/cbd7d202-da0f-422e-a57c-4932b0ce5494)

**Comment by fancyapps** [comment]
Can you create a demo with your setup?

**Comment by mmoollllee** [comment]
Hope this works somehow:
https://stackblitz.com/edit/js-2pohh3

Sorry for the mess!!

**Comment by fancyapps** [comment]
@mmoollllee Please upgrade to the latest version and check if the issue is resolved. 

Btw, I am surprised that you have 3 pages in the first demo (https://stackblitz.com/edit/js-4e4dq7?file=index.js), because you should always have 2 pages. Maybe you have made some changes. Also, I noticed that you are using older version.

**Comment by mmoollllee** [comment]
Thank you this helped with the inital problem already! Now I'm experiencing another, similar problem.
Depending on the screen size, sometimes carousel creates a extra slide for the last item. This happens only with few items in the list. See: https://stackblitz.com/edit/js-j9l3yw
And the video below.

[output.webm](https://github.com/fancyapps/ui/assets/26859300/44deea6a-c5de-4a38-9c3c-8333bb847a03)

> Btw, I am surprised that you have 3 pages in the first demo (https://stackblitz.com/edit/js-4e4dq7?file=index.js), because you should always have 2 pages (if viewport is wide enough). Maybe you have made some changes. Also, I noticed that you are using older version.

I didn't change anything expect for the `infinite: false`
