### ISSUE TITLE
Responsive images: Viewport width change doesnt reculate the right panzoom scale for the new viewport width

### ISSUE THREAD

**Issue by amkdev** [fancyapps/ui#5]
The title says it ... I'm working with responsive images, srcset and sizes. 

it's nessasary to reload that the right scale is working. if not it's possible that the slide is no longer scalable although it should be possible with the dedicated size-setting for the new screen width …

(This happens also if the slide isn't currently not panzoomed.)

**Comment by fancyapps** [comment]
Hi,

Sorry, but I could not understand your comment. Also, try upgrading to the latest, there a few enhancements.

**Comment by amkdev** [comment]
Open the first image in a low view port width - let's say 640 or something. The image is zoomable.

drag the browser window up to full width - 1920. try to zoom in - doesn't work.

close the fancybox popup and reopen - still not possible to scale the image

reload the whole page (width 1920) and open the first image again - now it's zoomable

this works also in the oposite. if I open the image in 1920 this wrong zoom factor stays also in lower viewport widths. the image will be zoomed too much … 

https://fancyphotos.alexander-korn.de/de/__home__/india-2014/neu-delhi

in this way it could happen that on mobile devices and orientation change the image won't be zoomed right.

**Comment by fancyapps** [comment]
This should work fine with the latest release.
