### ISSUE TITLE
Autoplay progress shows up inside slide and not the host

### ISSUE THREAD

**Issue by AndersMad** [fancyapps/ui#501]
### Describe the bug

`f-progress` element is inside the slide - so if autoplay is on a carousel with several slides - it shows in the middle including slide gaps

### Reproduction

Turn on autoplay for a carousel with multiple slides where width is not 100%: https://fancyapps.com/carousel/#multiple-slides

Is there a "playground" for samples?

**Comment by fancyapps** [comment]
Hi,

This is actually the intended behavior. 
Use `progressParentEl` option to customize the position of the progress element - https://fancyapps.com/carousel/plugins/autoplay/#progressparentel

https://jsfiddle.net/2epd5kvf/
