### ISSUE TITLE
Carousel: Minus right margin on track? Gaps..

### ISSUE THREAD

**Issue by AndersMad** [fancyapps/ui#505]
### Is your feature request related to a problem? Please describe.

I am trying to make a gapless carousel on the left and right (with gaps between) and it all works fine with `.f-carousel__track { margin-right: -xx; }` (with same padding right on `f-carousel__slide` and `.f-carousel__slide:last-child { padding: 0; }` etc.), but the problem is that the "calculation" then thinks there is an extra page - e.g. 3 dots instead of 2..

Sample: https://jsfiddle.net/bdh2mLq1/3/

### Describe the solution you'd like

Is there an options or a way to handle this minus right margin on the track? Possible it could check for margin and compensate..

### Additional context

Note that the slides may have different sizes - so can't do a calc width divided by number of slides minus margin etc.

**Comment by AndersMad** [comment]
the sample/doc has no gaps + the size of slides may vary - so can't use calc with division.. its pretty common to use a negavive margin to compensate for the missing html flext "only middle gaps" issue - so just putting in an inner right margin and having the final right minus that margin is a very easy and flixible solution imo.. so I basically just need all the pages pos to be calculated on width but minus a number (I do this now in a timer after on ready - but its cumbersome and hackish with a little flicker)

**Comment by fancyapps** [comment]
You mean it like this - https://jsfiddle.net/8rckq1tz/ ?

**Comment by AndersMad** [comment]
yes, but the problem is that the width is a `calc` and in my case the gap can be from a parant class and the slide width can be any of grid 24 on each page (each slide an arbitrary sizes) - so I'm pretty sure that css width `calc` is a no go for me

**Comment by AndersMad** [comment]
if I use event `initLayout` and recalculate the page pos etc. in a `setTimeout` I seem to be able to avoid initial layout shifts and its all seems to work fine.. but maybe an event from `updateMetrics` where one can do in own calcs a bit less hackish?

**Comment by fancyapps** [comment]
@AndersMad Sorry, but I've decided not to support negative margins, it adds an extra layer of complexity. Alternatively, you can wrap a viewport element with another element, here's a demo - https://jsfiddle.net/o6r8djme/
