### ISSUE TITLE
`backdropClick: "close"` ignored on small screens

### ISSUE THREAD

**Issue by mstratman** [fancyapps/ui#506]
### Describe the bug

When "backdropClick" is set to "close" (explicitly or as the default), and when the browser window is 578px or smaller, clicking the backdrop fails to close the image. Changing the window size to 579px or higher allows the image to be closed as expected.

### Reproduction

* Visit the "Basic Example" on https://fancyapps.com/fancybox/
* Set your browser window width to 578px or smaller
* Click an image to view it
* click the dark backdrop

Expected: Image closes
Actual: No change

Reproduced in Mac Chrome (Version 112.0.5615.137 (Official Build) (arm64)), and Mac (desktop) Safari

**Comment by fancyapps** [comment]
Hi,

Fancybox v5 automatically enables “compact” mode on mobile devices, which mimics touch actions in Apple Photos, etc. (for example, one tap switches information, two taps zoom images). You can disable that by setting `compact:false`.
