### ISSUE TITLE
Fancybox: touch disabled, still can drag 

### ISSUE THREAD

**Issue by runnickrun** [fancyapps/ui#508]
### Describe the bug

For some reason **touch:false** is not respected in fancybox:
https://jsfiddle.net/nLmrjcwu/

### Reproduction

Click on the button, you can drag modal content

**Comment by johnpash** [comment]
Can dragToClose be set using a data-attribute such as `data-drag-to-close="false"`? I've tried that but it doesn't work, but can't find anywhere in the docs that mention whether or not it can be done.

**Comment by fancyapps** [comment]
@johnpash Hi! You can use data attributes to set any slide option, but `dragToClose` is a "gallery option" and cannot be set/changed on a per-slide basis because it is only read once, during Carousel initialization.

But, you could do like this:

```html
<a
   data-fancybox="gallery"
   data-src="https://lipsum.app/id/1/1024x768"
   data-drag-to-close="false"
   >
  <img src="https://lipsum.app/id/1/200x150" />
</a>
```

   
```js
Fancybox.bind('[data-fancybox="gallery"]', {
  dragToClose: (fancybox) => {
    return fancybox.userSlides[0].dragToClose ?? true;
  },
});
```

https://jsfiddle.net/Lz7r9vw1/
