### ISSUE TITLE
slidesPerPage has no effect

### ISSUE THREAD

**Issue by moham96** [fancyapps/ui#510]
### Describe the bug

passing `slidesPerPage` to carousel has no effect( at least in react)

### Reproduction

here is a react example:https://stackblitz.com/edit/react-ts-rokfbn

in App.jsx set slidesPerPage to any number you will see that it has no effect
setting a width in percentage on the slides works fine.

**Comment by fancyapps** [comment]
Hi,

I guess the name is confusing, it is not "how much slides to display at the time", but it is more like "how much slides to slide when pressing left/right arrow".

**Comment by moham96** [comment]
Oh, i see, the name is definitely confusing

**Comment by moham96** [comment]
Well `slidesToSlide` seems self explanatory which is also the name used in another popular package   [react-multi-carousel](https://www.npmjs.com/package/react-multi-carousel)
