### ISSUE TITLE
Listen to when the slide is clicked

### ISSUE THREAD

**Issue by moham96** [fancyapps/ui#511]
### Is your feature request related to a problem? Please describe.

Hi I;m using fancybox with fancy carousel to display videos, I want to call a callback when a slide is clicked (The callback will trigger an ajax call to mark the video as watched),
I'm currently using the `reveal` event but it appears that when I click any slide the event is emitted multiple times(it is emitted for each slide even though I clicked only one slide)

Is this a bug? or is there another event I should use?

### Describe the solution you'd like

There should maybe be an event that gets emitted when a slide is clicked, and only emitted for that slide

**Comment by fancyapps** [comment]
What do you mean by "when slide is clicked"? You mean user clicks on the the DOM element of the carousel slide, or when particular slide is displayed?

**Comment by moham96** [comment]
> What do you mean by "when slide is clicked"? You mean when the user clicks on a DOM element for a carousel slide or when a specific slide is displayed?
Well the user clicks a carousel slide so that it trigger fancybox
> 
> Also, any demo would help to give you an answer. And keep in mind that by default there are 3 slides created (you can configure that using `Carrousel.preload` option), therefore you will receive `reveal` and other events 3 times.
Yes that's exactly what I want to avoid, I want an event that fires only for the clicked slide

A demo is here: https://stackblitz.com/edit/react-ts-rokfbn?file=App.tsx
What I expect is that when I click a slide( a video slide in this case) it should run the callback only for that slide and don't repeat it for every rendered slide

**Comment by fancyapps** [comment]
The very first example here - https://fancyapps.com/fancybox/api/events/#events - show how to determine if the slide is so called "clicked slide" or it is preloaded.
