### ISSUE TITLE
How to prevent closing fancybox when clicked backdrop on both mobile and desktop devices

### ISSUE THREAD

**Issue by yusupov-i** [fancyapps/ui#512]
### Describe the bug

`backdropClick: false` not working, tried on a simple dialog example from documentation

### Reproduction

https://fancyapps.com/fancybox/

**Comment by yusupov-i** [comment]
https://monosnap.com/file/bWi0YadZgcuBsojSeaCyCDoCpV1t95 - is there anyway to prevent closing fancybox in red area, expecting to close it only with the close button?

**Comment by fancyapps** [comment]
Works fine for me - https://jsfiddle.net/8f26auck/

**Comment by bashgeek** [comment]
@fancyapps Does not seem to work here: https://jsfiddle.net/tvnudhxy/ Can you have a look, please?

**Comment by fancyapps** [comment]
I guess you want to disable “compact” mode, add `compact:false`.

**Comment by bashgeek** [comment]
> I guess you want to disable “compact” mode, add `compact:false`.

Doesn't change anything: https://jsfiddle.net/07L3vpg8/

**Comment by fancyapps** [comment]
Sorry, but I do not understand, it just works perfectly fine to me.

pirmd., 2023. g. 3. jūl., plkst. 08:37 — lietotājs Daniel (<
***@***.***>) rakstīja:

**Comment by fancyapps** [comment]
@bashgeek Please, be careful about the `Fancybox.show()` method parameters, they are:

```js
Fancybox.show(ARRAY_OF_GALLERY_ITEMS, GALLERY_OPTIONS)
```

and `backdropClick` is gallery option (and not property of gallery item)

**Comment by bashgeek** [comment]
Ahh, thanks, works as intended then. A real Monday morning for me apparently.
