### ISSUE TITLE
fancybox youtube video issue

### ISSUE THREAD

**Issue by amrithrajnalam** [fancyapps/ui#515]
fancybox youtube video how to make autoplay stop

     Fancybox.bind('[data-fancybox="gallery"]', {
        Thumbs: false,
       
        Iframes: {
          iframeAttr: {
            scrolling : 'no',
          }
	    
	    
    }
       
});

in the above code scrolling : no  is not applying for iframe

**Comment by fancyapps** [comment]
Hi,

Here's a demo on how to disable autoplay - https://jsfiddle.net/6ag1wcxv/

```js
Fancybox.bind('[data-fancybox]', {
  Html : {
    videoAutoplay : false
  }
});    
 ```
