### ISSUE TITLE
Can't bind to 'caption' since it isn't a known property of 'a'. 

### ISSUE THREAD

**Issue by Drunkenpilot** [fancyapps/ui#516]
### Describe the bug

Angular(@analogjs/astro-angular): Can't add data-caption in an <a> tag
```console
[ERROR] NG8002: Can't bind to 'caption' since it isn't a known property of 'a'. [plugin angular-compiler]
```
dependencies: {
  "@analogjs/astro-angular": "^0.2.0-beta.16",
    "@angular-devkit/build-angular": "^16.1.0",
    "@angular/animations": "^16.1.1",
    "@angular/common": "^16.1.1",
    "@angular/compiler": "^16.1.1",
    "@angular/compiler-cli": "^16.1.1",
    "@angular/core": "^16.1.1",
    "@angular/language-service": "^16.1.1",
    "@angular/platform-browser": "^16.1.1",
    "@angular/platform-browser-dynamic": "^16.1.1",
    "@fancyapps/ui": "^5.0.19",
    "rxjs": "^7.8.1",
    "tailwindcss": "^3.3.2",
    "tslib": "^2.5.3",
    "zone.js": "^0.13.1"
}

### Reproduction

```typescript
// angular component
const caption = "image caption text";
```
```html
<!-- angular template -->
<a  href="route_to_image_file" data-fancybox="gallery" [data-caption]="caption" > 
  <img src="route_to_image_thumb_file" />
</a>
```

**Comment by fancyapps** [comment]
I think you should ask this question to the Angular repository/forum.
