### ISSUE TITLE
Request: Add functionality to zoom in on the current display area centered around the axis.

### ISSUE THREAD

**Issue by iwasaki1112** [fancyapps/ui#519]
### Is your feature request related to a problem? Please describe.

Currently, the zoom feature is centered around the origin coordinates (x, y) of the image, which often leads to the area of interest being obscured. As a result, it becomes challenging to focus on specific details that we want to enlarge.

### Describe the solution you'd like

It would greatly improve usability if an additional functionality could be implemented to zoom in on the current display area, taking the center of the visible region as the reference point. This way, users would be able to expand their view while keeping the important elements visible and accessible.

### Describe alternatives you've considered

I have now implemented a smiler feature.

```javascript
const windowWidth = window.innerWidth
const image = pz.content.getBoundingClientRect()
const containerRect = this._element.getBoundingClientRect()

const scrollX = Math.abs((image.left - ((windowWidth - containerRect.width) / 2)))
const contentRemainderX = (image.width - containerRect.width) / 2
const scrollXAmountFromCenter = scrollX - contentRemainderX

const scrollY = Math.abs(image.top - containerRect.top)
const contentRemainderY = (image.height - containerRect.height) / 2
const scrollYAmountFromCenter = scrollY - contentRemainderY

pz.zoomTo(nextScale, {
  originX: scrollXAmountFromCenter,
  originY: scrollYAmountFromCenter
})
```

**Comment by fancyapps** [comment]
Hi, 

Sorry about the late replay, but this is now the default behavior. Thanks for the suggestion.
