### ISSUE TITLE
Fancyapps can't be used in some mobile browsers

### ISSUE THREAD

**Issue by yyj1983** [fancyapps/ui#52]
Fancyapps can't be used in some mobile browsers: it can't slide and so on. For example: Safari browser

**Comment by fancyapps** [comment]
Hi,

Fancyapps components works perfectly on any modern browser. You really got to be more specific when creating an issue report.

**Comment by yyj1983** [comment]
Hello, I use Demo: https://fancyapps.com/docs/ui/fancybox/

Tested two browsers have problems!

1. Xiaomi mobile browser

2. UC browser

3. Individual versions of safari browser (to be further tested)

But v3.5.7 has no problem in any browser!!!

So v4.0 may not be perfect.

As a user, I may not describe it very clearly, but there must be problems with v4.0 in multiple browsers.

**Comment by yyj1983** [comment]
In addition, I think v3.5.7 is the best picture display effect in the world. Thank you here.

**Comment by fancyapps** [comment]
1) What devices are you using? 

2) What do you mean by "picture display effect"? Do you mean the cross-fade effect when changing images?
