### ISSUE TITLE
How can I add an image to the end of the lightbox?

### ISSUE THREAD

**Issue by Container-Zero** [fancyapps/ui#521]
How can I add an image to the end of the lightbox?
I have two usage scenarios where I may need to implement the above requirements:

### Scenario 1:
I have 50 images in my web page originally, I click on any of the images, the lightbox starts successfully and 50 images are loaded in the lightbox, which is fine.
Keep the lightbox open, at this point, suppose my website loads another 50 images through a dynamic technology like ajax, this time the website exists with 50 images at the beginning, plus 50 additional images later, for a total of 100 images.
I need to keep the lightbox not to close the premise, so that the lightbox tail automatically append on the web page through ajax loaded in the 50 images.

### Scenario 2:
Similar to the above scenario: I had 50 images in my web page, I clicked on any of the images, the lightbox started successfully, and 50 images will be loaded inside the lightbox, which is fine.
Keeping the lightbox open, at this point, I get some HTML for the images「[Similar to these](https://fancyapps.com/fancybox/plugins/images/#gallery-of-images)」, which I then need to parse and add to the end of the lightbox for display.

### Tried solutions:
I checked the documentation, but I didn't find anything like "update", "refresh", "append", etc., only something like " show", "setContent" and so on, these functions do not seem to achieve this requirement, I do not know what I should do.

**Comment by fancyapps** [comment]
Fancybox is build around Carousel component and you can append/prepend slides using Carousel methods, like this:

```js
Fancybox.getInstance().carousel.appendSlide({src : "https://lipsum.app/id/11/300x225/"});
```

The only thing currently missing is syncing with thumbnails.

There are two types of thumbnails - modern and classic. Modern thumbnails are not build around the Carousel and there are no methods to manage items.

But classic thumbnails are build around the Carousel, you can add new item like this:

```js
Fancybox.getInstance().plugins.Thumbs.ref.carousel.appendSlide('<img src="https://lipsum.app/id/11/300x225/" />')
```

**Comment by JorisPersua** [comment]
Hello, I'm also very interested in a solution to scenario 2 of OP's question.
I have a setup where in additional images (with additional information like captions) gets loaded in via AJAX.
Is there a way for the appendSlide to access these new images along with the caption data and add it to the Lightbox without closing it?

**Comment by fancyapps** [comment]
@JorisPersua Sorry, but I do not understand your comment, you just use `appendSlide` to add new slide with any data you need:

```js
Fancybox.getInstance().carousel.appendSlide({src : "https://lipsum.app/id/11/300x225/", caption : "My Caption"});
```

**Comment by fancyapps** [comment]
So, you are looking for a way to append multiple slides at once? Then either call it multiple times or pass an array of objects:

```js
Fancybox.getInstance().carousel.appendSlide([
  {
    src : "https://lipsum.app/id/11/300x225/", 
    caption : "My Caption"
  }, 
  {
    src : "https://lipsum.app/id/12/300x225/",
    caption : "Another Caption"
  }
]);

```
