### ISSUE TITLE
Keyboad not working with iFrames

### ISSUE THREAD

**Issue by dogzipp** [fancyapps/ui#522]
### Describe the bug

Keyboard (like pressing "ESC" to close the Fancybox) is not working on iFrames. If you have several items, and you get the Prev/Next arrows, pressing left/right no the keyword won't work either, you have to manually click on the arrows.

### Reproduction

Try the iFrame example here

https://fancyapps.com/fancybox/plugins/html/

It won't close with ESC like all the other examples.

on keydown also won't work.

**Comment by fancyapps** [comment]
Hi,

Actually, that is expected. The script listens for keyboard events on the page, but, if iframe element receives focus, these events are trapped inside the iframed page. 

The solution is to add keyboard listener to your iframed page and then call Fancybox from the parent page, for example, `window.parent.Fancybox.close()` (assuming `Fancybox` is globally available).

**Comment by dogzipp** [comment]
window.parent.Fancybox.close() does work. But how would you do for example slideNext() o .Fancybox.slidePrev()? They do not work.

**Comment by fancyapps** [comment]
@dogzipp  Use `Fancybox.next()` and `Fancybox.prev()`
