### ISSUE TITLE
Allow Caption to be an Element

### ISSUE THREAD

**Issue by asmith20002** [fancyapps/ui#531]
### Is your feature request related to a problem? Please describe.

The caption function returns a string. Sometimes I'd like to put a button with a bind JavaScript function to it. Currently I can return my html button as string and then bind my functionality on `Carousel.change`. 

### Describe the solution you'd like

 I think it would be more convenient if caption function could also return HTMLElement.

**Comment by fancyapps** [comment]
Hi,

Sorry about the late replay, it was made possible in one of the previous releases, see this demo - https://jsfiddle.net/et5rzbyf/
