### ISSUE TITLE
Videos wrong size when scrolling through carousel

### ISSUE THREAD

**Issue by matthewdixon** [fancyapps/ui#535]
### Describe the bug

Inline width and height styles are lost on video slides when scrolling to them from an image slide. This issue is present in v5 latest (5.0.20) but not v4 latest (4.0.31).

### Reproduction

Go to https://codepen.io/matthewdixon/pen/MWzXoWE, select the highlighted item and navigate right 3 times. You'll see the specified video size (192x108) if the item is clicked but not if it's navigated to from an image slide.

**Comment by fancyapps** [comment]
Hi, This should be fixed in a recent release.

**Comment by matthewdixon** [comment]
Many thanks, @fancyapps! 👏
