### ISSUE TITLE
appendSlide creates div element but I need li

### ISSUE THREAD

**Issue by vstyle** [fancyapps/ui#537]
### Is your feature request related to a problem? Please describe.

appendSlide method appends new slide in `<div class="f-carousel__slide ...">` tag but my interface uses `<li>` tags, is it possible to specify `<li>` tag somehow?

### Describe the solution you'd like

I suppose something like:

```javascript
var slide = {
    html: html,
    el: document.createElement('li'), // This line
    isDom: true,
    class: 'some-class',
};
carousel.appendSlide(slide);
```

but it does not work, is there any way to do so?
Thanks!

**Comment by fed9i** [comment]
Hi,
I have the similar issue, looking forward for the solution, 
thanks

**Comment by fancyapps** [comment]
Hi,

First, it is not recommended to use `ul`/`li` tags, because there are a couple of additional `div` elements needed for the functionality. And they are created automatically, if not found.

Anyway, it is now possible to customize slide element - https://jsfiddle.net/shqv1k2j/
