### ISSUE TITLE
When importing as an ESM module, I get an error after building

### ISSUE THREAD

**Issue by Nisekoi5** [fancyapps/ui#539]
### Describe the bug

same as this question，It works in Vite's development mode, but it doesn't work after building
https://github.com/fancyapps/ui/issues/169

You can follow the error prompt and modify the built code as follows
`import { Fancybox } from "@fancyapps/ui";`

change to
```

import pkg from '@fancyapps/ui';
const { Fancybox } = pkg;
```
can run normally

In this issue you said
`So, the question is - how do your settings differ, why doesn't it work for you. Sorry, I'm not a Node expert, I can't tell you the cause of your problem.`
Unfortunately I'm not a node expert either，And I can't read and understand the source code after the build, nor can I fix it
but I found this link, Not sure if this will help you fix this

https://nuxt.com/docs/guide/concepts/esm#troubleshooting-esm-issues

### Reproduction

Use on any page in vite
`import { Fancybox } from '@fancyapps/ui'`
Import the module, then build. Visit this page to see the error message

### Additional context

Another blogger's solution
https://www.luckyzh.cn/article/image-zoom.html

**Comment by fancyapps** [comment]
Hi,

Sorry, but I don't know how to help, it just works fine (for example, the project homepage is built using VitePress).

Make sure you have updated the package to the latest

**Comment by gutschik** [comment]
@Nisekoi5 @fancyapps  I was facing a similar issue and your workaround did not work as well. 

So I headed to https://nuxt.com/docs/guide/concepts/esm#troubleshooting-esm-issues and solved my build problems like this:

**transpiling-libraries**

`nuxt.config.ts`
```typescript
export default defineNuxtConfig({
  build: {
    transpile: ["fancyapps-ui"],
  }
```

**aliasing-libraries**

`nuxt.config.ts`
```typescript
export default defineNuxtConfig({
  alias: {
    "fancyapps-ui": "@fancyapps/ui/dist/index.esm.js",
  },
```

**implementation**

`CustomFancyBox.vue`
```typescript
<script setup>
import { Fancybox } from "fancyapps-ui";
import "@fancyapps/ui/dist/fancybox/fancybox.css";
</script>
```

**The complete vue3 component:**

```typescript
<script setup>
import { onMounted, onUnmounted, ref, watchEffect } from "vue";
import { Fancybox } from "fancyapps-ui";
import "@fancyapps/ui/dist/fancybox/fancybox.css";

// Default options for Fancybox if not provided in props
const defaultOptions = {};

// Props are declared with `defineProps`
const props = defineProps({
  options: {
    type: Object,
    default: () => ({}),
  },
});

const container = ref(null); // Reference to the element Fancybox will bind to

onMounted(() => {
  Fancybox.bind(container.value, "[data-fancybox]", {
    ...(props.options || defaultOptions),
  });
});

watchEffect(() => {
  Fancybox.unbind(container.value);
  Fancybox.close();

  Fancybox.bind(container.value, "[data-fancybox]", {
    ...(props.options || defaultOptions),
  });
});

onUnmounted(() => {
  Fancybox.destroy();
});
</script>

<template>
  <div ref="container">
    <slot></slot>
  </div>
</template>
```

**Comment by Yamabuki-bakery** [comment]
The error "Named export 'Fancybox' not found" occurred here and https://github.com/fancyapps/ui/issues/169 can be related to Server Side Components. Since Fancybox is a client side library, any attempt to server-side render it can cause this error.

For example, in Astro/react, I have a TSX react component that imports Fancybox and I use it in Astro file like this:

```astro
<MyFancybox client:load />
```

and the error can happen because "`client:load`" will attempt to server-side-render it. 
Changing to `client:only="react"` fixes the error.

Hope it may help someone.
