### ISSUE TITLE
Classic mode thumbnails have a refreshed repeatedly bug

### ISSUE THREAD

**Issue by Container-Zero** [fancyapps/ui#540]
### Describe the bug

When thumbnails are enabled.
Move the image from image B to image A by dragging and dropping with the mouse.
At this point, a quick click on the thumbnail of A before the end of the moving animation (i.e. is-animating is present in the fancybox__viewport's class) has a high probability of causing the lightbox to enter a buggy state:
**With any image at rest, clicking on the thumbnail of the current image will cause its image to be refreshed and reloaded with each click.**

### Reproduction

Click to enter: [https://stackblitz.com/edit/web-platform-2vzn8a?file=index.html](https://stackblitz.com/edit/web-platform-2vzn8a?file=index.html)

1. Click the "Open in New Tab" button in the upper right corner. (Important)

2. Click on an image to open Fancybox.

3. Open the thumbnail button in the upper right corner.

4. Assuming the current image is B and the right image is A: drag image B to the left with the mouse to switch to image A, and quickly click on the thumbnail of A before the end of the animation to enter the bug state.

5. See the video below for the detailed process

### Additional context

https://github.com/fancyapps/ui/assets/20435019/0afcf0c9-ab98-4d83-9349-b7ba2fdad315

**Comment by fancyapps** [comment]
Hi, This should be fixed in a recent release.
