### ISSUE TITLE
Lazy loading plugins not compatible with thumbnail carousel

### ISSUE THREAD

**Issue by gavin310** [fancyapps/ui#543]
When opening a gallery with thumbnails, I can't get the thumbnails to load when any lazy loading plugin is active. I've tried with four different plugins, but they all have the same issue. I've also tried adding the "fancybox__thumb" class to the lazy loading exceptions with no success. Is there anything I could try that might help fix this conflict? The thumbnail carousel is the only part causing problems; the main carousel loads fine.

**Comment by fancyapps** [comment]
Hi,

Sorry, but I do not understand what are you referring to. Could you, please, create a demo using any playground (jsfiddle, codepen, etc)?
