### ISSUE TITLE
l10n TOGGLE_ZOOM

### ISSUE THREAD

**Issue by afonja14755** [fancyapps/ui#546]
### Describe the bug

In my case:

```
Fancybox.bind("[data-fancybox]", {
    dragToClose: false,
    l10n: {
      TOGGLE_ZOOM: "Zoom-in/Zoom-out",
    }
  });
```

prop "TOGGLE_ZOOM" doesn't change button caption.

### Reproduction

Init fancybox from CDN, bind it like me in describe, check.

**Comment by fancyapps** [comment]
Hi,

If you refer to the "+/-" button on the default toolbar, then unfortunately for historical reasons you have to use the `ITERATEZOOM` label, for example:

```js
Fancybox.bind('[data-fancybox="gallery"]', {
  l10n: {
    ITERATEZOOM: "Zoom-in/Zoom-out",
  }
});    
```

https://jsfiddle.net/v7w61afd/

**Comment by afonja14755** [comment]
@fancyapps, thanks for the quick response. I took the example from "https://github.com/fancyapps/ui/blob/main/l10n/Fancybox/en.ts" and guess I'm not the only one doing this. It's better to write somewhere about it, or I just read the documentation badly.

Have a good day!
