### ISSUE TITLE
Classic thumbnails doesn't work on click since 5.0.21

### ISSUE THREAD

**Issue by msev** [fancyapps/ui#548]
### Describe the bug

Hi,

The "classic" thumbnails type no longer works on click since version 5.0.21.

Thanks!

### Reproduction

You can reproduce the issue in the documentation : https://fancyapps.com/fancybox/plugins/thumbs/#classic-thumbnails

**Comment by msev** [comment]
Hi @fancyapps, thanks for the fix in 5.0.22!

But there's another bug (sorry)

For example, if you first click on the third thumbnail, then change the active thumbnail with the arrow keys and stop at the fifth thumbnail, pressing the enter or space key returns you to the thumbnail you initially clicked (the third).

You can reproduce the issue here : https://fancyapps.com/fancybox/plugins/thumbs/#classic-thumbnails

**Comment by fancyapps** [comment]
You know, I've been thinking about this a lot, but I haven't decided on the best way to do it - which element to focus on when using the keyboard. Currently it stays on the last clicked element.

**Comment by msev** [comment]
Oh yes, I can see how that would be a hard choice.
