### ISSUE TITLE
Programmatic Usage of embed video failed

### ISSUE THREAD

**Issue by MaxymLeshchenko** [fancyapps/ui#550]
### Describe the bug

When using video embed code like
Fancybox.show([{ src: '<iframe src="..."></iframe>', type: "html" }]);

it failed with JS error
"URL constructor: ... is not a valid URL."

### Reproduction

https://jsfiddle.net/DopeRider/z9rfncL4/4/

### Additional context

Used @fancyapps/ui@5.0.22 for testing

**Comment by fancyapps** [comment]
Hi,

Use it like this:

```js
Fancybox.show([{ html: '<iframe width="560" height="315" src="https://www.youtube.com/embed/CtgJgqeNHcY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>' }]);
```

https://jsfiddle.net/xvLfgjd4/

or 

```js
Fancybox.show([{ src: 'https://www.youtube.com/embed/CtgJgqeNHcY', type: "iframe" }]);
```

https://jsfiddle.net/31qLw8ke/
