### ISSUE TITLE
Iframe form redirect problems

### ISSUE THREAD

**Issue by xApep** [fancyapps/ui#558]
### Describe the bug

On website, I have a button, which on click opens fancybox iframe.

In this iframe is a website subpage with form. When I submit form, I get then browser "error" that It can't redirect. Everything is under one website, in mine case, still localhost.

![image](https://github.com/fancyapps/ui/assets/1315340/77730c7a-6e25-4c0f-bfbb-73684eaed1c3)

### Reproduction

Iframe with form

**Comment by fancyapps** [comment]
Sorry, but did you read the message? The browser disabled page viewing for security reasons.

**Comment by xApep** [comment]
@fancyapps I figure it out that this error only happens on my localhost, but on production it is working. Not sure why thou.

**Comment by fancyapps** [comment]
It is due to browser security policy.
