### ISSUE TITLE
Wrong image sizes when using Carousel + Panzoom

### ISSUE THREAD

**Issue by S4nG0** [fancyapps/ui#560]
### Describe the bug

Using Panzoom on lazyloaded images within Carousel slides seems buggy.

Slides just appear empty, images are getting loaded but both width and height are at 0px.

Is there any way to make this work?

### Reproduction

Here's a demo of the issue : https://codepen.io/jvkonfi/pen/LYMZPje

**Comment by fancyapps** [comment]
But what did you expect? Your carousel has 0px height.

**Comment by S4nG0** [comment]
You're right. Since it was working without specifying any height to the carousel element, I just thought there was an issue with the lazyloading.

Thanks!
