### ISSUE TITLE
Highlighting caption text prevents the Close (X) button from working anymore

### ISSUE THREAD

**Issue by AkinBilgic** [fancyapps/ui#565]
### Describe the bug

Highlighting caption or sidebar text causes just the Close button to stop working when clicked.   See video.

### Reproduction

https://github.com/fancyapps/ui/assets/1250698/53fbdb00-ab17-4f0f-8ed1-ffd6beb02e6a

**Comment by fancyapps** [comment]
Hi, It should be fixed in the latest release.

**Comment by AkinBilgic** [comment]
Thanks!
