### ISSUE TITLE
Turn off grab to next/perv

### ISSUE THREAD

**Issue by amirhosein1000** [fancyapps/ui#567]
Hi
Can I disable grab right/left to next/perv?

**Comment by amirhosein1000** [comment]
ry

**Comment by fancyapps** [comment]
Hi,

Fancybox is built around the Carousel and it is built around Panzoom component, you can pass down options like this:

```
Fancybox.bind('[data-fancybox="gallery"]', {
  Carousel : {
    Panzoom : {
      touch: false
    }
  }
});    
```

https://jsfiddle.net/6da8gsvc/
