### ISSUE TITLE
Question: caption and buttons together with image

### ISSUE THREAD

**Issue by sollerpolt** [fancyapps/ui#568]
Is it possible to reach such layout:

![Безымянный](https://github.com/fancyapps/ui/assets/7893673/616294c9-74e1-4e9b-a160-93e1b4c1aa68)

All controls and caption is one solid piece. When swiping: 

![Безымянный2](https://github.com/fancyapps/ui/assets/7893673/4ff94745-1638-40da-9156-47c64cddf299)

Images can have different ratio. Captions can have differetn text (long and short).

Also do you have unminified version of library?

**Comment by fancyapps** [comment]
Hi,

1)Is it possible to reach such layout

Not really. First, there are reasons for the current layout. Your layout has significant issues - what if the image is really small; or if the user is using a small screen device and the image is resized to a tiny size; what will happen if the description is very long - it would cover the whole picture; what happens after the zoom button is pressed, wouldn't the layout get weird?

You can try to create custom elements over the content, but it's not optimized for that, and the result is not very good https://jsfiddle.net/k8gw27mu/

2)Also do you have unminified version of library 

Sorry, it is not currently available.
