### ISSUE TITLE
Debug methods

### ISSUE THREAD

**Issue by 6562680** [fancyapps/ui#576]
### Is your feature request related to a problem? Please describe.

I've made attributes [data-fancybox-button] and [data-src="#modal-form-call"] at my link, and its not working at all. Btw the button that placed below with same attributes works correctly. I need to debug some things and all methods return types is void.

Also seems you have interfaces that mismatch actual code, fromSelector not working at all, i surprisingly used show { src: domElement, type: inline } that works on page start (parsing window.location.hash), and tried to explore Fancybox.d.ts, and there's no [ type: 'inline' ] described. What's wrong with this library?

```
<a class="menu__menu-link" data-fancybox-button="" data-src="#modal-form-call" href="javascript:;" title="MyTitle">MyText</a>
```
is not working. Also on this link defined additional handler, cause of this menu part of OVERLAY, and there's event handler with e.stopPropagation() call. There's no preventDefault() call.

```
<button type="button" title="MyTitle" data-fancybox-button="" data-src="#modal-form-call" class="button button_solid button_one-md">
MyText
</button>
```

is working as expected.

Init code:
```
    Fancybox.bind( '[data-fancybox-button]', {
        l10n: ru,

        autoDimensions: true,
        autoScale:      true,
        centerOnScroll: true,

        hideClass: false,
        showClass: false,

        transitionIn:  'elastic',
        transitionOut: 'elastic',
        speedIn:       600,
        speedOut:      200,
    } );
```

### Describe the solution you'd like

At least "list" registered fancyboxes to display

**Comment by 6562680** [comment]
Changed code like that:

```
    function onClickFancyboxButton(e) {
        Fancybox.show(
            [
                { src: e.currentTarget.dataset.src, type: 'inline' },
            ],
            {
                l10n: ru,

                autoDimensions: true,
                autoScale:      true,
                centerOnScroll: true,

                hideClass: false,
                showClass: false,

                transitionIn:  'elastic',
                transitionOut: 'elastic',
                speedIn:       600,
                speedOut:      200,
            } );
    }


    await dom$Ready();

    const domFancyboxButton = dom$( '[data-fancybox-button]' );

    domFancyboxButton.map( (dom) => dom.addEventListener( 'click', onClickFancyboxButton ) );
    ```

**Comment by fancyapps** [comment]
btw, none of these options exist in v5:

```
  autoDimensions: true,
  autoScale:      true,
  centerOnScroll: true,

  transitionIn:  'elastic',
  transitionOut: 'elastic',
  speedIn:       600,
  speedOut:      200,
```
