### ISSUE TITLE
Fancybox.getInstance().carousel.appendSlide(video) does not work

### ISSUE THREAD

**Issue by gDuval60** [fancyapps/ui#578]
### Describe the bug

When I try to add a video to a Fancybox instance, the video does not load.

### Reproduction

let video = {
  src: URL,
  type: "video",
  thumb: thumbURL
  id: id
}

Fancybox.getInstance().carousel.appendSlide(video);

**Comment by fancyapps** [comment]
Well, it works fine for me, so, please, create a demo where your issue could be observed.

**Comment by gDuval60** [comment]
i make this https://jsfiddle.net/3g2y9xwf/62/

**Comment by gDuval60** [comment]
It works ! Thanks !

**Comment by gDuval60** [comment]
Can we read .MOV video (apple) ?
