### ISSUE TITLE
Animation errors in Fancybox.next() and Fancybox.prev()

### ISSUE THREAD

**Issue by Container-Zero** [fancyapps/ui#579]
### Describe the bug

When I use `Fancybox.next()` or `Fancybox.prev()`
If you click anywhere on the lightbox with your mouse at this point, there is a small chance that the image fade animation will change to an image scroll animation.

### Reproduction

When I use `fancybox.next()` or `fancybox.prev()`
If you click anywhere on the lightbox with your mouse at this point, there is a small chance that the image fade animation will change to an image scroll animation.

Click to enter: https://stackblitz.com/edit/web-platform-lnehx7?file=index.html

1. click on the image to open Fancybox.

2. I have used `setInterval(function(){Fancybox.next();},500);` in script.js file to trigger `Fancybox.next()` without any interruption so that the image will switch automatically.

3. Please use your mouse to click the image frequently and quickly at the same time.

4. there is a certain probability that a sliding animation will be triggered instead of the normal fade-in and fade-out

I'm pretty sure it's not a mouse slide that triggers the misbehavior because I used `lockAxis` to exclude the possibility of horizontal scrolling.
See the video below for the detailed process

### Additional context

https://github.com/fancyapps/ui/assets/20435019/ef947593-151e-4662-8c92-fe96ca066939

**Comment by fancyapps** [comment]
Hi,

1) Actually, I could not see any issue in your demo.
2) If you click the image quickly, you might accidentally drag it a little, then the JS animation will start to place it back. But if there is any JS animation, next/previous gallery item change will not use CSS transition.

Anyway, I will see what I could improve.

**Comment by Container-Zero** [comment]
> Hi,
> 
> 1. Actually, I could not see any issue in your demo.
> 2. If you click the image quickly, you might accidentally drag it a little, then the JS animation will start to place it back. But if there is any JS animation, next/previous gallery item change will not use CSS transition.
> 
> Anyway, I will see what I could improve.

No... I don't think I'm triggering the drag, I'm using the following code:
```
Panzoom: {
  lockAxis: () => {
    return 'y';
  },
},
```
This code has drag disabled, and I've used mouse listening for troubleshooting in my actual raw production environment, and I'm pretty sure my mouse still triggers the above bug without any movement.

You can check to make sure I'm right.

**Comment by Container-Zero** [comment]
> Hi,
> 
> 1. Actually, I could not see any issue in your demo.
> 2. If you click the image quickly, you might accidentally drag it a little, then the JS animation will start to place it back. But if there is any JS animation, next/previous gallery item change will not use CSS transition.
> 
> Anyway, I will see what I could improve.

Here's a demo of my production environment: https://stackblitz.com/edit/web-platform-mb6hqt?file=index.html,script.js

1. This function mainly works on mobile.
2. It will change the left half of the screen to the previous image by clicking on it, and the right half to the next image.
3. Disable the drag-and-drop image switching feature while you're at it. (Of course I can keep it, but at the moment it's not easy to debug the above problem)
4. At the same time also retained the double-click on the image to enlarge the image.
5. But if you frequently click on the right or left side of the screen to switch images, you will find that the above bugs have a high probability of recurring.

Can you take a look at this demo, is it a problem with fancybox? Or is there something I need to improve?

**Comment by fancyapps** [comment]
I think I have found the cause. I will release the next update in the coming days.

**Comment by Container-Zero** [comment]
> I think I have found the cause. I will release the next update in the coming days.

Thank you for your dedication.

**Comment by fancyapps** [comment]
@Container-Zero Could you, please, upgrade to the latest and see if that helps?

**Comment by Container-Zero** [comment]
> @Container-Zero Could you, please, upgrade to the latest and see if that helps?

Thank you. The problem has been resolved!

**Comment by Container-Zero** [comment]
> @Container-Zero Could you, please, upgrade to the latest and see if that helps?

Hello, I would like to additionally ask about the usage example of `addSlide` in `5.0.25`, does he have any differences and benefits over the existing `appendSlide`?

**Comment by fancyapps** [comment]
Well, `addSlide` lets you choose exactly where to place new slides. This is the actual source code for the `appendSlide` and `prependSlide` methods:

```js
prependSlide(what: userSlideType | Array<userSlideType>) {
  this.addSlide(0, what);
}

appendSlide(what: userSlideType | Array<userSlideType>) {
  this.addSlide(this.slides.length, what);
}
```
