### ISSUE TITLE
Scroll doesn't work on AJAX requests, if you are using wheel:slide

### ISSUE THREAD

**Issue by svgenov** [fancyapps/ui#582]
### Describe the bug

I'm using the same code to handle photos, videos, maps and some AJAX requests. It works beautifully, however, if the AJAX content is larger, even if you explicitly set visibility to scroll, the scrollbar will not work.

### Reproduction

In my case I'm using the (same) following code to handle photos, videos, maps and some AJAX requests:

`Fancybox.bind('[data-fancybox]', {
        wheel: 'slide',
        contentClick: 'next',
        Toolbar: {
            display: {
                left: ["infobar"],
                middle: [],
                right: ["slideshow", "thumbs", "close"],
            }
        },
    });`

It works beautifully for photos, videos and maps. However, if the AJAX content is larger, even if you explicitly set visibility to scroll, the scrollbar will not work.

**Comment by fancyapps** [comment]
Thanks for the report, it should be improved in the latest update.
