### ISSUE TITLE
jump to last slide using events?

### ISSUE THREAD

**Issue by morpolspc** [fancyapps/ui#586]
Use case is I am checking my database for 'new' images every x seconds and adding them to my carousel as they come in.  When the page loads there is no carousel... until it finds a new image... then I create the carousel instance... after it has been created I just add slides to the already created carousel from there on out.  What I am trying to do is jump to the last slide using the carousel listeners.  The below code does not work... any help would be appreciated.

In particular ```_carousel.slideTo(_carousel.slides.length - 1);``` in the ```initSlide``` listener.  Yes, the if condition it is within is true.

```
		sliderInst = new Carousel(document.getElementById('slider'), {    
			Dots: false,
			on: {
				initSlide: (_carousel, slide) => {
			  		// current
			  		sliderControls.find('.slide-current-slide').html(_carousel.page + 1);
			  		//total
			  		sliderControls.find('.slide-total-slides').html(_carousel.slides.length);

					//if jump to latest is on
					if( $('#jumpLatest').prop('checked') ) {
						//stop playing if it is and auto go to last slide added
						//_carousel.plugins.Autoplay.stop();
						_carousel.slideTo(_carousel.slides.length - 1);
					}	
				},
				change: (instance) => {
					//console.log('change', instance);
			  		// current
			  		sliderControls.find('.slide-current-slide').html(instance.page + 1);
			  		//total
			  		sliderControls.find('.slide-total-slides').html(instance.slides.length);
				},
			},
			Thumbs: {
				type: 'classic',
				minCount: 1
			},
			Autoplay: {
				autoStart: false,
				pauseOnHover: true,
				timeout: 5000,
			},
		},
			{ Thumbs, Autoplay }
		);
```

**Comment by fancyapps** [comment]
Hi,

Sorry, but I can't help you without a live demo, please use any code playground to create one or just fork any demo you can find in the documentation.

**Comment by fancyapps** [comment]
Here is an example - 

```js
const myCarousel = new Carousel(document.getElementById("myCarousel"), {
  on : {
    initSlide: () => {
      requestAnimationFrame(() => {
        const panzoom = myCarousel.panzoom;

        if (panzoom  && !panzoom.isDragging && panzoom.isResting) {
          myCarousel.slideTo(myCarousel.pages.length - 1);
        }
      });
    }
  }
});

setInterval(() => {
  myCarousel.appendSlide({
    html: `${myCarousel.slides.length + 1}`
  });
}, 1000);
```

https://jsfiddle.net/zstgexdn/

**Comment by morpolspc** [comment]
Have things working with requestAnimationFrame - thank you.  I assume the reason it was not working earlier was due to animation.  Maybe add an afterInitSlide event?

**Comment by fancyapps** [comment]
I've rearranged the code a bit and the 'requestAnimationFrame' is no longer needed - https://jsfiddle.net/6rcj9uwe/1/
