### ISSUE TITLE
Can panzoom be used for any html content or just images?

### ISSUE THREAD

**Issue by gettonet** [fancyapps/ui#587]
Hi, I'm trying to use panzoom like this:

`<div class="f-panzoom" id="myPanzoom">`
`<div class="f-panzoom__content">`
`  <img  src="https://lipsum.app/id/1/1200x1500" />`
`<svg>....</svg>`
`</div>`
`</div>`

...expexting that everything inside f-panzoom__content pans/zooms, including svg. Is it possible?

**Comment by fancyapps** [comment]
Hi,

Use option `transformParent: true` and wrap your content with `<div class="f-panzoom__viewport"></div>`:

```html

<div class="f-panzoom" id="myPanzoom">
  <div class="f-panzoom__viewport">
    <p>
      Hello
    </p>
    <img class="f-panzoom__content" src="https://lipsum.app/id/1/1200x1500" />
  </div>
</div>
```


https://jsfiddle.net/54kb1cju/

**Comment by fancyapps** [comment]
Another solution would be something like this - https://jsfiddle.net/54kb1cju/1/

**Comment by gettonet** [comment]
That did the trick. Thank you.
