### ISSUE TITLE
incorrect operation of the carousel in the modal window after reopening it

### ISSUE THREAD

**Issue by chimir** [fancyapps/ui#589]
### Describe the bug

incorrect operation of the carousel in the modal window after reopening it

### Reproduction

1. open modal
2. close modal
3. open modal again

**Expected result:**
carousel works correctly

**Actual result:**
incorrect slide positioning
incorrect transition animation

https://codepen.io/chimir/pen/vYbpPdK

### Additional context

![image](https://github.com/fancyapps/ui/assets/15053703/a6a4429a-440a-4c96-9c36-60c62814a75c)

**Comment by fancyapps** [comment]
Hi,

Thanks for reporting, this has been fixed in the latest release.
