### ISSUE TITLE
Only named exports may use 'export type'

### ISSUE THREAD

**Issue by Velmoren** [fancyapps/ui#590]
### Describe the bug

My settings:
Angular 13
"tslib": "^2.0.0",
"typescript": "~4.6.4"
"@fancyapps/ui": "^5.0.28",

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/@fancyapps/ui/types/Carousel/Carousel.d.ts:6:1 - error TS1383: Only named exports may use 'export type'.

6 export type * from "./plugins/index";
 

Error: node_modules/@fancyapps/ui/types/Carousel/plugins/index.d.ts:2:1 - error TS1383: Only named exports may use 'export type'.

2 export type * from "./Dots/Dots";


Error: node_modules/@fancyapps/ui/types/Carousel/plugins/index.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.

3 export type * from "./Navigation/Navigation";


Error: node_modules/@fancyapps/ui/types/Carousel/plugins/index.d.ts:4:1 - error TS1383: Only named exports may use 'export type'.

4 export type * from "./Sync/Sync";


Error: node_modules/@fancyapps/ui/types/Fancybox/Fancybox.d.ts:5:1 - error TS1383: Only named exports may use 'export type'.

5 export type * from "./plugins/index";


Error: node_modules/@fancyapps/ui/types/Fancybox/plugins/index.d.ts:2:1 - error TS1383: Only named exports may use 'export type'.

2 export type * from "./Hash/Hash";


Error: node_modules/@fancyapps/ui/types/Fancybox/plugins/index.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.

3 export type * from "./Images/Images";


Error: node_modules/@fancyapps/ui/types/Fancybox/plugins/index.d.ts:4:1 - error TS1383: Only named exports may use 'export type'.

4 export type * from "./Html/Html";


Error: node_modules/@fancyapps/ui/types/Fancybox/plugins/index.d.ts:5:1 - error TS1383: Only named exports may use 'export type'.

5 export type * from "./Slideshow/Slideshow";


Error: node_modules/@fancyapps/ui/types/Fancybox/plugins/index.d.ts:6:1 - error TS1383: Only named exports may use 'export type'.

6 export type * from "./Thumbs/Thumbs";


Error: node_modules/@fancyapps/ui/types/Fancybox/plugins/index.d.ts:7:1 - error TS1383: Only named exports may use 'export type'.

7 export type * from "./Toolbar/Toolbar";


Error: node_modules/@fancyapps/ui/types/Panzoom/Panzoom.d.ts:5:1 - error TS1383: Only named exports may use 'export type'.

5 export type * from "./plugins/index";
  

Error: node_modules/@fancyapps/ui/types/shared/Base/types.d.ts:4:116 - error TS2589: Type instantiation is excessively deep and possibly infinite.

4     [K in Extract<keyof O, string>]: O[K] extends Array<any> ? K : O[K] extends Record<string, unknown> ? `${K}` | `${K}.${DeepKeyOf<O[K]>}` : K;

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Reproduction

1) install "@fancyapps/ui": "^5.0.28",
2) in component.ts import { Fancybox } from '@fancyapps/ui';
3) npm start

**Comment by fancyapps** [comment]
Hi,

Thanks for the reporting, but I am not able to reproduce any of those issue. Even using different code playgrounds:
https://stackblitz.com/edit/react-ts-zfff59?file=App.tsx,Carousel.tsx,Fancybox.tsx
https://codesandbox.io/s/autumn-thunder-b7ecz7?file=/src/Fancybox.tsx

So if you have any hints/ideas, I'd love to hear them.

**Comment by Velmoren** [comment]
Hello

That's right, but angulat 13 is not able to use higher TypeScript versions (max version 4.7). If exports are escaped // @ts-ignore everything works, but unfortunately I won’t be able to do this in the library. Need named exports

**Comment by Velmoren** [comment]
I think the https://stackblitz.com service ignores TS errors

**Comment by Velmoren** [comment]
Is it possible to add a separate version for Angular with escaped exports (at least) with the __betta prefix (for example). Or you will have to wrap the library code in a separate library with a fix

**Comment by Velmoren** [comment]
This is how we managed to fix the export error 
```
export * from './Dots/Dots'; 
export * from './Navigation/Navigation'; 
export * from './Sync/Sync';
```

instead 

```
export type * from './Dots/Dots'; 
export type * from './Navigation/Navigation'; 
export type * from './Sync/Sync';
```

**Comment by AsbDaryaee** [comment]
Hi, I have kind of same issue using Nuxt 3:

```
- Operating System: Linux
- Node Version:     v21.2.0
- Nuxt Version:     3.8.1
- CLI Version:      3.10.0
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      devtools, css, postcss, modules, colorMode, runtimeConfig, device, vite, vue, gtag, app
- Runtime Modules:  nuxt-schema-org@3.2.0, @nuxt/image@1.0.0, @pinia/nuxt@0.4.11, @vueuse/nuxt@10.6.1, @nuxtjs/device@3.1.1, nuxt-gtag@1.1.1, @nuxtjs/color-mode@3.3.2
- Build Modules:    -
```

And the error is: 

```
SyntaxError: Named export 'Fancybox' not found. The requested module '@fancyapps/ui' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@fancyapps/ui';
const { Fancybox } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async setup (file:///src/server/chunks/app/server.mjs:21008:76)
    at async Object.callAsync (file:///src/server/chunks/app/server.mjs:91:16)
    at async applyPlugin (file:///src/server/chunks/app/server.mjs:18417:35)
    at async applyPlugins (file:///src/server/chunks/app/server.mjs:18437:7)
    at async createNuxtAppServer (file:///src/server/chunks/app/server.mjs:25003:7)
    at async Object.renderToString (file:///src/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
    at async file:///src/server/chunks/handlers/renderer.mjs:217:21

```

I followed the instruction in https://fancyapps.com/resources/integration/#vue

**Comment by AsbDaryaee** [comment]
> @AsbDaryaee Hi,
> 
> This is a misleading message - `'@fancyapps/ui' is a CommonJS module` - it is not a CommonJS module. And it works fine as you can clearly see in any demo you can find in the docs, therefore I have no idea how to help you.
> 
> Maybe try loading it directly, like this:
> 
> ```js
> import { Fancybox } from '@fancyapps/ui/dist/fancybox/fancybox.esm.js';
> ```
> 
> Working demo - https://stackblitz.com/edit/js-xue4qe?file=index.js

Many thanks for your attention, I tried this and it's working fine:

```
import * as fancy from "@fancyapps/ui";
const { Fancybox } = fancy;
```

**Comment by bugproof** [comment]
@fancyapps

I think if you add `"type": "module"` in the project package.json this will solve this issue. There is some issue with vite dev tools or vite in general and it favours "main" over "module"

![Image](https://github.com/user-attachments/assets/b3752d1c-642b-4ecf-a3c3-ac8312597356)

So to use it in SvelteKit for example you need to do

```ts
import { Fancybox as NativeFancybox } from '@fancyapps/ui/dist/index.esm.js';
```

Create `fancyapps-ui-esm.d.ts` with following content

```ts
declare module '@fancyapps/ui/dist/index.esm.js' {
  export * from '@fancyapps/ui';
}
```

adding type module to package.json could solve this issue, but this is the only way for now to use it with next.js/sveltekit/nuxt/vite-based tools

**Comment by bugproof** [comment]
Also example Svelte component that works in SvelteKit:

```svelte
<script lang="ts">
	import { onMount, type Snippet } from 'svelte';
	import { Fancybox as NativeFancybox } from '@fancyapps/ui/dist/index.esm.js';
	import '@fancyapps/ui/dist/fancybox/fancybox.css';
	import type { OptionsType } from '@fancyapps/ui/types/Fancybox/options';

	interface Props {
		children: Snippet;
		delegate?: string;
		options?: Partial<OptionsType>;
	}

	let { delegate = '[data-fancybox]', options = {}, children }: Props = $props();

	let container: HTMLDivElement;

	onMount(() => {
		NativeFancybox.bind(container, delegate, options);

		return () => {
			NativeFancybox.unbind(container);
			NativeFancybox.close();
		};
	});
</script>

<div bind:this={container}>
	{@render children()}
</div>

```

**Comment by fancyapps** [comment]
@bugproof The problem is that I can not add `"type": "module"` as the main type is not module, but UMD. I cannot believe that "modern" tools have not solved such simple issue, all they have to do is to use the standard `module` field.

The problem is that I can't add  `"type": "module"` because the main type is not module but UMD. It's unbelievable that "modern" tools haven't solved such a simple problem, they just need to use the standard "module" field.

**Comment by bugproof** [comment]
Yeah, it's some bug with vite probably. There are many packages dedicated for ESM using postfix like -es or -esm and that solves the problem as well.

**Comment by fancyapps** [comment]
@bugproof I'm thinking about changing the default type to module with the next major release, but I still need to do some testing. Thanks for your concern.
