### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined     at jquery.fancybox.min.js:12:6030

### ISSUE THREAD

**Issue by GlenBoonzaier** [fancyapps/ui#591]
### Describe the bug

I am getting the following error when simply referencing the js file.

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha512-uURl+ZXMBrF4AwGaWmEetzrd+J5/8NRkWAvJx5sbPSSuOb0bZLqf+tOzniObO00BjHa/dD7gub9oCGMLPQHtQA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

Uncaught ReferenceError: jQuery is not defined
    at jquery.fancybox.min.js:12:6030
(anonymous) @ jquery.fancybox.min.js:12

### Reproduction

Reference:

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha512-uURl+ZXMBrF4AwGaWmEetzrd+J5/8NRkWAvJx5sbPSSuOb0bZLqf+tOzniObO00BjHa/dD7gub9oCGMLPQHtQA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

### Additional context

If I use the reference

<script src="https://cdn.jsdelivr.net/npm/@@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>

There is no error

**Comment by fancyapps** [comment]
Hi,

It is very simple:
Fancybox v1-v3 are jQuery plugins and require jQuery as a dependency.
Fancybox v4+ does not require any dependencies.

**Comment by GlenBoonzaier** [comment]
Thanks for the fast feedback, I wasn't aware of this
