### ISSUE TITLE
正确引入 fancybox 后，点击图片并没有任何反应

### ISSUE THREAD

**Issue by kuole-o** [fancyapps/ui#595]
### Describe the bug

可以在这个页面查看示例：[https://blog.guole.fun/posts/17314/](https://blog.guole.fun/posts/17314/)

期望获得指引，因为没有任何报错，我不知道如何解决……

### Reproduction

我不知道如何出现的问题。之前都能正常使用   偶然发现图片无法点击放大了……

**Comment by fancyapps** [comment]
Hi,

You have not included a CSS file, therefore Fancybox is not visible.

**Comment by kuole-o** [comment]
Problem solved, I admit that I was negligent. Thank you very much for your advice
