### ISSUE TITLE
youtube video start time

### ISSUE THREAD

**Issue by onderakbulut** [fancyapps/ui#596]
### Describe the bug

`<button data-fancybox data-width="640" data-height="360" defaultType="youtube" data-small-btn="true" href="https://youtu.be/rahRaVtEQaM?t=15m43s">Video</button>`

`Fancybox.bind("[data-fancybox]", {});`

youtube video not starting stated duration 15m43s

### Reproduction

is there a parameter I forgot

**Comment by fancyapps** [comment]
Hi,

Thanks for reporting, this has been fixed in the latest release.

https://jsfiddle.net/fxyz69o4/
