### ISSUE TITLE
Manually update Carousel position

### ISSUE THREAD

**Issue by virgilejanssen** [fancyapps/ui#597]
### Is your feature request related to a problem? Please describe.

I wrote a function that changes the Carousel position on scroll. However, when I then click on an arrow or drag the carousel (with dragFree set as true), the transition starts from the last position before the scroll.

### Describe the solution you'd like

How can I manually update the value saved after scrolling / Where is it stored?

**Comment by fancyapps** [comment]
Hi,

Could you share your progress using any code playground?

Basically, Carousel uses Panzoom component under the hood, therefore you should interact with it.

**Comment by fancyapps** [comment]
Here is one possible solution - https://jsfiddle.net/v1tjh6ma/ (this is for a vertically aligned carousel, but should be similar to a horizontal carousel).

Sorry, custom animations or the wheel event were not considered beforehand when these components were built, therefore the solution is not that elegant.

**Comment by virgilejanssen** [comment]
Yes, that's exactly what I was looking for. I didn't know Panzoom was what I needed to interact with but it opens a lot of possibilities. Thanks a lot.

**Comment by fancyapps** [comment]
If you could update to the latest, you can do the following:

```js
myCarousel.container.addEventListener("wheel", (event) => {
  myCarousel.panzoom?.applyChange({
    panY: event.deltaY * -1,
  });

  myCarousel.setPageFromPosition()
});
 ```

https://jsfiddle.net/6ojbmsa8/
