### ISSUE TITLE
Wrong export in l10n TS files

### ISSUE THREAD

**Issue by GAL-CS** [fancyapps/ui#598]
### Describe the bug

The export in `@fancyapps/ui/l10n/Fancybox/es.ts` is named `en` and should be named `es`.
The export in `@fancyapps/ui/l10n/Fancybox/ja.ts` is named `js` and should be named `ja`.
The export in `@fancyapps/ui/l10n/Fancybox/lv.ts` is named `en` and should be named `lv`. Also this file includes the english panzoom translations instead of the latvian translations.

### Reproduction

_No steps needed._

**Comment by fancyapps** [comment]
Hi,

Thanks for the reporting, it will be fixed in the next release.

**Comment by fancyapps** [comment]
I hope everything is fine now after the last release, sorry about that.
