### ISSUE TITLE
the Iframe toolbar has a display problem

### ISSUE THREAD

**Issue by TIME-GATE** [fancyapps/ui#601]
### Describe the bug

if there is only one iframe, then it overlaps with toolbar， but if add an image display, and the toolbar will be below, as if this is normal.

### Reproduction

<img width="1890" alt="image" src="https://github.com/fancyapps/ui/assets/16061625/298b5f9a-856a-4b58-a9da-24bda19f9408">

<img width="1903" alt="image" src="https://github.com/fancyapps/ui/assets/16061625/d1539fe7-9ac2-4b8c-9c56-8fff3fc297d3">

**Comment by fancyapps** [comment]
I could not understand your comment, but I guess you just need to set `Toolbar: { absolute:false }`
