### ISSUE TITLE
Is there any option for setting autoplay off for video url ?

### ISSUE THREAD

**Issue by token-codeclouds** [fancyapps/ui#602]
### Is your feature request related to a problem? Please describe.

Is there any option for setting autoplay off for video url ? I am using vimeo link with fancybox. when opening the video its automatically starting but I want to off default autoplay and when click on play button it should play.

### Describe the solution you'd like

Fancybox.bind("[data-fancybox]", {
  // if here i can pass any param for video autoplay false
});

**Comment by fancyapps** [comment]
Hi,

Actually, you have two options.

1. Disable using data attribute -  `data-video-autoplay="false"`. Example:

```js
<a href="https://www.youtube.com/watch?v=UFHscDioNWQ" data-video-autoplay="false" data-fancybox="video-gallery">
    <img alt="" width="200" src="http://i3.ytimg.com/vi/UFHscDioNWQ/hqdefault.jpg">
</a>
```

2. Disable using JS options:

```js
Fancybox.bind('[data-fancybox]', {
  Html : {
    videoAutoplay: false
  }
});    
```
