### ISSUE TITLE
Fancybox 3.5.7 youtube video is loading too long in iframe type because of connection reset.

### ISSUE THREAD

**Issue by achieffment** [fancyapps/ui#603]
### Describe the bug

Hello, i'm using FancyBox v3.5.7.

I'm trying to open videos:
```
$(".video_link").fancybox({
	type: "iframe",
	maxWidth    : 800,
	maxHeight   : 600,
	fitToView   : false,
	width       : '70%',
	height      : '70%',
	autoSize    : false,
	closeClick  : false,
	opacity: true,
});
```

And having an issue in console:
```
GET https://yt3.ggpht.com/ytc/AIf8zZTfPlmAwsl_frOVh6pvckL4eXL0ssJlzeT9rLYQkg=s88-c-k-c0x00ffffff-no-rj net::ERR_CONNECTION_RESET
POST https://play.google.com/log?format=json&hasfast=true&authuser=0 net::ERR_CONNECTION_RESET
GET https://static.doubleclick.net/instream/ad_status.js net::ERR_CONNECTION_RESET
```

Some scripts from youtube can not be loaded (presumably in my country) and modal window is loading too long until last script will send error connection. 
But video is playing in background and working fine, but fancybox is waiting all the scripts of inserted iframe or window loading.
So i just see loading pin and listen music of video. At the end of scripts loading i can see the video.

I'm using not last version, but i can not upgrade, because of big site based on this version. Didn't find any info about how to disable fancybox loading or how to set loading timeout for iframe.

Help please.

### Reproduction

I'm trying to open videos:
```
$(".video_link").fancybox({
	type: "iframe",
	maxWidth    : 800,
	maxHeight   : 600,
	fitToView   : false,
	width       : '70%',
	height      : '70%',
	autoSize    : false,
	closeClick  : false,
	opacity: true,
});
```

**Comment by fancyapps** [comment]
Hi,

First, Fancybox v3 has been discontinued for many years. 

Anyway, maybe try disabling iframe preloading, see https://web.archive.org/web/20210325170940/https://fancyapps.com/fancybox/3/docs/#iframe

Also, Fancybox works the same regardless of the version - the embedable URL is formatted and the iframe element is created. The rest depends on the browser and content provider. In your case I think the ad blocker is affecting the loading.
