### ISSUE TITLE
Can't use fancybox

### ISSUE THREAD

**Issue by hunli12312** [fancyapps/ui#604]
### Describe the bug

I am creating the website for my django project.

In the html file, I wrote 

```html
                    <div class="portfolio-item image-zoom">
                        <div class="image-zoom-wrapper">
                            <img src="{% static 'images/bullet.png' %}">
                        </div>
                        <a href="{% static 'images/bullet.png' %}" data-fancybox="gallery" class="iconbox"><i class="ri-search-2-line"></i></a>
                    </div>
``` 

No matter how hard I tried, I just couldn't use fancybox. I have no clue. Is that because the path?

```html
 href="{% static 'images/bullet.png' %}
``` 

### Reproduction

Just adding data-fancybox="gallery". Then nothing happened.

**Comment by fancyapps** [comment]
Hi,

Simply follow the docs - https://fancyapps.com/fancybox/getting-started/#option-1-declarative

> Unlike previous versions, you have to call Fancybox.bind() method to enable Fancybox.

Other than this, I don't know what else to comment without seeing your live page/demo.
