### ISSUE TITLE
Can not override CSS for class "fancybox__content"

### ISSUE THREAD

**Issue by CodeTappert** [fancyapps/ui#608]
### Describe the bug

I am currently embedding an iframe using fancybox. 

The iframe loads fine and works as expected. But is has a white border around it.

After some searching i found that the class "fancybox_content" has a padding of "2rem" which causes the background to show.

I trief overriding the CSS with 

```
.fancybox__content {
  padding: 0 !important; 
}

```

which did nothing.

So please help. (I tried https://jsfiddle.net/fL53wzdr/1/ (a fiddle you provided to another user) to see if it is a global problem and yes it also happens there)

![grafik](https://github.com/fancyapps/ui/assets/38758606/b3a68a3c-d63d-4389-969f-87fb7838f434)

### Reproduction

1. Add a iframe to the fancybox (and use content that isnt white)
2. See a white border around the content of the iframe
3. Try to override it with CSS

**Comment by fancyapps** [comment]
Hi, Use this CSS snippet:

```css
.fancybox__slide.has-iframe .fancybox__content {
  padding: 0;
}
```

https://jsfiddle.net/zbwfpqht/

**Comment by CodeTappert** [comment]
It worked like you described.

Just a note for everybody so that you dont do the same mistake as me and waste hours on this...

Check if your script tag uses "scoped" when using vue. My script tag in my component did and when i created a script tag without "scoped" it worked
