### ISSUE TITLE
Limited Toolbar Customization Options for HTML5 Video Elements

### ISSUE THREAD

**Issue by zeel0562** [fancyapps/ui#613]
### Is your feature request related to a problem? Please describe.

We can include toolbar options for images, allowing customization such as full screen, download, and close functionalities. However, when it comes to HTML videos, we are limited to having only the close icon option, and additional features like fullscreen and download cannot be added.

### Describe the solution you'd like

I would like a solution that enables the inclusion of toolbar options for both images and HTML videos. Specifically, I want the ability to customize the toolbar for images, including options like full screen, download, and close. For HTML videos, I am seeking an enhancement that allows for more flexibility, enabling the addition of features such as fullscreen and download options, in addition to the existing close icon.

**Comment by fancyapps** [comment]
Hi,

Since the toolbar functionality is mostly useful for images, it is disabled by default if no image is found in the gallery. You can enable the toolbar for any content type using the `enabled` option, demo - https://jsfiddle.net/L7cknjra/
