### ISSUE TITLE
fontawesome on nexTpl/prevTpl only works if pointer-events: none

### ISSUE THREAD

**Issue by HongPong** [fancyapps/ui#614]
### Describe the bug

Hello, I wanted to use the fontawesome `<i>` style tags to put in arrows. Noticed that the arrows don't give the action although the surrounding button box still causes the event. If CSS attribute `pointer-events: none` is set on the `<i>` elements then the click event works as normal. However the standard CSS :hover pseudoclass stops working.

Working Example:
https://jsfiddle.net/vrkswd3j/1/

As a workaround I can use SVG for this instead of the `<i>` tag. Never ran into this with fontawesome before. It's not that big an issue but I thought sort of interesting (there should not be any extra event listener in the `<i>` tag) and reproducible.

### Reproduction

https://jsfiddle.net/vrkswd3j/1/

```javascript
    let carousel = new Carousel(els[i], {
      infinite: true,
      center: false,
      slidesPerPage: 4,
      transition: false,
      Navigation: {
        // nextTpl: "next",
        // prevTpl: "prev",
        nextTpl: "<i class=\'fa-solid fa-circle-arrow-right\' tabindex=\'-1\'></i>",
        prevTpl: "<i class=\"fa-solid fa-circle-arrow-left\" tabindex=\"-1\"></i>"
      }
```

### Additional context

Ah This has been more known than I realized:
* https://stackoverflow.com/questions/21653978/font-awesome-icon-preventing-click-in-parent-button
* https://stackoverflow.com/questions/58372943/how-to-make-font-awesome-icon-clickable-event

**Comment by fancyapps** [comment]
Hi,

I am very sorry, I somehow forgot to respond. Yes, you are supposed to add CSS `pointer-events: none`.
