### ISSUE TITLE
Unable to pass tpl with Fancybox.show

### ISSUE THREAD

**Issue by carasmo** [fancyapps/ui#615]
### Describe the bug

I don't know if this is a bug or not, but when I use Fancybox.show, the tpl option doesn't work.

### Reproduction

        document.querySelector(".foobar a").addEventListener("click", (e) => {
            e.preventDefault();

            Fancybox.show([{
                    src: "#service-menu",
                    type: "inline",
                    compact: false,
                    closeButton: false,
                    tpl: {
                        main: `<div class="fancybox__container custom--modal-container" role="dialog" aria-modal="true" aria-label="{{MODAL}}" tabindex="-1">
          <div class="fancybox__backdrop hooked_modal_backdrop"></div>
          <div class="fancybox__carousel"></div>
              <button data-fancybox-close class="f-button is-close-btn" title="{{CLOSE}}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" tabindex="-1"><path d="M20 20L4 4m16 0L4 20"/></svg></button>
        </div>`
                    },

                }]

            );

        });

**Comment by fancyapps** [comment]
Hi,

Note that not all options can be set per item, set them like this:

```js
Fancybox.show(
  // Array containing gallery items
  [
    // Gallery item
    {
      src: "#dialog-content",
      type: "inline",
    }
  ], 
  // Gallery options
  {
    compact: false,
    closeButton: false,
    tpl: {
      main: `<div class="fancybox__container custom--modal-container" role="dialog" aria-modal="true" aria-label="{{MODAL}}" tabindex="-1">
      <div class="fancybox__backdrop hooked_modal_backdrop"></div>
      <div class="fancybox__carousel"></div>
          <button data-fancybox-close class="f-button is-close-btn" title="{{CLOSE}}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" tabindex="-1"><path d="M20 20L4 4m16 0L4 20"/></svg></button>
      </div>`
    },
  }
);
```

https://jsfiddle.net/4mekvpqb/

**Comment by carasmo** [comment]
Thank you!!!
