### ISSUE TITLE
Custom hash values don't work

### ISSUE THREAD

**Issue by chimir** [fancyapps/ui#617]
### Describe the bug

if digits with hyphenated numbers are used in the data-slug value

### Reproduction

https://chimir.github.io/slug/#cat - work
https://chimir.github.io/slug/#bird-1 - don't work

**Comment by fancyapps** [comment]
Hi,

The script looks for an element whose hash value is `bird` and doesn't find one, and that's all.

**Comment by freezyh** [comment]
> Hi,
> 
> The script looks for an element whose hash value is `bird` and doesn't find one, and that's all.

fancybox能不能在预览图片的时候移除掉hash，真的很不美观
