### ISSUE TITLE
startIndex not working after upgrading to > 5.0.31

### ISSUE THREAD

**Issue by AndersMad** [fancyapps/ui#619]
### Describe the bug

After upgrading to 5.0.33 (and 5.0.32) the `startIndex` is not honered. It works in 5.0.31.

### Reproduction

`fancybox.fromNodes(myLinksArray, { startIndex: 2 });`

It will show slide 2 but immediately shift to first slide.

### Additional context

comparing latest to v31 - this is extra events fired after the last `done` (there are several of them btw.)
```
Carousel.beforeChange
Carousel.Panzoom.startAnimation
Carousel.selectSlide
Carousel.unselectSlide
Carousel.change
Carousel.Panzoom.beforeTransform
Carousel.Panzoom.afterTransform
Carousel.Panzoom.beforeTransform
Carousel.Panzoom.endAnimation
Carousel.settle
```

**Comment by fancyapps** [comment]
Hi,

I do not see any issue, it works fine -  https://jsfiddle.net/vpedghk6/

**Comment by AndersMad** [comment]
The sample uses https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js and that if identical to my `"@fancyapps/ui": "5.0.31",` - but if I go v33 and update packages, it is not identical. Can you update the CDN source to the latest - then I will try repro again. Maybe add version number to the source - could be helpfull in other situations.

**Comment by fancyapps** [comment]
> Can you update the CDN source to the latest 

Actually, all demos always use the latest version, because the link is created like this:

```html
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
```

If you wanted to load a specific version, you would have to change it like this:

```html
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0.33/dist/fancybox/fancybox.umd.js"></script>
```

Tip: you can easily check the version of the loaded Fancybox JS file:

```
alert(Fancybox.version);
```

Tip2: Make sure that you have included Fancybox JS and CSS files only once.

**Comment by AndersMad** [comment]
This was solved by adding the `data-fancybox` to each link - FYI this is needed after version v5.0.31 - even if doing it all programmatically / no binding.

Sorry about the CDN compare - I was hit by double minify, cache/bad etag and not enough ☕

**Comment by fancyapps** [comment]
hmm, actually it works without those attributes - https://jsfiddle.net/cemr7s93/

**Comment by AndersMad** [comment]
looks odd, very much like I do it - maybe because I use `srcset` and it triggers an observer and then re-creates - I also tried removing the `video` tags etc.. I can try repro later, but the "workaround" if fine and I was just focused on the "regression" state of it all.. NOTE: It only does it the first time: open, it goes to 2, then goes to 1, close, open and it stays on 2.
