### ISSUE TITLE
image quality

### ISSUE THREAD

**Issue by yesyeahvh123** [fancyapps/ui#623]
in lastest version 5, i have problem with image quality, image is blurred when see in lightbox, you can see clearly when using low resolution images, i try in version 3 and 4 did not encounter this problem, can you help?

**Comment by fancyapps** [comment]
Hi,

>  you can see clearly when using low resolution images

I am sorry, but I do not see any issue, could you, please, show some live page/demo?

**Comment by yesyeahvh123** [comment]
Thanks for reply, here is demo https://wpmgm.sytes.net/2024/03/02/fdhdfgdg/

**Comment by fancyapps** [comment]
Well, I don't see any blurring, your images look the same to me if I open them in a new tab.

**Comment by yesyeahvh123** [comment]
If you look closely you will see the difference.
In version 4.0.31 i have problem on movile if i swipe up/down to close lightbox, i must Press the back button twice to return to the previous page. You can check the website address above again, thanks

**Comment by yesyeahvh123** [comment]
i use this code 
function enqueue_fancybox() {
    wp_enqueue_style('vdh-fancybox', 'https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0.31/dist/fancybox.min.css', array(), false, false);
    wp_enqueue_script('vdh-fancybox', 'https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0.31/dist/fancybox.umd.min.js', array('jquery'), false, true); 
}
add_action('wp_enqueue_scripts', 'enqueue_fancybox');



function vdh_fancybox_gallery() {
    ?>
    <script>
        jQuery(document).ready(function($){
            $('.wp-block-gallery a').attr('data-fancybox', 'gallery');
            Fancybox.bind("[data-fancybox]", {

				groupAll: true,
                hideScrollbar: false,
				arrows: false,
				Carousel: {
					  transition: "slide",
					},
				// Disable image zoom animation on opening and closing
			    Images: {
						zoom: false
					},
					// Custom CSS transition on opening
				showClass: "f-fadeIn",
				//wheel: "slide", jss
				Thumbs: {
					autoStart: false,
				  },
				
            });
        });
    </script>
    <?php
}
add_action('wp_footer', 'vdh_fancybox_gallery');

**Comment by yesyeahvh123** [comment]
i use this code

function enqueue_fancybox() {
    wp_enqueue_style('vdh-fancybox', 'https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0.31/dist/fancybox.min.css', array(), false, false);
    wp_enqueue_script('vdh-fancybox', 'https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0.31/dist/fancybox.umd.min.js', array('jquery'), false, true);
}
add_action('wp_enqueue_scripts', 'enqueue_fancybox');

function vdh_fancybox_gallery() {
    ?>
    <script>
        jQuery(document).ready(function($){
            $('.wp-block-gallery a').attr('data-fancybox', 'gallery');
            Fancybox.bind("[data-fancybox]", {

				groupAll: true,
                hideScrollbar: false,
				arrows: false,
				Carousel: {
					  transition: "slide",
					},
				// Disable image zoom animation on opening and closing
			    Images: {
						zoom: false
					},
					// Custom CSS transition on opening
				showClass: "f-fadeIn",
				//wheel: "slide", jss
				Thumbs: {
					autoStart: false,
				  },
				
            });
        });
    </script>
    <?php
}
add_action('wp_footer', 'vdh_fancybox_gallery');

**Comment by yesyeahvh123** [comment]
i see only this code work well on codepen https://codepen.io/StasAlsahanov1975/pen/vYRqRwM, how to apply this code to my code above

**Comment by fancyapps** [comment]
I'm sorry, but I don't know how to help you. Your images look good to me and...the result depends on how the browser renders, you can't really control that. 

For v4, simply disable Hash plugin, check docs, there are samples.

**Comment by yesyeahvh123** [comment]
@fancyapps I already try hash but it not working well, when open lightbox I click back, Instead of closing the lightbox it returns to the previous page

**Comment by fancyapps** [comment]
@yesyeahvh123 This is how browsers work - when you open a page, clicking the back button will take you to the previous page. 

The Hash plugin adds a hash to the URL and adds new entry to the history, so when you click the back button, it will take you to the previous page where Fancybox isn't open, so you see it closing.

**Comment by yesyeahvh123** [comment]
@fancyapps I also encountered the same situation in version 5, why is it worse the higher the version? version 3 everything work fine but i dont like thumbnail at the right and bad animation on mobile

**Comment by yesyeahvh123** [comment]
@fancyapps can i bring thumbnail in version 3 to bottom and smooth animation when swipe image left/right on mobile?

**Comment by fancyapps** [comment]
It is what it is, I did my best and i'm so sorry if you feel disappointed. Also, I am currently working on the next major version, it will be built completely differently. If you want to get involved in the development process with your suggestions, then you are welcome to join the discord channel.
