### ISSUE TITLE
Fancybox - Next picture when you click on the picture

### ISSUE THREAD

**Issue by MrKlarki** [fancyapps/ui#624]
### Is your feature request related to a problem? Please describe.

Hi! :)

There may already be such functionality. When you click on the picture, it will switch to the next picture

### Describe the solution you'd like

Click on the current picture to switch to the next one

An example in the video. I click on the picture with the mouse to switch to the next picture
https://youtu.be/p3vUHVDvI9k

**Comment by MrKlarki** [comment]
Thank you very much! :)

**Comment by matthias-willhaben** [comment]
Could it be that this feature is now gone with version 6.x?

**Comment by fancyapps** [comment]
@matthias-willhaben Sorry, this option is really not available in v6. See, v6 is not just a complete rewrite, but a new look at the entire project, and some features are being dropped to see if anyone uses them (like is Ajax still relevant in 2025?). But yes, this option will be brought back.

**Comment by matthias-willhaben** [comment]
Thanks for the quick reply! I found somewhat of a workaround, but somehow it goes to the next image on the first click and then starts to skip n images for ever further click I do.

```
Fancybox.show(
    images,
    {
        Carousel: {
            on: {
                click: (instance) => {
                    instance.next()
                }
            },
        },
    },
)
```

**Comment by fancyapps** [comment]
You could try like this:

```js
Fancybox.show(
  images
  {
    on: {
      "Carousel.click": (fancybox, carousel) => {
        carousel.next();
      },
    },
    Carousel: {
      Zoomable: {
        Panzoom: {
          clickAction: false,
        },
      },
    },
  }
);
```

https://jsbin.com/simafuboba/edit?html,output

**Comment by matthias-willhaben** [comment]
That worked, thanks a lot for the quick response! 🙇‍♂
