### ISSUE TITLE
Carousel UI like Slick Carousel

### ISSUE THREAD

**Issue by AdamBauerle** [fancyapps/ui#626]
I see some UI settings that would get autoplay working similar to Slick, but I don't see a way to make the FancyApps carousel to "slide" like the Slick carousel works (found here: https://kenwheeler.github.io/slick/). I'd like to use all FancyApps (carousel and fancybox) instead of having to mix Slick for carousel and fancybox. Ideally, we'd like the carousel to autoslide by default, letting the user to slide it back manually, and then autoplay (slide) again once the interaction leaves the carousel. No UI required (i.e., buttons) to navigate. All done via mouse cursor (or touch on touch enabled devices).

![image](https://github.com/fancyapps/ui/assets/51344596/7ebda634-1b21-4fb8-973a-b432aa5ba0d9)

Please advise. Thank you!
Adam

**Comment by fancyapps** [comment]
Hi,

It could be something like this - https://jsfiddle.net/qhoef2x0/

**Comment by fancyapps** [comment]
Sorry, this is not yet implemented, but it is planned.

**Comment by AdamBauerle** [comment]
Thank you for the update!

Any idea when it is planned to be implemented? We would love to use more of the Fancyapps, but would need the above capabilities.

Thank you!
Adam

**Comment by fancyapps** [comment]
I'm so sorry, I can't say when, but it won't be soon. There will be big changes in this project, and I'm currently building everything from scratch.
