### ISSUE TITLE
In the later versions, it was not possible to achieve where the image would slide and where the progress would be synchronized after turning off the lightbox.

### ISSUE THREAD

**Issue by yyj1983** [fancyapps/ui#628]
### Describe the bug

In the later versions, it was not possible to achieve where the image would slide and where the progress would be synchronized after turning off the lightbox.

### Reproduction

In the later versions, it was not possible to achieve where the image would slide and where the progress would be synchronized after turning off the lightbox.

**Comment by fancyapps** [comment]
I'm sorry, but I don't understand anything. What did you mean by "turning off the lightbox"? What "progress", what to be "synchronized" with what?

**Comment by yyj1983** [comment]
What I mean is, there was a previous version where you could slide the lightbox to, exit the lightbox, and the page content would be displayed there.

**Comment by yyj1983** [comment]
For example, there are 300 images on my page, and I see the 200th one from the first one in the lightbox. At this point, I will exit the lightbox and the content on the page will automatically display at the position of the 200th page.

**Comment by yyj1983** [comment]
How many small versions of 5.0 have you recently removed this useful feature?

**Comment by fancyapps** [comment]
I think I understand what you're trying to say. It should be fixed in the latest release, please, upgrade and check if that works for you.

**Comment by yyj1983** [comment]
Thank you very much. It's already possible. You are excellent
