### ISSUE TITLE
Calling a modal window from a modal window

### ISSUE THREAD

**Issue by Oleksandr07** [fancyapps/ui#629]
If I call a modal from an already open modal, how do I close the previous modal? 
In fancybox version 3, the closeExisting parameter was responsible for this

**Comment by fancyapps** [comment]
Hi,

Sorry, there is currently no such option. Are you opening modal manually or using trigger element? If you open your modal manually, then you could just call `Fancybox.close()` right before opening a new one.

**Comment by Oleksandr07** [comment]
I use the function
`Fancybox.bind( '[data-fancybox]', {
autoFocus: false,
dragToClose: false,
});`

But I can't figure out at what point I should call the function `Fancybox.close()`

**Comment by fancyapps** [comment]
OK, I see, I will add `closeExisting` option in the next update.

**Comment by fancyapps** [comment]
So, the latest version contains that option, see this demo -
https://jsfiddle.net/wcuhbors/

**Comment by Oleksandr07** [comment]
Great, everything works. Thanks
