### ISSUE TITLE
Modal windows are duplicated

### ISSUE THREAD

**Issue by Oleksandr07** [fancyapps/ui#630]
### Describe the bug

If you open a modal window, open another modal window inside it, and then open the previous modal window, instead of destroying the previous instance, it duplicates

### Reproduction

Click link "Open modal 1"
Click link "Open modal 2"
Click link "Open modal 1"

### Additional context

https://codepen.io/Oleksandr07/pen/KKYMrXX
![2024-03-13_13 52 34](https://github.com/fancyapps/ui/assets/11850595/949e332f-1b1d-46e8-a269-98fec4396afc)

**Comment by fancyapps** [comment]
Duplicate of #629
