### ISSUE TITLE
Unexpected :empty selector

### ISSUE THREAD

**Issue by ExileofAranei** [fancyapps/ui#631]
### Describe the bug

Hi, 5.0.34 introduced this style:
```css
.fancybox__container *:empty {
  display: block;
}
```
Is this required style? Because by default it has higher specifity than base classes, `display: block;` is not always wanted for each element with no children. `:empty` ignores pseudo elements, what kinda broke my UI in popup. Maybe there are a way more unexpected side effects with this rule

![image](https://github.com/fancyapps/ui/assets/41694699/afa1f275-a775-47ae-9892-2d639b2cecda)
![image](https://github.com/fancyapps/ui/assets/41694699/76fc5e05-2bf1-4f06-ae0d-5dac1b01ded1)
![image](https://github.com/fancyapps/ui/assets/41694699/2b04a5ee-e65e-4b42-aec3-0bf67a8e4bbf)
![image](https://github.com/fancyapps/ui/assets/41694699/dfa2df5e-0757-44f4-8773-0e5177af68e4)

### Reproduction

A minimal example for issue with pseudo elements:
https://jsfiddle.net/exileofaranei/1Lg9ednh/35/

**Comment by fancyapps** [comment]
It's so typical. This snippet was added to make Fancybox compatible with Shopify so that it works without writing any additional code. But you call this "a bug".

**Comment by ExileofAranei** [comment]
But with this style library enforces me to write some extra code, patch version should not bring that

**Comment by fancyapps** [comment]
Yes I see. I'll adjust the selector so it doesn't affect the content. Sorry for the trouble.

**Comment by ExileofAranei** [comment]
Sorry, my first demo was too poor. There is a better one: https://jsfiddle.net/exileofaranei/zo3vhcbj/1/

**Comment by brendon** [comment]
Just found this too :) It breaks font awesome icons (webfont based) where it's an empty `<i>` with a `::before` to set the character representing the icon in the font.

**Comment by fancyapps** [comment]
It should be fixed in the latest release, sorry for the inconvenience.
