### ISSUE TITLE
Carousel's Thumbnails plugin: removeSlide method bug

### ISSUE THREAD

**Issue by limite1224** [fancyapps/ui#632]
Hi,
I encountered an issue while using Carousel's Thumbnails plugin, and the removeSlide method will not remove the Thumbnails

https://github.com/fancyapps/ui/assets/44696227/9dd8c448-792a-4508-9aa5-5d16d37487c5

**Comment by fancyapps** [comment]
Hi,

Slide removal sync is currently not supported.

**Comment by limite1224** [comment]
thank you. I tried using re-init to handle it

**Comment by limite1224** [comment]
Hi,
I achieved the same effect using Sync plugin. Thank you😊
