### ISSUE TITLE
Where does the gray background load from when the resolution is reduced?

### ISSUE THREAD

**Issue by kosh2323** [fancyapps/ui#636]
Hi, I'm faced with such a task. I use ordinary *jpg images. And I download them locally from the images/fan/ folder that I created, and the group is also called. Here is the code for inserting one slide

`<script>
 Fancybox.bind('[data-fancybox="fan"]', {
        Thumbs : {
          type: "classic"
        }
      });
</script>`

Everything works, but when the resolution is reduced in the code inspector in Chrome, a gray background appears from somewhere, as if from under the image, I can't even understand why and where it comes from, it spoils the design. Help me understand what needs to be done to remove it completely. 
![im01](https://github.com/fancyapps/ui/assets/82117170/a8792ba0-5bd3-444c-a2fb-dbdf8a5496b3) 
![im1](https://github.com/fancyapps/ui/assets/82117170/53d8b084-d16c-4aae-a75c-f02501ce256e)
![im2](https://github.com/fancyapps/ui/assets/82117170/e33f6d43-b481-4546-bb74-1ce9f6151212)
![im3](https://github.com/fancyapps/ui/assets/82117170/e11da0f6-1672-4b0a-935b-bd59272a3a04)

**Comment by kosh2323** [comment]
The image that I am inserting
[https://postimg.cc/9z6z3FhM](url)

**Comment by fancyapps** [comment]
Hi,

For small screen devices, to save space, the caption is placed over the content, you can disable this feature using `compact:false` option, see this demo - https://jsfiddle.net/fmLdgtc7/

**Comment by kosh2323** [comment]
Thank you very much, you helped a lot, and success in all your projects!
