### ISSUE TITLE
Request to use fancyapps in open source projects

### ISSUE THREAD

**Issue by cweijan** [fancyapps/ui#637]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

I'm the author of the VS Code extension [Office Viewer](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office), currently I'm looking to replace the UI library for viewing images, I found fancyapps which are beautiful, but it's paid.

Can I apply to use it for free in Office Viewer? Instead, I will add fancyapps information to the displayed page..

**Comment by fancyapps** [comment]
Hi,

Usually, it is not allowed to use Fancyapps software in open source projects, but you can use it in your project with a disclaimer and without making a payment.
