### ISSUE TITLE
Fancybox PDF Presentation mode

### ISSUE THREAD

**Issue by unknown1818** [fancyapps/ui#644]
### Is your feature request related to a problem? Please describe.

Hi,

Is there a option to show pdf files at fullscreen and presentation mode?
Fullscreen its too small

### Describe the solution you'd like

Option to get presentation mode

**Comment by fancyapps** [comment]
Hi,

I do not know what do you mean by "Presentation mode", but you can control dimensions of the content using CSS. Check the samples in the documentation.

**Comment by unknown1818** [comment]
When open .pdf in chrome and click three dots you have option for presentation mode, pages are displayed fullscreen without control borders on fancybox this option is disabled

**Comment by fancyapps** [comment]
You see, parsing and rendering PDF files is out of the scope of this project. So, how do you display them? Inside iframe tag? Then the browser decides what to do. As html? Using [PDF.js](https://mozilla.github.io/pdf.js/), then it is controlled by that script.
