### ISSUE TITLE
Vertical carousel doesn't work

### ISSUE THREAD

**Issue by ermk28** [fancyapps/ui#649]
### Describe the bug

For some reason, the vertical carousel is not working, I've tried different ways to pull this vertical carousel, but either it doesn't even grab the carousel or it pulls horizontally, any tips on how to solve this?

https://codepen.io/Erick-Moura-Ruiz-Guedes-Cardoso/pen/oNOJrZJ

### Reproduction

https://codepen.io/Erick-Moura-Ruiz-Guedes-Cardoso/pen/oNOJrZJ

https://github.com/fancyapps/ui/assets/167920678/4d52aa13-8b8f-4c4b-bcd8-b6b66284f76c

### Additional context

I need to do something similar to this, I already had an idea of ​​the code for the scroll to click on next and prev, but without the vertical carousel the animation wouldn't be good

https://github.com/fancyapps/ui/assets/167920678/53790756-f32d-4cf4-a374-343607ff2c15

**Comment by fancyapps** [comment]
Hi,

I'm surprised you expected it to be vertically scrollable since you've created a layout with no scrollable content. Just set the height of the container to be less than the height of the content, for example:

```css
.hero__items {
  height: 100px;
}
```

See https://fancyapps.com/carousel/getting-started/#add-markup
