### ISSUE TITLE
Description of `reveal` and `done` events are not accurate and behaviour is undesirable

### ISSUE THREAD

**Issue by chrisdeeming** [fancyapps/ui#650]
### Describe the bug

The description of the `reveal` event is as follows:
> Content is ready to be displayed on one of the slides

The description of the `done` event is as follows:
> Content is revealed on one of the slides

Now look at this JsFiddle and click the button:
https://jsfiddle.net/r9ea80Lq/1/

In the console you will see the following logs:

```
"done: 0"
"done: 1"
"done: 2"
```

`done` is being fired for all slides, not just the single slide that has been displayed. `reveal` has the same behaviour therefore its behaviour is practically indistinguishable from `loaded`.

The behaviour does not seem to match the description, nor does the behaviour seem desirable. There is no event which fires for a single slide. So at the very least adding this would be a benefit.

### Reproduction

View the JsFiddle and click the button:
https://jsfiddle.net/r9ea80Lq/1/

**Comment by fancyapps** [comment]
Hi, The explanation and solution is already provided here - https://fancyapps.com/fancybox/api/events/ (see second sample). Or you could disable preloading if that is bothering you.

**Comment by chrisdeeming** [comment]
I see that and I am using those events.

"Content is revealed on one of the slides" does not seem to be the correct description for what happens when the `done` event is fired.
