### ISSUE TITLE
Vimeo parameters have no effect

### ISSUE THREAD

**Issue by petehjfd** [fancyapps/ui#651]
### Describe the bug

Hi

I would like to use a custom color for the Vimeo embed player.  [As per the docs](https://fancyapps.com/fancybox/plugins/html/#vimeo), my code looks like this:

```js
Fancybox.bind("[data-fancybox]", {
    vimeo: {
        color: 'ff0000'
    }
});
```

but the embed URL in the output still contains the default `00adef` color.  This is exactly what gets output by Fancybox:

```html
<iframe class="fancybox__iframe" id="fancybox__iframe_1_0" allow="autoplay; fullscreen" scrolling="auto" src="https://player.vimeo.com/video/100902001?byline=1&amp;color=00adef&amp;controls=1&amp;dnt=1&amp;muted=0" data-ready="true"></iframe>
```

### Reproduction

- Install fancybox
- Add `data-fancybox` to an `a` element with a Vimeo video URL as the `href` value
- Instantiate fancybox on the element with the above code

**Comment by petehjfd** [comment]
I should also add, I've also specified a color in the embed settings for the video in Vimeo (not the example video I've used above) but it gets overridden by the color applied by Fancybox.

I think it would make more sense for Fancybox to omit the color attribute entirely if the vimeo.color option is not specified when Facybox in instantiated.

**Comment by fancyapps** [comment]
Hi, @petehjfd 

Sorry about the confusion, the correct syntax is like this:

```js
Fancybox.bind('[data-fancybox]', {
  Html : {
    vimeo: {
      color: 'ff0000'
    }
  }
});
```

**Comment by petehjfd** [comment]
Ah perfect, that works, thanks!
