### ISSUE TITLE
Unable to click on a link positioned over a Fancybox/Carousel

### ISSUE THREAD

**Issue by hybrid897** [fancyapps/ui#660]
### Describe the bug

I have an absolutely positioned element with a clickable link in it that overlays a carousel slide, the carousel is inside a fancybox. When I left click the link the fancybox opens instead of going to the link. Middle clicking the link seems fine. 

How can I stop fancybox from opening for clicks on my overlayed element? Thanks

![image](https://github.com/fancyapps/ui/assets/52395382/50539bb6-6d47-45bd-8a6c-1b5c4e61c9ec)

### Reproduction

https://stackblitz.com/edit/react-ts-yfbtny?file=style.css

**Comment by fancyapps** [comment]
Hi,

The simplest solution would be create new wrapping element around your images, example:

```html
<div className="f-carousel__slide relative">
  <div data-fancybox="gallery"
       data-src="https://lipsum.app/id/60/1600x1200"
       data-thumb-src="https://lipsum.app/id/60/200x150">
    <img
         alt=""
         src="https://lipsum.app/id/60/400x300"
         width="400"
         height="300"
         />
  </div>
  <div className="custom-caption">Hello <a href="https://www.google.com">Test Link</a></div>
</div>
```
