### ISSUE TITLE
Fancybox: Hide caption when idle?

### ISSUE THREAD

**Issue by tou0125** [fancyapps/ui#662]
### Is your feature request related to a problem? Please describe.

I would like to hide the caption along with the toolbar when idle mode is activated. At the moment, only the toolbar is hidden but the caption remains visible.

### Describe the solution you'd like

Would it be possible to hide the caption along with the toolbar if idle is set to true?
Rather than trying some alternative hiding the caption, I was wondering if there is any easy way to do this already?

**Comment by fancyapps** [comment]
Hi,

You could listen to `setIdle` / `endIdle` to do your stuff. There is no built-in options for that.
