### ISSUE TITLE
iframe performance issue

### ISSUE THREAD

**Issue by TIME-GATE** [fancyapps/ui#663]
### Describe the bug

sometimes open the website is very by `iframe`， it will be normal open this website from new page tab

### Reproduction

Embedding a website via `iframe` can be slow to open, sometimes it gets stuck, I don't know the reproduction steps yet, it's easy to reproduce try a few times, but if I open the website directly, it's never slow, even if I clear all the cache directly.

### Additional context

![image](https://github.com/fancyapps/ui/assets/16061625/f99050eb-99bc-4a47-a2b8-d13ab87d8877)

**Comment by fancyapps** [comment]
Hi,

Try disabling auto sizing and/or preload:

```js
Fancybox.bind("[data-fancybox]", {
  Html: {
    autoSize: false,
  },
  preload : false
});
```

Sorry, I don't think there's anything else that can be done that will help.

**Comment by TIME-GATE** [comment]
@fancyapps  thanks,  got it
