### ISSUE TITLE
Vertical thumbnails?

### ISSUE THREAD

**Issue by mumus** [fancyapps/ui#667]
### Is your feature request related to a problem? Please describe.

Hello. It is possible to make option like "vertical" for thumbs and place them on the left of gallery?
![image](https://github.com/fancyapps/ui/assets/3994560/eac3afb4-22b1-485f-b0ab-eb4bab2dca55)

### Describe the solution you'd like

Maybe option like 'vertical' in Thumbs plugin?

**Comment by fancyapps** [comment]
Hi,

Thumbnails are built around Carousel component and you can use the same options using `Thumbs.Carousel` as for any other carousel. Here is a very quick demo - https://jsfiddle.net/8g9uc1kt/ and here is a more complete example - https://stackblitz.com/edit/js-8zg2gb?file=index.html,index.js,style.css

```js
new Carousel(document.getElementById("myCarousel"), {
  Dots: false,
  Thumbs: {
    type: 'classic',
    Carousel : {
      axis: "y"
    }
  }
}, { Thumbs });
```
