### ISSUE TITLE
Carousel thumbs bug: Thumb src doesn't work on addSlide, prependSlide and appendSlide

### ISSUE THREAD

**Issue by devjam1n** [fancyapps/ui#672]
### Describe the bug

When using addSlide, prependSlide or appendSlide on a carousel with thumbs, the thumb is added, but src is set as some base64 string instead of the actual data-thumb-src attribute specified in the html key value when adding a slide.

### Reproduction

[Codepen demo](https://codepen.io/devjamin/pen/YzoqXdJ)

**Comment by fancyapps** [comment]
Hi,

You should actually use the `thumb` attribute, for example:

```
 carousel.addSlide(1, {
    html: `<div class="f-carousel__slide" data-thumb-src="https://picsum.photos/640?4">
          <img alt="" height="600" itemprop="image" data-lazy-src="https://picsum.photos/640?4" width="600" /></div>`,
    thumb: 'https://picsum.photos/640?4'
  })
```

That base64 string is a dummy 1x1 transparent image to avoid displaying broken image "thing".

**Comment by devjam1n** [comment]
Thanks, that works perfectly :)
Apologies for overlooking it in the documentation
