### ISSUE TITLE
Deceleration re-implementation?

### ISSUE THREAD

**Issue by devjam1n** [fancyapps/ui#673]
### Is your feature request related to a problem? Please describe.

Deceleration is managed by continuously updating the transform property via requestAnimationFrame. However, in WebKit this method is throttled when low power mode is enabled, resulting in a laggy deceleration.

### Describe the solution you'd like

Instead of relying on JS to continuously update the transform property for deceleration, we can set the final transform value directly and temporarily apply a transition duration. This duration can e.g be calculated based on the friction, velocity configuration, and the distance slid until touchend/mouseup. By doing so, the browser only needs to handle a single transition, ensuring smooth deceleration without depending on continuous possible throttled RAF updates.

### Additional context

I've digged into a couple of popular sites carousel slider implementations. Almost none used JavaScript for deceleration. Instead, I observed them using either `scroll-snap-type` with `scroll-snap-stop` or the approach I suggested, which adds a temporary transition duration.

**Comment by fancyapps** [comment]
Hi, Thanks for the suggestion!

**Comment by devjam1n** [comment]
Thanks for the answer and alright :)
