### ISSUE TITLE
图片预览的时候，能不能不要在url添加hash

### ISSUE THREAD

**Issue by freezyh** [fancyapps/ui#678]
### Is your feature request related to a problem? Please describe.

每次点击预览图片的时候url都会添加当前图片的hash，在单页面开发，如vue、react上很不美观，在苹果手机的浏览器上也有兼容性，能不能图片预览的时候直接在document上创建元素就可以，不要改变url
![image](https://github.com/user-attachments/assets/f2f09f6c-3160-4031-afc1-3835b54b9af0)

### Describe the solution you'd like

图片预览的时候不改变url，url上hash内容可以放到本地存储，当关闭预览的时候清除存储标记或者点击预览的是判断有存储过标记就先清除

**Comment by fancyapps** [comment]
English, please
