### ISSUE TITLE
Custom template for prev/next buttons

### ISSUE THREAD

**Issue by tolchai** [fancyapps/ui#686]
### Describe the bug

Hi,

I am probably missing something very obvious, but is there a way to customize template for prev/next buttons?

I am unable to do that with tpl object (seems to manage only main and closeButton) and it works within Toolbar.items.prev and Toolbar.items.next only if those are actually added to Toolbar. 

### Reproduction

Default functionality

**Comment by fancyapps** [comment]
Hi, Here is an example:

```js
Fancybox.bind('[data-fancybox="gallery"]', {
  Carousel : {
    Navigation : {
      nextTpl: "Next page",
      prevTpl: "Previous page",
    }
  }
});    
```

https://jsfiddle.net/z5p13kht/
