### ISSUE TITLE
Carousel autoplay

### ISSUE THREAD

**Issue by alexxxseo** [fancyapps/ui#69]
Hello!

What about carousel autoplay?
Like this: https://fancyapps.com/playground/Be with autoplay/slideshow..

**Comment by AndersMad** [comment]
@alexxxseo He did this straight after it would seem and works just fine: Add carousel.autoplay and I use a module load so `xx.Carousel.Plugins["Autoplay"] = yy.Autoplay` and option `Autoplay: { timeout: 1000 }`

**Comment by fancyapps** [comment]
Hi,

Yes, @AndersMad is right, there is a new (optional) plugin for Carousel. To use it, either include `carousel.umd.js` file or import as module (and then register as `Carousel.Plugins.Autoplay = Autoplay;`). Documentation will be updated soon, but customization is very simple, example:

```JS
let myCarousel = new Carousel(document.querySelector("#myCarousel"), {
 Autoplay: {
  timeout : 1000,
  hoverPause : true
 },
});
```

**Comment by fancyapps** [comment]
See https://fancyapps.com/docs/ui/carousel/plugins/autoplay
