### ISSUE TITLE
how to change default load error image 

### ISSUE THREAD

**Issue by zenonux** [fancyapps/ui#694]
### Is your feature request related to a problem? Please describe.

can not change  default load error image

### Describe the solution you'd like

```<div  class="f-carousel"  :data-load-error-src=""></div>```

**Comment by fancyapps** [comment]
Hi, 

Check the documentation for the localization - https://fancyapps.com/fancybox/getting-started/#localization

```js
Fancybox.bind('[data-fancybox="gallery"]', {
  l10n: {
    IMAGE_ERROR : "☹️"
  }
});    
```
https://jsfiddle.net/cfdseq29/

**Comment by zenonux** [comment]
> Hi,
> 
> Check the documentation for the localization - https://fancyapps.com/fancybox/getting-started/#localization
> 
> ```js
> Fancybox.bind('[data-fancybox="gallery"]', {
>   l10n: {
>     IMAGE_ERROR : "☹️"
>   }
> });    
> ```
> 
> https://jsfiddle.net/cfdseq29/

It seems like there is no way to change the default image for failed image loading in the carousel and thumbnail components.

**Comment by fancyapps** [comment]
Sorry, but I just do not understand what do you mean by "default image", or what and why do you expect to happen when image could not be loaded.

**Comment by zenonux** [comment]
> Sorry, but I just do not understand what do you mean by "default image", or what and why do you expect to happen when image could not be loaded.

![image](https://github.com/user-attachments/assets/c84100fc-6cd7-47a2-a646-c749eedb7f95)
the image looks ugly when it fails to load properly.I want to load the image https://test.com/default-error.png when the original image fails to load.

**Comment by fancyapps** [comment]
Oh, I see now, I will think about it for the next version, thanks.
