### ISSUE TITLE
is beforeShow an event? if so should not be listed for explanation under the events section?  

### ISSUE THREAD

**Issue by halukkaramete** [fancyapps/ui#700]
### Describe the bug

I wanted to see which events are available, such as onClose, onNext, onPrev but could not find them on this web page: 
https://fancyapps.com/fancybox/api/events/

What am I doing wrong? 

### Reproduction

...

### Additional context

,,

**Comment by fancyapps** [comment]
"is beforeShow an event?" You can see the list of all available events and some demos on the page you posted. 

Take a note that Fancybox is build around Carousel component, you can access all Carousel events (https://fancyapps.com/carousel/api/events/#available-events) using `Carousel.` prefix, like `Carousel.change`.
