### ISSUE TITLE
What happens when the fancybox interface is closed?

### ISSUE THREAD

**Issue by brendon** [fancyapps/ui#703]
### Describe the bug

I have a weird interaction between Fancybox and Turbo (https://turbo.hotwired.dev/) where when an image is viewed with Fancybox and then the interface is closed Turbo no longer responds to any page refresh requests coming through from the server via web socket. It still receives them but doesn't so anything about them.

I'm just wondering if you could tell me what the close function is doing particularly so I can see why it might be interfering?

### Reproduction

Nothing so far, just investigating at this point.

**Comment by fancyapps** [comment]
Hi, I guess the Hash plugin may be interfering with your code, so please try disabling it first.

**Comment by brendon** [comment]
Amazing! That fixed it. I guess Throws a wobbly if it doesn't get full control over the location. Thank you so much, that saved a lot of time :D
