### ISSUE TITLE
closeButton OUTSIDE

### ISSUE THREAD

**Issue by fetfurmoz1985** [fancyapps/ui#704]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css" />

    <style>
    	.popup-css.fancybox__content .is-close-btn {
    		position: fixed;
    		right: 50px;
    		top: 50px;
    	}
    </style>
</head>

<body>
    <button data-fancybox data-src="#dialog-content">Launch Dialog</button>

    <div id="dialog-content" class="popup-css" style="display:none;max-width:500px;">
        <h2>Hello, world!</h2>
        <p>
            <input type="text" value="" />
        </p>
        <p>
            Try hitting the tab key and notice how the focus stays within the dialog
            itself.
        </p>
        <p>
            To close dialog hit the esc button, click on the overlay or just click the
            close button.
        </p>
        <p>
            Element used to launch the modal would receive focus back after closing.
        </p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <script>
        Fancybox.bind('[data-fancybox]', {

        });
    </script>
</body>

</html>
`

https://github.com/user-attachments/assets/64689256-fa1b-4404-a605-0e502475ec5a

[https://g1t.ru/video/chrome_bqbCGkDle1.mp4](https://g1t.ru/video/chrome_bqbCGkDle1.mp4)

[https://codepen.io/xvjelsst-the-reactor/pen/xxvEPyo](https://codepen.io/xvjelsst-the-reactor/pen/xxvEPyo)

How to move the modal window close button outside the dialog box?

**Comment by fancyapps** [comment]
Hi,

Well, I do not understand. You ask a question and at the same time provide an answer to it, and also video proof of your solution that it works.

**Comment by fetfurmoz1985** [comment]
> Привет,
> 
> Ну я не понимаю. Вы задаете вопрос и одновременно даете на него ответ, а также видеодоказательство того, что ваше решение работает.

The close button appears within the dialog box and then moves to the corner of the browser, but how can I make it move straight to the corner of the browser?

**Comment by fetfurmoz1985** [comment]
> Вы можете отключить CSS-переходы с помощью CSS, но вот еще одно возможное решение:
> 
> ```js
> Fancybox.bind('[data-fancybox]', {
>   closeButton: false,
>   Toolbar : {
>     enabled : true
>   }
> });    
> ```
> 
> https://jsfiddle.net/tm4edvb9/

Oh my god it's so easy thank you

**Comment by fancyapps** [comment]
I think it is caused by the layout reflow that starts reveal animation. Here is one possible workaround:

```css
.fancybox__content>.f-button.is-close-btn {
  display: none;
  position: fixed;
  right: 50px;
  top: 50px;
}

.fancybox__slide.is-done .f-button.is-close-btn {
  display: block;
}
```

https://jsfiddle.net/etpxgqwc/

**Comment by fetfurmoz1985** [comment]
> I think it is caused by the layout reflow that starts reveal animation. Here is one possible workaround:
> 
> ```css
> .fancybox__content>.f-button.is-close-btn {
>   display: none;
>   position: fixed;
>   right: 50px;
>   top: 50px;
> }
> 
> .fancybox__slide.is-done .f-button.is-close-btn {
>   display: block;
> }
> ```
> 
> https://jsfiddle.net/etpxgqwc/

ahaha )), all genius is simple . Thank you very much

**Comment by fetfurmoz1985** [comment]
Another question, how to remove scrolling? [https://g1t.ru/video/chrome_T468Ri5iPt.mp4](https://g1t.ru/video/chrome_T468Ri5iPt.mp4)

[https://codepen.io/xvjelsst-the-reactor/pen/VwoENPr](https://codepen.io/xvjelsst-the-reactor/pen/VwoENPr)
