### ISSUE TITLE
remove scrolling

### ISSUE THREAD

**Issue by fetfurmoz1985** [fancyapps/ui#708]
How to remove scrolling? https://g1t.ru/video/chrome_T468Ri5iPt.mp4

https://codepen.io/xvjelsst-the-reactor/pen/VwoENPr

**Comment by fancyapps** [comment]
First of all, I don't see any scrolling here. I'm guessing you want to disable dragging? Then here's a snippet:

```js
Fancybox.bind('[data-fancybox="popup"]', {
  Carousel: {
    Navigation: false,
    Panzoom : {
      touch: false
    }
  },
});
```

**Comment by fetfurmoz1985** [comment]
> ```js
> Fancybox.bind('[data-fancybox="popup"]', {
>   Carousel: {
>     Navigation: false,
>     Panzoom : {
>       touch: false
>     }
>   },
> });
> ```

Excellent, thank you
