### ISSUE TITLE
There will be performance issues when zooming pictures on the mobile phone, and there is a certain probability that the screen will go black.

### ISSUE THREAD

**Issue by uubbbb** [fancyapps/ui#709]
### Is your feature request related to a problem? Please describe.

The first problem, in fact, many people have mentioned that the experience is not good when it comes to large pictures. But I still write down my experience truthfully. There will be certain performance issues after clicking on the picture to zoom in and out on the mobile phone, as shown in the video below.

https://github.com/user-attachments/assets/e0c7740a-6740-45bd-b95b-eea257311379

However, this problem will not occur when clicking the zoom button in the status bar, as shown in the video below. I wonder if clicking on the picture to zoom can be made the same as button zooming?

https://github.com/user-attachments/assets/f6a3489a-6380-4443-83ed-327f917d0a6d

The second problem is that there is a certain probability that the picture will be lost and the screen will go black after zooming, as shown in the video below.

https://github.com/user-attachments/assets/93f4f704-c9aa-46d0-8317-826dff8ff550

Then I tested a long picture again, and the screen still went black, as shown in the video below.

https://github.com/user-attachments/assets/47c90642-fbde-44af-bf82-ea1ccdd1ed0e

Device information
Mobile phone: Oneplus Ace 2 Pro
Android: 14
Processor: Snapdragon 8 Gen 2
16 GB RAM + 512 GB Storage

First picture: Size: 2.11MB, 3072 × 4096
Second picture: Size: 1.09MB, 1300 × 5294

### Describe the solution you'd like

Optimize the performance better, especially the black screen will be very uncomfortable.

**Comment by fancyapps** [comment]
Sorry, but there's not much to do. You just need to provide lower resolution files for mobile devices using `data-srcset`, see the docs for examples.

**Comment by uubbbb** [comment]
> Sorry, but there's not much to do. You just need to provide lower resolution files for mobile devices using , see the docs for examples.`data-srcset`

Hello,
Excuse me again, I found a WordPress plugin, https://firelightwp.com/pro-lightbox-dark/, which also uses Fancybox, but it will not have performance problems when scaling large pictures on mobile phones. As shown in the video below, the same picture will not have lag and black screen. I wonder if it can inspire you?
Thank you!

https://github.com/user-attachments/assets/b7850bdb-0dcf-4619-b56d-93cbe3915477
