### ISSUE TITLE
FancyBox 5 React Example: Custom Options Not Replicating in UI

### ISSUE THREAD

**Issue by bvr666** [fancyapps/ui#712]
### Describe the bug

I am experiencing an issue where the FancyBox 5 options are not being reflected in the UI when using the React example code provided in the official FancyBox documentation. Despite following the instructions, custom options like Toolbar, Thumbs, and Slideshow do not appear in the UI as expected.

### Reproduction

1. Environment Setup:
    - FancyBox Version: 5.0.36
    - React Version: 18.0.0
    - WordPress Sage Version: Sage 10
2. React Component Based on Official Documentation:
    -   I used the code provided in the FancyBox documentation for React integration.
    

          ```
          import React, { useRef, useEffect } from 'react';
          
          import { Fancybox as NativeFancybox } from '@fancyapps/ui';
          import '@fancyapps/ui/dist/fancybox/fancybox.css';
          
          function Fancybox(props) {
            const containerRef = useRef(null);
          
            useEffect(() => {
              const container = containerRef.current;
          
              const delegate = props.delegate || '[data-fancybox]';
              const options = props.options || {};
          
              NativeFancybox.bind(container, delegate, options);
          
              return () => {
                NativeFancybox.unbind(container);
                NativeFancybox.close();
              };
            });
          
            return <div ref={containerRef}>{props.children}</div>;
          }
          
          export default Fancybox;
          ```
          
          ```
          <Fancybox
                  options={{
                    Carousel: {
                      infinite: false,
                    },
                    Toolbar: {
                      display: {
                        left: ['infobar'],
                        middle: [],
                        right: ['slideshow', 'thumbs', 'close'],
                      },
                    },
                    Thumbs: false,
                  }}
                >
                  <a data-fancybox="gallery" href="https://youtu.be/ld1chylSBvI">
                    <img
                      src="https://lipsum.app/id/60/200x150"
                      width="200"
                      height="150"
                    />
                  </a>
                  <a data-fancybox="gallery" href="https://youtu.be/ld1chylSBvI">
                    <img
                      src="https://lipsum.app/id/61/200x150"
                      width="200"
                      height="150"
                    />
                  </a>
                  <a data-fancybox="gallery" href="https://youtu.be/ld1chylSBvI">
                    <img
                      src="https://lipsum.app/id/62/200x150"
                      width="200"
                      height="150"
                    />
                  </a>
                  <a data-fancybox="gallery" href="https://youtu.be/ld1chylSBvI">
                    <img
                      src="https://lipsum.app/id/63/200x150"
                      width="200"
                      height="150"
                    />
                  </a>
                  <a data-fancybox="gallery" href="https://youtu.be/ld1chylSBvI">
                    <img
                      src="https://lipsum.app/id/64/200x150"
                      width="200"
                      height="150"
                    />
                  </a>
                </Fancybox>
          ```
3. Expected Behavior:
    - The FancyBox UI should reflect the custom options, such as:
    - Toolbar icons (slideshow, thumbs, close) appearing at the top-right corner.
    - Thumbnails view available.
    - Slideshow autoplay should be enabled.

4. Observed Behavior:
    - None of the specified options (Toolbar, Thumbs, Slideshow, etc.) appear in the UI.
    - The FancyBox modal opens, but the toolbar is missing.

5. Troubleshooting Steps Taken:
    - Cleared Browser Cache: Cleared the cache and performed a hard refresh.
    - Checked if [data-fancybox] Elements Are Available: Verified that elements are present in the DOM when binding occurs.
    - Delayed Initialization: Added a setTimeout() to delay the initialization, but this did not make any difference.

6. Additional Context:
    - The project is built in a WordPress Sage 10 environment, and React is being used within this setup.
    - The integration follows the official FancyBox example, but the custom options (Toolbar, Slideshow, etc.) are not visible in the UI.

7. Screenshots

    - Actual behaviour
    
![Screenshot from 2024-11-19 13-30-25](https://github.com/user-attachments/assets/6db4b839-1461-4896-a448-941be3ef97b1)

    - Expected behaviour

![Screenshot from 2024-11-19 13-33-28](https://github.com/user-attachments/assets/72c95095-e877-453c-bf11-f3dcc7a632b2)

**Comment by fancyapps** [comment]
Hi,

I am closing this issue report, because I do not see any issue. I have already explained to you that you can find working examples on the homepage, you can fork and edit them. Try and you will see that everything works fine, as expected. Example - https://stackblitz.com/edit/react-ts-lp7l8l?file=App.tsx 

Sorry, but, since you did not share a fork of any code playground, I am not able to help you in any way.

**Comment by bvr666** [comment]
Hi,

This issue might be platform dependent, the configurations for the platform that we are using I have already mentioned above. We are trying to implement this solution inside our wordpress theme (sage by roots.io) which uses react library for the front-end. I have already shared my code implementation with you and [here](https://teknovalves.krenovate.com/tekno-valves-facility/) you can see the output of that code. If you still need the complete setup let me know I can share the github repository.

If you can share any debugging options to me that will also help. Thanks!
