### ISSUE TITLE
I need to add custom element to each image with template variable, no success

### ISSUE THREAD

**Issue by yurkinx** [fancyapps/ui#80]
Hi, thanks for your project! I need to add custom element to each image in the gallery (I am adding functionality to rate each image with 5 star rating). Trying to use `template` variable, but no success. Is this not supported by the library?
```
var gallery = [
  {
    src: "https://lipsum.app/id/2/800x600",
    thumb: "https://lipsum.app/id/2/80x80",
    caption: "First image",
  },
  {
    src: "https://lipsum.app/id/3/800x600",
    thumb: "https://lipsum.app/id/3/80x80",
    caption: "Second image",
  },
  {
    src: "https://lipsum.app/id/4/800x600",
    thumb: "https://lipsum.app/id/4/80x80",
    caption: "Third image",
  },
];
const customHtml = "whatever..."
Fancybox.show(gallery,  {
   template: {
    main: customHtml
  }   
})
```

**Comment by fancyapps** [comment]
Hi,

There are different ways to do implement this. For example:

The easiest way yould be to put your elements into caption area -
https://fancyapps.com/playground/FA

You could create sidebar -
https://fancyapps.com/playground/FH

Or you could new item in the toolbar -
https://fancyapps.com/playground/FI

**Comment by yurkinx** [comment]
Amazing, thank you so much for the help!

**Comment by fancyapps** [comment]
I think the best would be to put your elements into caption area, but you have to decide what works best for you. Feel free to ask if you need additional help.
