### ISSUE TITLE
Roadmap / Time till stable?

### ISSUE THREAD

**Issue by iJungleboy** [fancyapps/ui#84]
We can't wait to use this in production ;)

Any idea of the timeline, till when it should be stable?

Many thanks for you awesome work!

**Comment by fancyapps** [comment]
Hi,

The current release (4.0.0-beta.2) is pretty stable, 4.0.0 will be released this week with only minor changes that won't break anything. Thanks!

**Comment by iJungleboy** [comment]
Totally awesome - thx!

We're in the process of integrating it into content-templates of 2sxc (https://2sxc.org/en/) and into a demo-gallery app and will also publish it this week 💪
