### ISSUE TITLE
Fancybox 4 seems to be missing Download button support?

### ISSUE THREAD

**Issue by timavaza** [fancyapps/ui#86]
Could you please add Download button support, with it's own attribute, so it can be different to the previewed url.
data-download="download url goes here.."

For example, 
we might use iframe to support pdf js,.. but need the download action to download the original pdf file.

Thank you!

**Comment by Eldzej** [comment]
This is already present, but missing from documentation, and download is hidden by default from the toolbar.
Took me a night spelunking around source files to figure it out myself.

Basically you need to do these two things

1. To your `data-fancybox` items (or whatever you use to target the items), add the following data atribute `data-download-src="link://to.file"`
2. In the initialization script, add the following option  
```
Toolbar: {
    display: ['counter', 'download', 'thumbs', 'close']
},
```
(alter the options as you need, but you have to include the ```download``` keyword. The available options are in the [source file for Toolbar](https://github.com/fancyapps/ui/blob/main/src/Fancybox/plugins/Toolbar/Toolbar.js)

**Comment by fancyapps** [comment]
Hi,

See this docs page - https://fancyapps.com/docs/ui/fancybox/plugins/toolbar

**Comment by timavaza** [comment]
Thank you! I'll take a look :)
