### ISSUE TITLE
[Suggestion] Crossfade (not scroll) as option for carousel

### ISSUE THREAD

**Issue by AndersMad** [fancyapps/ui#89]
Any plans on making the transition crossfade an option? Ofc. this would then only show 1 slide at a time / simple mode - but it could then completely replace e.g.: https://getbootstrap.com/docs/5.0/components/carousel/#crossfade

This would be a nice option for both the carousel and the fancybox that sits on top.

**Comment by fancyapps** [comment]
Hi,

Yes, it is planned, but it is currently not possible to give any ETA.

**Comment by AndersMad** [comment]
maybe I shouldn't have closed this one.. it has a couple of votes too :)

**Comment by fancyapps** [comment]
Hi,

Transitions are available in v5, see example here - https://fancyapps.com/fancybox/#examples
