### ISSUE TITLE
Iframe Keyboard Navigation

### ISSUE THREAD

**Issue by fcjm** [fancyapps/ui#90]
Hello,

I am currently in search for a lightbox alternative for our project and Fancybox looks like a very good choice. Especially the good integration of keyboard controls is a big plus for this plugin.

However, we have some cases where there are multiple Iframes in one gallery. The current behaviour is that once you get into one iframe, you navigate through all the other iframes of the gallery as well before regaining focus in the lightbox overlay.

To replicate this you can simply adjust this playground example (https://fancyapps.com/playground/vk) by duplicating the last video 'a'-tag.

Can a fix for this issue still be expected for the 4.0.0 release?

Thanks in advance!

**Comment by fancyapps** [comment]
Hi,

Sorry, I do not see any issue. Did you try focusing on the page that is not inside iframe (any playground is inside iframe and that may affect the flow depending whether pages are same origin)?

**Comment by fcjm** [comment]
I have already tried to implement it in our application for testing purposes (with no wrapping iframe), and there it has also the same behaviour. 

For example if you take the playground example with only these two videos:

```
  <a
    class="hidden"
    data-fancybox="gallery"
    href="https://www.youtube.com/watch?v=5AwdkGKmZ0I"
  ></a>

  <a
    class="hidden"
    data-fancybox="gallery"
    href="https://www.youtube.com/watch?v=HmZKgaHa3Fg"
  ></a>   
```

And you then press Tab on the last focusable element of the first player (fullscreen button) followed up with Enter it opens the channel of the second video - at least for me. But if you cannot replicate this issue you are probably right and it is an error on my end.

Thanks

**Comment by fancyapps** [comment]
If I press tab multiple times to place it on fullscreen button and then press Enter, fullscreen is activated. Therefore I simply do not understand your issue.

**Comment by fcjm** [comment]
No, my problem lies not with the fullscreen feature itself. It is the button that is focused after the fullscreen button which in my opinion should either be the "Previous", "Next" or "Close" Button again. 

But instead the Iframe from the next slide is focused, although it is not visible to the user. I was trying to say that if I perform a Tab while being on the Fullscreen button, I end up in the next Iframe and upon pressing Enter afterwards, the channel of the next video is opened. 

Sorry if I am being hard to understand, i am trying my best to be as clear as i can. Thank you for investing your time in this.

**Comment by fcjm** [comment]
I hope these two pictures help to illustrate my problem. In Picture 1 the Fullscreen Button in iframe_1_4 is currently focused. Picture 2 shows the state, after i press the Tab button. The focus now lies in iframe_1_5 on the first focusable element (The Channel Selection probably). If I press Enter now, the channel is opened in a new Tab.


![iframe1](https://user-images.githubusercontent.com/22943731/130781207-b8e92909-4267-492b-81c2-e125a298ec66.PNG)
Picture 1


![iframe2](https://user-images.githubusercontent.com/22943731/130781226-10f13e48-25ba-4816-96de-1ce6443d383b.PNG)
Picture 2

**Comment by fancyapps** [comment]
I could not reproduce this issue in the basic example, but I could observe it in that particular demo.

Sorry, I think I can not fix it, because the browser decides where place the focus and, if it happens to be in the iframe, focus event does not bubble up and it is not possible to catch it. The only solution would be to disable preloading.
