### ISSUE TITLE
Consider adding image rotation

### ISSUE THREAD

**Issue by 721806280** [fancyapps/ui#91]
考虑增加图片旋转吗

**Comment by fancyapps** [comment]
Hi,

I believe it is bad practice to force users to press some button to view image correctly. You should fix rotation of your images on the server.

Anyway, this feature request is taken into account, but it does not have high priority.

**Comment by fancyapps** [comment]
Hi,

v5 has been released recently and it offers more functionally, see this example - https://fancyapps.com/fancybox/#transformation-controls
